// SPDX-License-Identifier: FSL-1.1-Apache-2.0
//! Assemble the chart CRD (a Helm *template*) from the structural schema
//! and the `_crdMetas` entry.
//!
//! The output is a Helm template, not pure YAML: `metadata.labels`
//! carries the operator chart's `{{ include "apprafter-operator.labels" }}`,
//! which `serde_yaml` cannot represent (it is a Go template, not YAML).
//! We emit a placeholder there and replace it with the include after
//! serialization.

use anyhow::{Context, Result};
use serde_json::{json, Value};

const LABELS_PLACEHOLDER: &str = "__APPRAFTER_HELM_LABELS__";
const LABELS_INCLUDE: &str = "{{- include \"apprafter-operator.labels\" . | nindent 4 }}";

/// Build the full CRD object from the `_crdMetas` entry + the resolved
/// `spec`/`status` schemas. `metadata.labels` is the placeholder.
pub fn build_crd(meta: &Value, spec_schema: Value, status_schema: Value) -> Result<Value> {
    let group = str_field(meta, "group")?;
    let version = str_field(meta, "version")?;
    let scope = str_field(meta, "scope")?;
    let names = meta
        .get("names")
        .context("_crdMetas: missing names")?
        .clone();
    let plural = names
        .get("plural")
        .and_then(Value::as_str)
        .context("_crdMetas.names: missing plural")?;

    let mut version_obj = json!({
        "name": version,
        "served": true,
        "storage": true,
        "schema": { "openAPIV3Schema": {
            "type": "object",
            "required": ["spec"],
            "properties": {
                "apiVersion": { "type": "string" },
                "kind": { "type": "string" },
                "metadata": { "type": "object" },
                "spec": spec_schema,
                "status": status_schema,
            }
        }},
    });
    if let Some(sr) = meta.get("subresources") {
        version_obj["subresources"] = sr.clone();
    }
    if let Some(pc) = meta.get("printerColumns") {
        version_obj["additionalPrinterColumns"] = pc.clone();
    }

    let mut metadata = json!({
        "name": format!("{plural}.{group}"),
        "labels": LABELS_PLACEHOLDER,
    });
    if let Some(ann) = meta.get("annotations") {
        metadata["annotations"] = ann.clone();
    }

    Ok(json!({
        "apiVersion": "apiextensions.k8s.io/v1",
        "kind": "CustomResourceDefinition",
        "metadata": metadata,
        "spec": {
            "group": group,
            "scope": scope,
            "names": names,
            "versions": [version_obj],
        }
    }))
}

fn str_field<'a>(v: &'a Value, key: &str) -> Result<&'a str> {
    v.get(key)
        .and_then(Value::as_str)
        .with_context(|| format!("_crdMetas: missing string field `{key}`"))
}

/// Render the CRD object to the chart YAML text: GENERATED + SPDX header,
/// the `serde_yaml` body, with the labels placeholder swapped for the
/// helm include.
pub fn render(source_file: &str, crd: &Value) -> Result<String> {
    let body = serde_yaml::to_string(crd).context("serialize CRD to yaml")?;
    let body = body.replacen(
        &format!("labels: {LABELS_PLACEHOLDER}"),
        &format!("labels:\n    {LABELS_INCLUDE}"),
        1,
    );
    Ok(format!(
        "# GENERATED by crdgen from {source_file} — DO NOT EDIT.\n\
         # Run `just gen-crds` to regenerate; edit the CUE schema instead.\n\
         # SPDX-License-Identifier: MIT\n{body}"
    ))
}

#[cfg(test)]
mod tests {
    use super::*;

    fn meta() -> Value {
        json!({
            "group": "apprafter.io",
            "version": "v1alpha1",
            "scope": "Namespaced",
            "names": { "plural": "applications", "kind": "Application" },
            "annotations": { "argocd.argoproj.io/sync-wave": "-5" },
            "subresources": { "status": {} },
            "printerColumns": [ { "name": "Age", "type": "date", "jsonPath": ".metadata.creationTimestamp" } ]
        })
    }

    #[test]
    fn builds_envelope_with_name_and_subresources() {
        let crd = build_crd(
            &meta(),
            json!({"type": "object"}),
            json!({"type": "object"}),
        )
        .unwrap();
        assert_eq!(crd["metadata"]["name"], json!("applications.apprafter.io"));
        assert_eq!(crd["spec"]["scope"], json!("Namespaced"));
        assert_eq!(
            crd["spec"]["versions"][0]["subresources"]["status"],
            json!({})
        );
        assert_eq!(crd["spec"]["versions"][0]["name"], json!("v1alpha1"));
    }

    #[test]
    fn render_replaces_labels_placeholder_with_helm_include() {
        let crd = build_crd(
            &meta(),
            json!({"type": "object"}),
            json!({"type": "object"}),
        )
        .unwrap();
        let text = render("schemas/v1alpha1", &crd).unwrap();
        assert!(text.contains("# SPDX-License-Identifier: MIT"));
        assert!(text.contains(LABELS_INCLUDE));
        assert!(!text.contains(LABELS_PLACEHOLDER));
        // the include sits under a `labels:` key
        assert!(text.contains("labels:\n    {{- include"));
    }
}
