// SPDX-License-Identifier: FSL-1.1-Apache-2.0
//! Render the command model into the committed reference artefacts.
//!
//! Layout (one page per top-level command keeps each file small
//! enough to read and diff):
//!   docs/reference/cli/index.md        overview table
//!   docs/reference/cli/<command>.md    one visible top-level command
//!   docs/reference/cli/SUMMARY.md      nav fragment for literate-nav
//!   docs/reference/cli/commands.json   machine-readable projection
//!
//! Every byte here is a pure function of the clap tree: `docsgen check`
//! byte-compares a fresh render against the committed one, so a
//! timestamp, an absolute path or a hash-map iteration order in the
//! output would turn unrelated commits into CI failures. The CLI
//! version is deliberately confined to `commands.json` (a consumer
//! wants it as data); putting it in the prose pages would churn every
//! page on every release bump.
//!
//! Hidden commands (`auth` and its subtree) are rendered nowhere —
//! not on a page, not in the index, not in the nav — but they stay in
//! `commands.json`, because the documentation snippet gate must still
//! resolve `apprafter auth …` as a real path.

use crate::model::{one_line, tree_from, CommandNode, Tree};
use clap::Command;
use std::path::{Path, PathBuf};

pub const BANNER: &str = "<!-- generated by docsgen; do not edit -->";
pub const DIR: &str = "docs/reference/cli";

/// One generated file. `path` is absolute (rooted at the caller's
/// `repo_root`) and is never written here — `render_all` is pure, and
/// `generate` / `check` decide what to do with the text.
#[derive(Debug, PartialEq, Eq)]
pub struct Artefact {
    pub path: PathBuf,
    pub text: String,
}

/// Render every artefact, sorted by path so the caller's iteration
/// order (and any progress output it prints) is stable too.
pub fn render_all(root_cmd: &Command, repo_root: &Path) -> Vec<Artefact> {
    let version = root_cmd.get_version().unwrap_or("unknown").to_string();
    let tree = tree_from(root_cmd, &version);
    let dir = repo_root.join(DIR);

    let mut out = vec![
        Artefact {
            path: dir.join("commands.json"),
            text: format!(
                "{}\n",
                serde_json::to_string_pretty(&tree).expect("serialise tree")
            ),
        },
        Artefact {
            path: dir.join("index.md"),
            text: page(render_index(&tree)),
        },
        Artefact {
            path: dir.join("SUMMARY.md"),
            text: page(render_summary(&tree)),
        },
    ];
    for top in top_level(&tree) {
        out.push(Artefact {
            path: dir.join(format!("{top}.md")),
            text: page(render_command_page(&tree, &top)),
        });
    }
    out.sort_by(|a, b| a.path.cmp(&b.path));
    out
}

/// Visible top-level command names. `tree.commands` is sorted by path,
/// so filtering preserves that order without a second sort.
fn top_level(tree: &Tree) -> Vec<String> {
    tree.commands
        .iter()
        .filter(|c| c.path.len() == 1 && !c.hidden)
        .map(|c| c.path[0].clone())
        .collect()
}

/// Normalise a page to exactly one trailing newline. Sections append
/// their own blank-line separator, so without this every page would
/// end in a stray blank line that `markdownlint` flags and a reviewer
/// has to look past in every regenerated diff.
fn page(mut text: String) -> String {
    while text.ends_with('\n') {
        text.pop();
    }
    text.push('\n');
    text
}

fn node_at<'a>(tree: &'a Tree, path: &[String]) -> &'a CommandNode {
    tree.commands
        .iter()
        .find(|c| c.path == path)
        .unwrap_or_else(|| panic!("no command {path:?}"))
}

fn frontmatter(title: &str, description: &str) -> String {
    format!(
        "---\ntitle: {}\ndescription: {}\naudience: reference\nstatus: stable\n---\n\n{BANNER}\n\n",
        yaml_scalar(title),
        yaml_scalar(description),
    )
}

/// Quote a frontmatter value.
///
/// Half the `about` strings contain a colon (`"AppRafter CLI:
/// bootstrap …"`), and a bare `key: value: value` is a YAML parse
/// error — the docs frontmatter validator would reject the page it is
/// meant to be validating. Double-quoted style needs only `\` and `"`
/// escaped.
fn yaml_scalar(s: &str) -> String {
    format!(
        "\"{}\"",
        one_line(s).replace('\\', "\\\\").replace('"', "\\\"")
    )
}

/// Abbreviations whose full stop does not end a sentence. Short list
/// on purpose: it only has to cover what a CLI doc comment plausibly
/// contains, and a miss costs a slightly short summary, never a wrong
/// page.
const ABBREVIATIONS: [&str; 6] = ["e.g.", "i.e.", "etc.", "vs.", "cf.", "approx."];

/// A summary is grown one sentence at a time until it reaches this
/// many bytes. A lead sentence is almost always the right summary, so
/// this is set low enough to catch only genuine stubs: `doctor` opens
/// with "Self-diagnostic." (16 bytes), which tells an overview-table
/// reader nothing, while the shortest useful lead sentence in the
/// current surface is 43.
const MIN_SUMMARY: usize = 32;

/// The lead sentence (or two) of an `about`, for the frontmatter
/// description and the index table.
///
/// Several `about`s run to 400 characters (`restore`), which makes an
/// unreadable overview row and a meta description search engines
/// truncate anyway. Nothing is lost either way: the command's own page
/// prints the full text below its H1.
fn summary(about: &str) -> String {
    let one = one_line(about);
    let mut from = 0;
    while let Some(rel) = one[from..].find(". ") {
        let end = from + rel + 1;
        // Sentence boundaries only, and only once there is enough of a
        // sentence to be worth reading.
        if end >= MIN_SUMMARY && !ABBREVIATIONS.iter().any(|a| one[..end].ends_with(a)) {
            return one[..end].to_string();
        }
        from = end;
    }
    one
}

/// Escape a table cell: collapse whitespace, neutralise the column
/// separator, and protect placeholders (see [`escape_prose`]).
fn cell(s: &str) -> String {
    // The pipe is escaped after the prose pass, and inside code spans
    // as well as outside them: Markdown splits a table row on `|`
    // before it ever looks for backticks, so `` `a|b` `` would still
    // spill into the next column.
    escape_prose(&one_line(s)).replace('|', "\\|")
}

/// Protect angle-bracket placeholders that sit outside a code span.
///
/// `backup enable`'s long help documents `--credential-file <dotenv>`
/// in prose. Python-Markdown passes a bare `<dotenv>` through as raw
/// HTML, so the browser swallows it as an unknown tag and the reader
/// sees `--credential-file  Parse the dotenv file…`. Inside a code
/// span the same text is already literal, and escaping it there would
/// print `&lt;` verbatim — hence the scan rather than a blanket
/// `replace`.
fn escape_prose(s: &str) -> String {
    let mut out = String::with_capacity(s.len());
    let mut rest = s;
    while let Some(open) = rest.find('`') {
        let (before, from_tick) = rest.split_at(open);
        out.push_str(&before.replace('<', "&lt;"));
        // An unbalanced backtick is not a code span: treat the
        // remainder as prose rather than silently trusting it.
        match from_tick[1..].find('`') {
            Some(close) => {
                let end = 1 + close + 1;
                out.push_str(&from_tick[..end]);
                rest = &from_tick[end..];
            }
            None => {
                out.push_str(&from_tick.replace('<', "&lt;"));
                return out;
            }
        }
    }
    out.push_str(&rest.replace('<', "&lt;"));
    out
}

/// A `long_about` keeps its blank-line paragraph breaks (four commands
/// have several paragraphs), so it is emitted as-is apart from the
/// placeholder escaping, which runs per paragraph.
fn prose(node: &CommandNode) -> String {
    let text = node.long_about.as_deref().unwrap_or(&node.about);
    text.split("\n\n")
        .map(escape_prose)
        .collect::<Vec<_>>()
        .join("\n\n")
}

fn code_list(items: &[String]) -> String {
    items
        .iter()
        .map(|i| format!("`{i}`"))
        .collect::<Vec<_>>()
        .join(", ")
}

fn render_index(tree: &Tree) -> String {
    let mut s = frontmatter(
        "CLI reference",
        "Every apprafter command, flag and default, generated from the clap definitions.",
    );
    s.push_str("# CLI reference\n\n");
    s.push_str(
        "Generated from `cli/platform-cli/src/cli.rs`. Every command, flag, default and\n\
         alias below is projected straight from the parser, so this page cannot describe\n\
         a flag the binary does not have. Run `apprafter <command> --help` for the same\n\
         information shell-formatted.\n\n",
    );
    s.push_str(
        "Aliases are accepted on the command line but are not listed in `--help`; they\n\
         are documented here because the guides use them.\n\n",
    );
    s.push_str("| Command | Aliases | Summary |\n| --- | --- | --- |\n");
    for name in top_level(tree) {
        let node = node_at(tree, std::slice::from_ref(&name));
        let aliases = if node.aliases.is_empty() {
            "—".to_string()
        } else {
            code_list(&node.aliases)
        };
        s.push_str(&format!(
            "| [`apprafter {name}`]({name}.md) | {aliases} | {} |\n",
            cell(&summary(&node.about))
        ));
    }
    s
}

fn render_command_page(tree: &Tree, top: &str) -> String {
    let path = [top.to_string()];
    let root = node_at(tree, &path);
    let mut s = frontmatter(&format!("apprafter {top}"), &summary(&root.about));
    s.push_str(&format!("# `apprafter {top}`\n\n"));
    s.push_str(&format!("{}\n\n", prose(root)));
    // The H1 already carries this command's own anchor, so its aliases
    // and tables follow it directly instead of under a repeated
    // heading; descendants start at `##`.
    s.push_str(&render_body(root));

    for node in tree
        .commands
        .iter()
        .filter(|c| c.path.len() > 1 && c.path[0] == top && !c.hidden)
    {
        s.push_str(&format!(
            "{} `apprafter {}`\n\n",
            "#".repeat(node.path.len()),
            node.path.join(" ")
        ));
        s.push_str(&format!("{}\n\n", prose(node)));
        s.push_str(&render_body(node));
    }
    s
}

/// Aliases, argument tables and examples — everything below a
/// command's heading and description.
fn render_body(node: &CommandNode) -> String {
    let mut s = String::new();

    if !node.aliases.is_empty() {
        s.push_str(&format!(
            "Aliases: {} — accepted on the command line, not listed in `--help`.\n\n",
            code_list(&node.aliases)
        ));
    }

    if !node.positionals.is_empty() {
        s.push_str("| Argument | Required | Description |\n| --- | --- | --- |\n");
        for p in &node.positionals {
            let name = if p.multiple {
                format!("`<{}>…`", p.value_name)
            } else {
                format!("`<{}>`", p.value_name)
            };
            let mut description = cell(&p.help);
            if !p.possible_values.is_empty() {
                // A `ValueEnum` positional carries its accepted set in
                // the model; leaving it to the doc comment would let a
                // renamed variant byte-compare clean.
                let values = p
                    .possible_values
                    .iter()
                    .map(|v| format!("`{v}`"))
                    .collect::<Vec<_>>()
                    .join(", ");
                description = match description.chars().last() {
                    None => format!("One of {values}."),
                    // `clap_derive` strips the full stop off a
                    // one-line doc comment, so joining naively yields
                    // "enable \| disable One of `enable`…".
                    Some(c) if c.is_alphanumeric() || c == '`' || c == ')' => {
                        format!("{description}. One of {values}.")
                    }
                    Some(_) => format!("{description} One of {values}."),
                };
            }
            s.push_str(&format!(
                "| {name} | {} | {} |\n",
                yes_no(p.required),
                or_dash(description)
            ));
        }
        s.push('\n');
    }

    if !node.args.is_empty() {
        s.push_str(
            "| Flag | Value | Default | Required | Description |\n| --- | --- | --- | --- | --- |\n",
        );
        for a in &node.args {
            let flag = match (&a.long, a.short) {
                (Some(l), Some(c)) => format!("`--{l}`, `-{c}`"),
                (Some(l), None) => format!("`--{l}`"),
                (None, Some(c)) => format!("`-{c}`"),
                (None, None) => format!("`{}`", a.id),
            };
            let value = if !a.possible_values.is_empty() {
                a.possible_values
                    .iter()
                    .map(|v| format!("`{v}`"))
                    .collect::<Vec<_>>()
                    .join(" \\| ")
            } else if a.takes_value {
                format!(
                    "`<{}>`",
                    a.value_name.clone().unwrap_or_else(|| "VALUE".into())
                )
            } else {
                "flag".to_string()
            };
            // An em dash, not "None": a switch has no default at all,
            // and `false` is a clap-synthesised artefact the model
            // already drops.
            let default = a
                .default
                .as_deref()
                .map(|d| format!("`{d}`"))
                .unwrap_or_else(|| "—".into());
            s.push_str(&format!(
                "| {flag} | {value} | {default} | {} | {} |\n",
                yes_no(a.required),
                or_dash(cell(&a.help))
            ));
        }
        s.push('\n');
    }

    if !node.examples.is_empty() {
        s.push_str("Examples:\n\n```sh\n");
        for e in &node.examples {
            s.push_str(&format!("{e}\n"));
        }
        s.push_str("```\n\n");
    }

    s
}

/// An em dash for an empty cell. Seven flags carry no doc comment in
/// `cli.rs` (`backup enable --cron`, `--keep-daily`, …); a blank cell
/// reads as a broken table, the dash as "nothing to say here".
fn or_dash(s: String) -> String {
    if s.is_empty() {
        "—".to_string()
    } else {
        s
    }
}

fn yes_no(b: bool) -> &'static str {
    if b {
        "yes"
    } else {
        "no"
    }
}

fn render_summary(tree: &Tree) -> String {
    let mut s = format!("{BANNER}\n\n* [Overview](index.md)\n");
    for name in top_level(tree) {
        s.push_str(&format!("* [apprafter {name}]({name}.md)\n"));
    }
    s
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn a_pipe_in_a_cell_cannot_spill_into_the_next_column() {
        assert_eq!(cell("a | b"), "a \\| b");
        assert_eq!(cell("`a|b`"), "`a\\|b`");
    }

    #[test]
    fn cells_collapse_whitespace() {
        assert_eq!(cell("a\n  b\tc"), "a b c");
    }

    #[test]
    fn bare_placeholders_are_escaped_but_code_spans_are_left_alone() {
        assert_eq!(
            escape_prose("pass <dotenv> to `s3:https://<host>/<bucket>`"),
            "pass &lt;dotenv> to `s3:https://<host>/<bucket>`"
        );
    }

    #[test]
    fn an_unbalanced_backtick_does_not_swallow_the_rest_of_the_line() {
        assert_eq!(escape_prose("a `b <c>"), "a `b &lt;c>");
    }

    #[test]
    fn frontmatter_survives_a_colon_in_the_description() {
        let fm = frontmatter("apprafter init", "AppRafter CLI: bootstrap a cluster");
        assert!(fm.contains("description: \"AppRafter CLI: bootstrap a cluster\""));
        assert!(fm.contains(BANNER));
    }

    #[test]
    fn a_summary_stops_at_the_first_real_sentence() {
        let about = "Seal secret material with the sealed-secrets public cert. \
                     The CLI cannot decrypt it. And more.";
        assert_eq!(
            summary(about),
            "Seal secret material with the sealed-secrets public cert."
        );
        // No sentence break at all — the whole thing is the summary.
        assert_eq!(
            summary("Apply the desired state"),
            "Apply the desired state"
        );
    }

    #[test]
    fn a_stub_lead_sentence_borrows_the_next_one() {
        // `doctor` opens "Self-diagnostic." — a row reading just that
        // is worse than no summary at all.
        assert_eq!(
            summary("Self-diagnostic. Walks the target's stored config and credentials. Exits 1."),
            "Self-diagnostic. Walks the target's stored config and credentials."
        );
    }

    #[test]
    fn an_abbreviation_does_not_end_the_summary() {
        assert_eq!(
            summary("Resulting type, e.g. Opaque, of the Secret. Rest."),
            "Resulting type, e.g. Opaque, of the Secret."
        );
    }

    #[test]
    fn an_enum_positional_lists_its_values_as_its_own_sentence() {
        let node = CommandNode {
            path: vec!["target".into(), "firewall".into()],
            aliases: vec![],
            about: String::new(),
            long_about: None,
            hidden: false,
            examples: vec![],
            args: vec![],
            positionals: vec![crate::model::PositionalSpec {
                id: "state".into(),
                value_name: "STATE".into(),
                required: true,
                multiple: false,
                possible_values: vec!["enable".into(), "disable".into()],
                help: "enable | disable".into(),
            }],
        };
        assert!(
            render_body(&node)
                .contains("| `<STATE>` | yes | enable \\| disable. One of `enable`, `disable`. |"),
            "{}",
            render_body(&node)
        );
    }

    #[test]
    fn an_undocumented_flag_gets_a_dash_not_a_blank_cell() {
        let node = CommandNode {
            path: vec!["backup".into(), "enable".into()],
            aliases: vec![],
            about: String::new(),
            long_about: None,
            hidden: false,
            examples: vec![],
            args: vec![crate::model::ArgSpec {
                id: "cron".into(),
                long: Some("cron".into()),
                short: None,
                takes_value: true,
                value_name: Some("CRON".into()),
                default: None,
                required: false,
                possible_values: vec![],
                help: String::new(),
            }],
            positionals: vec![],
        };
        assert!(
            render_body(&node).contains("| `--cron` | `<CRON>` | — | no | — |"),
            "{}",
            render_body(&node)
        );
    }

    #[test]
    fn a_page_ends_with_exactly_one_newline() {
        assert_eq!(page("a\n\n\n".to_string()), "a\n");
        assert_eq!(page("a".to_string()), "a\n");
    }

    #[test]
    fn frontmatter_escapes_a_quote() {
        assert!(frontmatter("t", "say \"hi\"").contains("description: \"say \\\"hi\\\"\""));
    }
}
