// SPDX-License-Identifier: FSL-1.1-Apache-2.0
//! Render the command model into the committed reference artefacts.
//!
//! Layout (one page per top-level command keeps each file small
//! enough to read and diff):
//!   docs/reference/cli/index.md        overview table
//!   docs/reference/cli/<command>.md    one visible top-level command
//!   docs/reference/cli/SUMMARY.md      nav fragment for literate-nav
//!   docs/reference/cli/commands.json   machine-readable projection
//!
//! Every byte here is a pure function of the clap tree: `docsgen check`
//! byte-compares a fresh render against the committed one, so a
//! timestamp, an absolute path or a hash-map iteration order in the
//! output would turn unrelated commits into CI failures. The CLI
//! version is deliberately confined to `commands.json` (a consumer
//! wants it as data); putting it in the prose pages would churn every
//! page on every release bump.
//!
//! Hidden commands (`auth` and its subtree) are rendered nowhere —
//! not on a page, not in the index, not in the nav — but they stay in
//! `commands.json`, because the documentation snippet gate must still
//! resolve `apprafter auth …` as a real path.

use crate::model::{one_line, tree_from, ArgSpec, CommandNode, PositionalSpec, Tree};
use clap::Command;
use std::path::{Path, PathBuf};

pub const BANNER: &str = "<!-- generated by docsgen; do not edit -->";
pub const DIR: &str = "docs/reference/cli";

/// One generated file. `path` is absolute (rooted at the caller's
/// `repo_root`) and is never written here — `render_all` is pure, and
/// `generate` / `check` decide what to do with the text.
#[derive(Debug, PartialEq, Eq)]
pub struct Artefact {
    pub path: PathBuf,
    pub text: String,
}

/// Render every artefact, sorted by path so the caller's iteration
/// order (and any progress output it prints) is stable too.
pub fn render_all(root_cmd: &Command, repo_root: &Path) -> Vec<Artefact> {
    let version = root_cmd.get_version().unwrap_or("unknown").to_string();
    let tree = tree_from(root_cmd, &version);
    let dir = repo_root.join(DIR);

    let mut out = vec![
        Artefact {
            path: dir.join("commands.json"),
            text: format!(
                "{}\n",
                serde_json::to_string_pretty(&tree).expect("serialise tree")
            ),
        },
        Artefact {
            path: dir.join("index.md"),
            text: page(render_index(&tree)),
        },
        Artefact {
            path: dir.join("SUMMARY.md"),
            text: page(render_summary(&tree)),
        },
    ];
    for top in top_level(&tree) {
        out.push(Artefact {
            path: dir.join(format!("{top}.md")),
            text: page(render_command_page(&tree, &top)),
        });
    }
    out.sort_by(|a, b| a.path.cmp(&b.path));
    out
}

/// Visible top-level command names. `tree.commands` is sorted by path,
/// so filtering preserves that order without a second sort.
fn top_level(tree: &Tree) -> Vec<String> {
    tree.commands
        .iter()
        .filter(|c| c.path.len() == 1 && !c.hidden)
        .map(|c| c.path[0].clone())
        .collect()
}

/// Normalise a page to exactly one trailing newline. Sections append
/// their own blank-line separator, so without this every page would
/// end in a stray blank line that `markdownlint` flags and a reviewer
/// has to look past in every regenerated diff.
fn page(mut text: String) -> String {
    while text.ends_with('\n') {
        text.pop();
    }
    text.push('\n');
    text
}

fn node_at<'a>(tree: &'a Tree, path: &[String]) -> &'a CommandNode {
    tree.commands
        .iter()
        .find(|c| c.path == path)
        .unwrap_or_else(|| panic!("no command {path:?}"))
}

fn frontmatter(title: &str, description: &str) -> String {
    format!(
        "---\ntitle: {}\ndescription: {}\naudience: reference\nstatus: stable\n---\n\n{BANNER}\n\n",
        yaml_scalar(title),
        yaml_scalar(description),
    )
}

/// Quote a frontmatter value.
///
/// Half the `about` strings contain a colon (`"AppRafter CLI:
/// bootstrap …"`), and a bare `key: value: value` is a YAML parse
/// error — the docs frontmatter validator would reject the page it is
/// meant to be validating. Double-quoted style needs only `\` and `"`
/// escaped.
fn yaml_scalar(s: &str) -> String {
    format!(
        "\"{}\"",
        one_line(s).replace('\\', "\\\\").replace('"', "\\\"")
    )
}

/// Abbreviations whose full stop does not end a sentence. Short list
/// on purpose: it only has to cover what a CLI doc comment plausibly
/// contains, and a miss costs a slightly short summary, never a wrong
/// page.
const ABBREVIATIONS: [&str; 6] = ["e.g.", "i.e.", "etc.", "vs.", "cf.", "approx."];

/// The lead sentence of an `about`, for the frontmatter description
/// and the index table.
///
/// Several `about`s run to 400 characters (`restore`), which makes an
/// unreadable overview row and a meta description search engines
/// truncate anyway. Nothing is lost either way: the command's own page
/// prints the full text below its H1.
///
/// A lead sentence that is too terse to be a summary is a defect in
/// the doc comment, not something to paper over here: a length
/// threshold would be a magic number tuned against today's 26
/// top-level `about`s, and would silently glue a second sentence onto
/// the many legitimately short ones (`target use`, `volume remove`)
/// the moment this is reused for subcommands.
fn summary(about: &str) -> String {
    let one = one_line(about);
    let mut from = 0;
    while let Some(rel) = one[from..].find(". ") {
        let end = from + rel + 1;
        if !ABBREVIATIONS.iter().any(|a| one[..end].ends_with(a)) {
            return one[..end].to_string();
        }
        from = end;
    }
    one
}

/// Escape a table cell: collapse whitespace, protect placeholders and
/// neutralise the column separator — the last two outside code spans
/// only.
///
/// Python-Markdown (what MkDocs runs) resolves backtick regions
/// *before* it splits a row on `|`, so a pipe inside a code span is
/// already safe and escaping it there would print a literal backslash:
/// a doc comment mentioning `` `app logs -f | grep ERROR` `` would
/// render as `-f \| grep`. Outside a code span the opposite holds — an
/// unescaped pipe silently truncates the row at that point. Both
/// directions were checked against `markdown_py -x tables`; GFM/cmark
/// behave differently here, so intuition from GitHub does not transfer.
fn cell(s: &str) -> String {
    outside_code_spans(&one_line(s), |text| {
        text.replace('<', "&lt;").replace('|', "\\|")
    })
}

/// Protect angle-bracket placeholders that sit outside a code span.
///
/// `backup enable`'s long help documents `--credential-file <dotenv>`
/// in prose. Python-Markdown passes a bare `<dotenv>` through as raw
/// HTML, so the browser swallows it as an unknown tag and the reader
/// sees `--credential-file  Parse the dotenv file…`. Inside a code
/// span the same text is already literal, and escaping it there would
/// print `&lt;` verbatim — hence the scan rather than a blanket
/// `replace`. Pipes are left alone: outside a table they are literal.
fn escape_prose(s: &str) -> String {
    outside_code_spans(s, |text| text.replace('<', "&lt;"))
}

/// Apply `escape` to everything except the code spans, which are
/// copied through verbatim.
///
/// Spans are delimited by a run of backticks closed by a run of the
/// same length, per CommonMark: a single-backtick scan would read
/// ` ``--foo=<bar>`` ` as two empty spans with unprotected prose
/// between them. An unterminated run is not a span at all, so the
/// remainder is treated as prose.
fn outside_code_spans(s: &str, escape: impl Fn(&str) -> String) -> String {
    let mut out = String::with_capacity(s.len());
    let mut rest = s;
    while let Some(open) = rest.find('`') {
        let (before, from_tick) = rest.split_at(open);
        out.push_str(&escape(before));

        let fence = from_tick.len() - from_tick.trim_start_matches('`').len();
        match closing_run(&from_tick[fence..], fence) {
            Some(offset) => {
                let end = fence + offset + fence;
                out.push_str(&from_tick[..end]);
                rest = &from_tick[end..];
            }
            None => {
                out.push_str(&escape(from_tick));
                return out;
            }
        }
    }
    out.push_str(&escape(rest));
    out
}

/// Byte offset of the first backtick run of exactly `len` backticks.
fn closing_run(body: &str, len: usize) -> Option<usize> {
    let bytes = body.as_bytes();
    let mut i = 0;
    while i < bytes.len() {
        if bytes[i] != b'`' {
            i += 1;
            continue;
        }
        let start = i;
        while i < bytes.len() && bytes[i] == b'`' {
            i += 1;
        }
        if i - start == len {
            return Some(start);
        }
    }
    None
}

/// A `long_about` keeps its blank-line paragraph breaks (four commands
/// have several paragraphs), so it is emitted as-is apart from the
/// placeholder escaping, which runs per paragraph.
fn prose(node: &CommandNode) -> String {
    let text = node.long_about.as_deref().unwrap_or(&node.about);
    text.split("\n\n")
        .map(escape_prose)
        .collect::<Vec<_>>()
        .join("\n\n")
}

fn code_list(items: &[String]) -> String {
    code_list_sep(items, ", ")
}

/// `code_list` with an explicit separator — the flag table's Value
/// column needs an escaped pipe (`` `enable` \| `disable` ``) because
/// that pipe sits outside the code spans this builds.
fn code_list_sep(items: &[String], sep: &str) -> String {
    items
        .iter()
        .map(|i| format!("`{i}`"))
        .collect::<Vec<_>>()
        .join(sep)
}

/// Append a sentence to a description, repairing the seam.
///
/// `clap_derive` strips the full stop off a one-line doc comment, so a
/// naive join reads "enable \| disable One of `enable`…".
fn join_sentence(description: &str, addition: &str) -> String {
    match description.chars().last() {
        None => addition.to_string(),
        Some(c) if c.is_alphanumeric() || c == '`' || c == ')' => {
            format!("{description}. {addition}")
        }
        Some(_) => format!("{description} {addition}"),
    }
}

fn render_index(tree: &Tree) -> String {
    let mut s = frontmatter(
        "CLI reference",
        "Every apprafter command, flag and default, generated from the clap definitions.",
    );
    s.push_str("# CLI reference\n\n");
    s.push_str(
        "Generated from `cli/platform-cli/src/cli.rs`. Every command, flag, default and\n\
         alias below is projected straight from the parser, so this page cannot describe\n\
         a flag the binary does not have. Run `apprafter <command> --help` for the same\n\
         information shell-formatted.\n\n",
    );
    s.push_str(
        "Aliases are accepted on the command line but are not listed in `--help`; they\n\
         are documented here because the guides use them.\n\n",
    );
    s.push_str(
        "In the flag tables, a Value of `flag` means the flag takes no value; an em dash\n\
         means it takes one whose name adds nothing beyond the flag itself.\n\n",
    );
    s.push_str(
        "The same tree is published as [`commands.json`](commands.json) — every command\n\
         path, flag, default and value enum as data, including the hidden ones, with the\n\
         CLI version it was generated from. Use it to check a command line against a\n\
         specific release rather than scraping these pages.\n\n",
    );
    s.push_str("| Command | Aliases | Summary |\n| --- | --- | --- |\n");
    for name in top_level(tree) {
        let node = node_at(tree, std::slice::from_ref(&name));
        let aliases = if node.aliases.is_empty() {
            "—".to_string()
        } else {
            code_list(&node.aliases)
        };
        s.push_str(&format!(
            "| [`apprafter {name}`]({name}.md) | {aliases} | {} |\n",
            cell(&summary(&node.about))
        ));
    }
    s
}

fn render_command_page(tree: &Tree, top: &str) -> String {
    let path = [top.to_string()];
    let root = node_at(tree, &path);
    let mut s = frontmatter(&format!("apprafter {top}"), &summary(&root.about));
    s.push_str(&format!("# `apprafter {top}`\n\n"));
    s.push_str(&format!("{}\n\n", prose(root)));
    // The H1 already carries this command's own anchor, so its aliases
    // and tables follow it directly instead of under a repeated
    // heading; descendants start at `##`.
    s.push_str(&render_body(root, &children_of(tree, root)));

    for node in tree
        .commands
        .iter()
        .filter(|c| c.path.len() > 1 && c.path[0] == top && !c.hidden)
    {
        s.push_str(&format!(
            "{} `apprafter {}`\n\n",
            "#".repeat(node.path.len()),
            node.path.join(" ")
        ));
        s.push_str(&format!("{}\n\n", prose(node)));
        s.push_str(&render_body(node, &children_of(tree, node)));
    }
    s
}

/// A node's direct visible subcommands, in `tree.commands` order
/// (sorted by path, so alphabetical).
fn children_of<'a>(tree: &'a Tree, node: &CommandNode) -> Vec<&'a CommandNode> {
    tree.commands
        .iter()
        .filter(|c| {
            !c.hidden && c.path.len() == node.path.len() + 1 && c.path.starts_with(&node.path)
        })
        .collect()
}

/// The in-page anchor of a command's heading.
///
/// Headings are rendered as `` ### `apprafter target cert import` ``,
/// and Python-Markdown's toc slugifier drops the backticks and joins
/// the words with hyphens. Getting this wrong is not silent: the
/// strict build validates anchors (`validation.links.anchors`), so a
/// mismatch fails `just docs-build`.
fn anchor(path: &[String]) -> String {
    format!("apprafter-{}", path.join("-"))
}

/// Usage, aliases, argument tables and examples — everything below a
/// command's heading and description. `children` are the node's direct
/// visible subcommands, used only for a group node that has nothing
/// else to show.
fn render_body(node: &CommandNode, children: &[&CommandNode]) -> String {
    let mut s = String::new();

    // The usage line leads, as it does in `--help`. It is the only
    // place positional ORDER survives: the argument table is sorted by
    // id, so `target rename <FROM> <TO>` and `<TO> <FROM>` render the
    // same table.
    s.push_str(&format!("```text\n{}\n```\n\n", node.usage));

    if !node.aliases.is_empty() {
        s.push_str(&format!(
            "Aliases: {} — accepted on the command line, not listed in `--help`.\n\n",
            code_list(&node.aliases)
        ));
    }

    // A pure group (`target cert`, `repo creds`) has no args of its
    // own, so the tables below render nothing and the heading is
    // followed by one sentence and silence — 30 such headings. List
    // what it routes to instead.
    if node.args.is_empty() && node.positionals.is_empty() && !children.is_empty() {
        s.push_str("Subcommands:\n\n");
        for child in children {
            s.push_str(&format!(
                "- [`apprafter {}`](#{}) — {}\n",
                child.path.join(" "),
                anchor(&child.path),
                cell(&summary(&child.about))
            ));
        }
        s.push('\n');
    }

    if !node.positionals.is_empty() {
        s.push_str("| Argument | Required | Description |\n| --- | --- | --- |\n");
        for p in &node.positionals {
            s.push_str(&positional_row(p));
        }
        s.push('\n');
    }

    if !node.args.is_empty() {
        s.push_str(
            "| Flag | Value | Default | Required | Description |\n| --- | --- | --- | --- | --- |\n",
        );
        for a in &node.args {
            s.push_str(&flag_row(a));
        }
        s.push('\n');
    }

    if !node.examples.is_empty() {
        s.push_str("Examples:\n\n```sh\n");
        for e in &node.examples {
            s.push_str(&format!("{e}\n"));
        }
        s.push_str("```\n\n");
    }

    s
}

fn positional_row(p: &PositionalSpec) -> String {
    // A trailing ellipsis is how `--help` spells a repeatable
    // positional, so the reference spells it the same way.
    let name = if p.multiple {
        format!("`<{}>…`", p.value_name)
    } else {
        format!("`<{}>`", p.value_name)
    };

    let mut description = cell(&p.help);
    if !p.possible_values.is_empty() {
        // A `ValueEnum` positional carries its accepted set in the
        // model; leaving it to the doc comment would let a renamed
        // variant byte-compare clean.
        description = join_sentence(
            &description,
            &format!("One of {}.", code_list(&p.possible_values)),
        );
    }

    format!(
        "| {name} | {} | {} |\n",
        yes_no(p.required),
        or_dash(description)
    )
}

fn flag_row(a: &ArgSpec) -> String {
    let flag = match (&a.long, a.short) {
        (Some(l), Some(c)) => format!("`--{l}`, `-{c}`"),
        (Some(l), None) => format!("`--{l}`"),
        (None, Some(c)) => format!("`-{c}`"),
        (None, None) => format!("`{}`", a.id),
    };

    let value = if !a.possible_values.is_empty() {
        code_list_sep(&a.possible_values, " \\| ")
    } else if a.takes_value {
        // A value name clap synthesised from the field name says
        // nothing the flag has not already said (`--keep-daily
        // <KEEP_DAILY>` — 99 of 150 rows), so it gets the same em dash
        // as any other empty cell. A hand-written `value_name` in
        // `cli.rs` (`<cron>`, `<count>`, `<url>`) does carry
        // information and is printed. Teaching the renderer to invent
        // one would put the CLI's vocabulary in the wrong file.
        match a.value_name.as_deref() {
            Some(name) if !is_synthesised(name, a) => format!("`<{name}>`"),
            _ => "—".to_string(),
        }
    } else {
        "flag".to_string()
    };

    // An em dash, not "None": a switch has no default at all, and
    // `false` is a clap-synthesised artefact the model already drops.
    // An empty-string default (`backup enable --credential`) is the
    // same case — `--help` prints nothing for it, and a `` `` `` cell
    // would render as two stray backticks rather than a code span.
    let default = a
        .default
        .as_deref()
        .filter(|d| !d.is_empty())
        .map(|d| format!("`{d}`"))
        .unwrap_or_else(|| "—".into());

    let mut description = cell(&a.help);
    if let Some(env) = &a.env {
        // Appended rather than given a sixth column: only 8 of ~200
        // flags read an environment variable, so a column would be an
        // em dash on every other row and widen every table on the site.
        description = join_sentence(&description, &format!("Env: `{env}`."));
    }

    format!(
        "| {flag} | {value} | {default} | {} | {} |\n",
        yes_no(a.required),
        or_dash(description)
    )
}

/// Whether a value name is clap's own derivation from the argument
/// rather than something an author chose.
///
/// `clap_derive` names the value after the field — `keep_daily` →
/// `KEEP_DAILY` — which is also the long flag uppercased with dashes
/// turned to underscores. Both spellings are checked because an
/// explicit `long = "…"` can differ from the field name.
fn is_synthesised(value_name: &str, a: &ArgSpec) -> bool {
    let from_id = a.id.to_uppercase();
    let from_long = a.long.as_ref().map(|l| l.to_uppercase().replace('-', "_"));
    value_name == from_id || from_long.as_deref() == Some(value_name)
}

/// An em dash for an empty cell. Seven flags carry no doc comment in
/// `cli.rs` (`backup enable --cron`, `--keep-daily`, …); a blank cell
/// reads as a broken table, the dash as "nothing to say here".
fn or_dash(s: String) -> String {
    if s.is_empty() {
        "—".to_string()
    } else {
        s
    }
}

fn yes_no(b: bool) -> &'static str {
    if b {
        "yes"
    } else {
        "no"
    }
}

fn render_summary(tree: &Tree) -> String {
    let mut s = format!("{BANNER}\n\n* [Overview](index.md)\n");
    for name in top_level(tree) {
        s.push_str(&format!("* [apprafter {name}]({name}.md)\n"));
    }
    s
}

#[cfg(test)]
mod tests {
    use super::*;

    fn arg(long: &str) -> ArgSpec {
        ArgSpec {
            id: long.replace('-', "_"),
            long: Some(long.to_string()),
            short: None,
            takes_value: true,
            value_name: Some(long.to_uppercase().replace('-', "_")),
            default: None,
            env: None,
            required: false,
            possible_values: vec![],
            help: String::new(),
        }
    }

    fn positional(value_name: &str) -> PositionalSpec {
        PositionalSpec {
            id: value_name.to_lowercase(),
            value_name: value_name.to_string(),
            required: true,
            multiple: false,
            possible_values: vec![],
            help: String::new(),
        }
    }

    fn node(args: Vec<ArgSpec>, positionals: Vec<PositionalSpec>) -> CommandNode {
        CommandNode {
            path: vec!["backup".into(), "enable".into()],
            aliases: vec![],
            about: String::new(),
            long_about: None,
            usage: "Usage: apprafter backup enable".into(),
            hidden: false,
            examples: vec![],
            args,
            positionals,
        }
    }

    #[test]
    fn a_prose_pipe_is_escaped_but_one_inside_a_code_span_is_not() {
        assert_eq!(cell("a | b"), "a \\| b");
        // Python-Markdown resolves backtick regions before splitting
        // the row, so this pipe is already safe; escaping it would
        // print the backslash. Verified against `markdown_py -x
        // tables` — GFM differs, which is the trap here.
        assert_eq!(cell("`a|b`"), "`a|b`");
        assert_eq!(
            cell("run `logs -f | grep E` now | ok"),
            "run `logs -f | grep E` now \\| ok"
        );
    }

    #[test]
    fn cells_collapse_whitespace() {
        assert_eq!(cell("a\n  b\tc"), "a b c");
    }

    #[test]
    fn bare_placeholders_are_escaped_but_code_spans_are_left_alone() {
        assert_eq!(
            escape_prose("pass <dotenv> to `s3:https://<host>/<bucket>`"),
            "pass &lt;dotenv> to `s3:https://<host>/<bucket>`"
        );
    }

    #[test]
    fn a_multi_backtick_span_is_one_span_not_two_empty_ones() {
        // A single-backtick scan reads ``x`` as two empty spans and
        // escapes the prose between them.
        assert_eq!(
            escape_prose("try ``--foo=<bar>`` then <baz>"),
            "try ``--foo=<bar>`` then &lt;baz>"
        );
    }

    #[test]
    fn an_unbalanced_backtick_does_not_swallow_the_rest_of_the_line() {
        assert_eq!(escape_prose("a `b <c>"), "a `b &lt;c>");
        assert_eq!(escape_prose("a ``b <c>`"), "a ``b &lt;c>`");
    }

    #[test]
    fn frontmatter_survives_a_colon_in_the_description() {
        let fm = frontmatter("apprafter init", "AppRafter CLI: bootstrap a cluster");
        assert!(fm.contains("description: \"AppRafter CLI: bootstrap a cluster\""));
        assert!(fm.contains(BANNER));
    }

    #[test]
    fn frontmatter_escapes_a_quote() {
        assert!(frontmatter("t", "say \"hi\"").contains("description: \"say \\\"hi\\\"\""));
    }

    #[test]
    fn a_summary_is_the_lead_sentence() {
        let about = "Seal secret material with the sealed-secrets public cert. \
                     The CLI cannot decrypt it. And more.";
        assert_eq!(
            summary(about),
            "Seal secret material with the sealed-secrets public cert."
        );
        // No sentence break at all — the whole thing is the summary.
        assert_eq!(
            summary("Apply the desired state"),
            "Apply the desired state"
        );
        // A short lead sentence is kept as-is: padding it from the
        // next sentence would run away on `target use`-style abouts.
        assert_eq!(summary("Remove a target. It is gone."), "Remove a target.");
    }

    #[test]
    fn an_abbreviation_does_not_end_the_summary() {
        assert_eq!(
            summary("Resulting type, e.g. Opaque, of the Secret. Rest."),
            "Resulting type, e.g. Opaque, of the Secret."
        );
    }

    #[test]
    fn an_enum_positional_lists_its_values_as_its_own_sentence() {
        let mut state = positional("STATE");
        state.possible_values = vec!["enable".into(), "disable".into()];
        state.help = "enable | disable".into();
        let body = render_body(&node(vec![], vec![state]), &[]);
        assert!(
            body.contains("| `<STATE>` | yes | enable \\| disable. One of `enable`, `disable`. |"),
            "{body}"
        );
    }

    #[test]
    fn an_undocumented_flag_gets_a_dash_not_a_blank_cell() {
        let body = render_body(&node(vec![arg("cron")], vec![]), &[]);
        assert!(body.contains("| `--cron` | — | — | no | — |"), "{body}");
    }

    #[test]
    fn a_clap_derived_value_name_is_dropped_but_a_chosen_one_is_kept() {
        // `--keep-daily <KEEP_DAILY>` repeats the flag; `<count>` does
        // not. Both spellings of the derivation are recognised, since
        // an explicit `long =` can differ from the field name.
        let mut synthesised = arg("keep-daily");
        synthesised.id = "keep_daily".into();
        synthesised.value_name = Some("KEEP_DAILY".into());
        let body = render_body(&node(vec![synthesised], vec![]), &[]);
        assert!(body.contains("| `--keep-daily` | — |"), "{body}");

        let mut chosen = arg("keep-daily");
        chosen.id = "keep_daily".into();
        chosen.value_name = Some("count".into());
        let body = render_body(&node(vec![chosen], vec![]), &[]);
        assert!(body.contains("| `--keep-daily` | `<count>` |"), "{body}");
    }

    #[test]
    fn a_switch_is_distinguishable_from_a_flag_with_an_unnamed_value() {
        // Both cells are terse; they must not be the SAME terse.
        let mut switch = arg("yes");
        switch.takes_value = false;
        switch.value_name = None;
        assert!(
            render_body(&node(vec![switch], vec![]), &[]).contains("| `--yes` | flag |"),
            "a switch must say so"
        );
    }

    #[test]
    fn an_empty_string_default_is_not_a_default() {
        // `backup enable --credential` is `default_value = ""`.
        // Rendering it as a code span emits two stray backticks, which
        // Python-Markdown prints literally; `--help` shows nothing
        // there either.
        let mut credential = arg("credential");
        credential.default = Some(String::new());
        let body = render_body(&node(vec![credential], vec![]), &[]);
        assert!(
            body.contains("| `--credential` | — | — | no | — |"),
            "{body}"
        );
        // Scoped to the row: the body now opens with a ```text usage
        // fence, whose backtick run is not a stray empty code span.
        let row = body
            .lines()
            .find(|l| l.contains("`--credential`"))
            .expect("flag row");
        assert!(!row.contains("``"), "stray backticks: {row}");
    }

    #[test]
    fn an_env_backed_flag_names_its_variable() {
        let mut token = arg("token");
        token.help = "Hetzner Cloud API token".into();
        token.env = Some("HCLOUD_TOKEN".into());
        let body = render_body(&node(vec![token], vec![]), &[]);
        assert!(
            body.contains("Hetzner Cloud API token. Env: `HCLOUD_TOKEN`."),
            "{body}"
        );
    }

    #[test]
    fn examples_render_as_a_shell_fence() {
        // Dead until a later task populates `examples`; pinning the
        // format now stops that task from inventing another one.
        let mut n = node(vec![], vec![]);
        n.examples = vec!["apprafter backup enable --bucket b".into()];
        assert!(
            render_body(&n, &[])
                .ends_with("Examples:\n\n```sh\napprafter backup enable --bucket b\n```\n\n"),
            "{}",
            render_body(&n, &[])
        );
    }

    #[test]
    fn the_usage_line_leads_the_body() {
        let body = render_body(&node(vec![], vec![]), &[]);
        assert!(
            body.starts_with("```text\nUsage: apprafter backup enable\n```\n\n"),
            "{body}"
        );
    }

    #[test]
    fn a_group_with_no_args_lists_its_children_instead_of_nothing() {
        let mut child = node(vec![], vec![]);
        child.path = vec!["target".into(), "cert".into(), "import".into()];
        child.about = "Import a TLS certificate. And more prose.".into();
        let group = node(vec![], vec![]);
        let body = render_body(&group, &[&child]);
        assert!(
            body.contains(
                "- [`apprafter target cert import`](#apprafter-target-cert-import) — \
                 Import a TLS certificate."
            ),
            "{body}"
        );
    }

    #[test]
    fn a_command_with_its_own_args_does_not_list_children() {
        // `app` has both flags and subcommands; the flag table is the
        // useful thing there, and the subcommands follow as sections.
        let mut child = node(vec![], vec![]);
        child.path = vec!["app".into(), "add".into()];
        let body = render_body(&node(vec![arg("cron")], vec![]), &[&child]);
        assert!(!body.contains("Subcommands:"), "{body}");
    }

    #[test]
    fn a_page_ends_with_exactly_one_newline() {
        assert_eq!(page("a\n\n\n".to_string()), "a\n");
        assert_eq!(page("a".to_string()), "a\n");
    }
}
