// SPDX-FileCopyrightText: 2026 AppRafter contributors
// SPDX-License-Identifier: FSL-1.1-Apache-2.0
//
// Companion declaration for importMap.js (regenerated by
// `payload generate:importmap`). The .js itself is empty until
// custom admin components are added, but TypeScript needs a type
// to satisfy strict moduleResolution.

import type { ImportMap } from 'payload';

export declare const importMap: ImportMap;
