// SPDX-License-Identifier: FSL-1.1-Apache-2.0
//! `apprafter app scaffold` — generate a starter
//! `apprafter/Application.cue` based on the cwd's runtime
//! markers. Track B.1.79b Part 3.
//!
//! Two templates live in `cli/platform-cli/templates/
//! application/` and embed in the binary via `include_str!`:
//!
//!   * `default.cue.hbs` — used for every runtime that the
//!     detector could pin (Bun, Node-{pnpm,yarn,npm},
//!     Python-{poetry,uv,pipenv,pip}, Rust, Go, Docker).
//!     Runtime-specific bits (primary port, display name,
//!     slug) come from a small registry.
//!   * `blank.cue.hbs` — used when the detector returned
//!     `Blank/Fallback`. Every field carries a TODO; no
//!     runtime-hint comments.
//!
//! Template engine is a straight `{{name}}` substitution
//! pass — no conditionals, no loops, no escaping. The vars
//! set is fixed AND known by template-content review, so the
//! "no `{{` remains after substitution" sanity check at the
//! end of `render_template` reliably catches typo-in-template
//! bugs without false positives.

use std::collections::BTreeMap;
use std::io::{self, IsTerminal};
use std::path::{Path, PathBuf};

use cli_core::{CliError, Result};

use crate::commands::runtime_detect::{detect_runtimes, Runtime};

const DEFAULT_TEMPLATE: &str = include_str!("../../templates/application/default.cue.hbs");
const BLANK_TEMPLATE: &str = include_str!("../../templates/application/blank.cue.hbs");

/// AppRafter v1alpha1 schema files embedded at compile time
/// (cargo rebuild fires automatically when these source files
/// change). Walk-fix #5 post-Part-3b: scaffold vendors these
/// into the operator's repo at `apprafter/cue.mod/pkg/
/// apprafter.io/schemas/v1alpha1/`, so the operator's
/// Application.cue can `import v1alpha1 "apprafter.io/
/// schemas/v1alpha1"` AND `cue vet` works locally without any
/// `cue mod tidy` step OR external network call from CMP at
/// sync time. Application.cue stays clean — the schema
/// definitions live alongside it but in their own package
/// directory.
const SCHEMA_TYPES_CUE: &str = include_str!("../../../../schemas/v1alpha1/types.cue");
const SCHEMA_APPLICATION_CUE: &str = include_str!("../../../../schemas/v1alpha1/application.cue");

/// Vendored schema file list — paired filename + content,
/// written to `apprafter/cue.mod/pkg/apprafter.io/schemas/
/// v1alpha1/` during scaffold. Tests cover the byte-identity
/// invariant (vendored copy === embedded source).
const VENDORED_SCHEMAS: &[(&str, &str)] = &[
    ("types.cue", SCHEMA_TYPES_CUE),
    ("application.cue", SCHEMA_APPLICATION_CUE),
];

/// Local CUE module manifest. Module path
/// `apprafter.io/local-app` is a neutral string — it just has
/// to differ from the imported `apprafter.io/schemas/v1alpha1`
/// so CUE's resolver treats the import as a dependency lookup
/// (find in `cue.mod/pkg/`) rather than a self-reference. The
/// `language.version` pin mirrors the apprafter monorepo's
/// own cue.mod/module.cue.
const CUE_MOD_MODULE_CUE: &str = "// Generated by `apprafter app scaffold` — local CUE module
// manifest declaring the vendored AppRafter schemas under
// `cue.mod/pkg/apprafter.io/schemas/v1alpha1/`. CUE walks up
// from Application.cue, finds this file, and resolves the
// `apprafter.io/schemas/v1alpha1` import to the vendored
// package. Re-scaffold with `--force` to refresh the vendored
// schemas when AppRafter publishes a new CRD revision.

module: \"apprafter.io/local-app\"

language: {
	version: \"v0.10.0\"
}
";

/// Default destination namespace for scaffolded manifests.
/// Mirrors `apprafter app add`'s `--namespace` default (walk-
/// fix #12 post-B.1.79a) so the scaffolded manifest and the
/// Argo CD parent CR agree out of the box.
pub const DEFAULT_NAMESPACE: &str = "apprafter";

/// Per-runtime defaults baked into the template. The `slug`
/// must match the `Runtime::slug()` value (load-bearing for
/// the `--runtime <slug>` flag round-trip).
pub struct RuntimeDefaults {
    pub primary_port: u16,
    pub display: &'static str,
    pub slug: &'static str,
}

/// Per-runtime defaults. Plan.md §1.79b "Runtime detection"
/// table: bun/node = 3000, python = 8000, rust/go = 8080,
/// docker = 8080, blank = 8080 (placeholder).
pub fn defaults_for(runtime: Runtime) -> RuntimeDefaults {
    match runtime {
        Runtime::Bun => RuntimeDefaults {
            primary_port: 3000,
            display: "Bun",
            slug: "bun",
        },
        Runtime::NodePnpm => RuntimeDefaults {
            primary_port: 3000,
            display: "Node.js (pnpm)",
            slug: "node-pnpm",
        },
        Runtime::NodeYarn => RuntimeDefaults {
            primary_port: 3000,
            display: "Node.js (yarn)",
            slug: "node-yarn",
        },
        Runtime::NodeNpm => RuntimeDefaults {
            primary_port: 3000,
            display: "Node.js (npm)",
            slug: "node-npm",
        },
        Runtime::PythonPoetry => RuntimeDefaults {
            primary_port: 8000,
            display: "Python (poetry)",
            slug: "python-poetry",
        },
        Runtime::PythonUv => RuntimeDefaults {
            primary_port: 8000,
            display: "Python (uv)",
            slug: "python-uv",
        },
        Runtime::PythonPipenv => RuntimeDefaults {
            primary_port: 8000,
            display: "Python (pipenv)",
            slug: "python-pipenv",
        },
        Runtime::PythonPip => RuntimeDefaults {
            primary_port: 8000,
            display: "Python (pip)",
            slug: "python-pip",
        },
        Runtime::Rust => RuntimeDefaults {
            primary_port: 8080,
            display: "Rust",
            slug: "rust",
        },
        Runtime::Go => RuntimeDefaults {
            primary_port: 8080,
            display: "Go",
            slug: "go",
        },
        Runtime::Docker => RuntimeDefaults {
            primary_port: 8080,
            display: "Docker",
            slug: "docker",
        },
        Runtime::Blank => RuntimeDefaults {
            primary_port: 8080,
            display: "blank",
            slug: "blank",
        },
    }
}

/// Pure template engine — substitutes `{{key}}` → value for
/// every entry in `vars`. Refuses to return when any `{{...}}`
/// remains after substitution (caught typo in a template's
/// placeholder name OR forgotten variable). String-based
/// `replace` is sufficient for our tiny templates — no
/// conditionals, no nesting, no escaping.
pub fn render_template(template: &str, vars: &BTreeMap<&str, String>) -> Result<String> {
    let mut out = template.to_string();
    for (key, value) in vars {
        let placeholder = format!("{{{{{key}}}}}");
        out = out.replace(&placeholder, value);
    }
    if let Some(idx) = out.find("{{") {
        let end = (idx + 30).min(out.len());
        return Err(CliError::Other(format!(
            "template renderer left an unsubstituted placeholder near `{}` \
             — likely a typo in a template `{{{{key}}}}` or a variable \
             missing from the scaffold callsite.",
            &out[idx..end]
        )));
    }
    Ok(out)
}

/// Pure helper — `my-app-name` → `myAppName`. Used to derive
/// the CUE binding identifier from the app's DNS-1123 name.
/// CUE identifiers must start with a letter; we lower-case-
/// first character to keep idiomatic CUE style (`appName:`
/// not `AppName:`).
pub fn kebab_to_camel(name: &str) -> String {
    let mut out = String::with_capacity(name.len());
    let mut capitalise_next = false;
    for (idx, c) in name.chars().enumerate() {
        if c == '-' || c == '_' {
            capitalise_next = true;
        } else if capitalise_next {
            out.extend(c.to_uppercase());
            capitalise_next = false;
        } else if idx == 0 {
            out.extend(c.to_lowercase());
        } else {
            out.push(c);
        }
    }
    if out.is_empty() {
        "app".to_string()
    } else {
        out
    }
}

/// Outcome of image-reference derivation. The caller picks the
/// scaffold's image comment from the variant: a `Derived` ref
/// gets a "verify it matches your CI" note; a `Placeholder`
/// gets the "replace REPLACE-ME" TODO. Walk-fix post-Part-3b:
/// derive the registry image ref from the repo's git origin
/// where the host is recognised, otherwise fall back to the
/// obvious placeholder.
#[derive(Debug, Clone, PartialEq, Eq)]
pub(crate) enum ImageRef {
    /// Confidently derived from the git origin — full ref incl.
    /// `:latest` tag.
    Derived(String),
    /// Could not derive — placeholder the operator must fill.
    Placeholder(String),
}

impl ImageRef {
    fn value(&self) -> &str {
        match self {
            ImageRef::Derived(s) | ImageRef::Placeholder(s) => s,
        }
    }
    fn is_derived(&self) -> bool {
        matches!(self, ImageRef::Derived(_))
    }
}

/// Pure — resolve the image reference for the scaffold from an
/// optional git origin URL. `None` origin (not a git repo / no
/// remote) → placeholder. `app_name` is used only for the
/// placeholder fallback path.
pub(crate) fn derive_image_ref(git_origin: Option<&str>, app_name: &str) -> ImageRef {
    let placeholder = || ImageRef::Placeholder(format!("ghcr.io/REPLACE-ME/{app_name}:latest"));
    match git_origin.and_then(derive_image_from_url) {
        Some(s) => ImageRef::Derived(s),
        None => placeholder(),
    }
}

/// Pure workhorse — map an HTTPS git URL to a registry image
/// reference. Returns `None` for any URL we cannot confidently
/// map (caller keeps the REPLACE-ME placeholder).
///
/// Rules (verified against OCI distribution-spec + GitHub /
/// GitLab docs, walk research 2026-05-29):
///
///   * `github.com` (exact) → `ghcr.io/<owner>/<repo>:latest`.
///     GitHub repos are flat owner/repo; extra URL segments
///     (`/tree/main`) are ignored.
///   * `gitlab.com` (exact) → `registry.gitlab.com/<full-
///     path>:latest`. The registry path mirrors the FULL
///     project path including every subgroup level.
///   * host containing `gitlab` (self-managed GitLab) →
///     `registry.<host>/<full-path>:latest`. The registry
///     host is admin-configured (subdomain vs `:5050`); we
///     guess the GitLab-documented subdomain default and flag
///     it in the scaffold comment.
///   * host containing `gitea` / `forgejo` → `<host>/<owner>/
///     <repo>:latest`. Gitea/Forgejo serve the OCI registry
///     on the identical host; repos are flat owner/repo.
///   * anything else (Bitbucket, GitHub Enterprise, unknown)
///     → `None`.
///
/// Host match for the SaaS specials is EXACT (so
/// `github.com.attacker.net` does NOT map to ghcr.io). The
/// entire image path is ASCII-lowercased (OCI grammar mandates
/// lowercase repository names); the registry host literal and
/// the `:latest` tag are left as-is.
pub(crate) fn derive_image_from_url(repo_url: &str) -> Option<String> {
    let rest = repo_url.trim().strip_prefix("https://")?;
    let (authority, path) = rest.split_once('/')?;

    // Authority → bare host: drop userinfo (after last '@'),
    // then port (before first ':').
    let host = authority.rsplit('@').next().unwrap_or(authority);
    let host = host.split(':').next().unwrap_or(host);
    let host_lc = host.to_ascii_lowercase();
    if host_lc.is_empty() {
        return None;
    }

    // Path → clean segments: cut query/fragment, split on '/',
    // strip trailing `.git` on the last segment, drop empties.
    let path_clean = path.split(['?', '#']).next().unwrap_or(path);
    let mut segs: Vec<&str> = path_clean.split('/').filter(|s| !s.is_empty()).collect();
    if let Some(last) = segs.last_mut() {
        *last = last.strip_suffix(".git").unwrap_or(last);
    }
    segs.retain(|s| !s.is_empty());
    if segs.len() < 2 {
        return None;
    }

    let image_path = if host_lc == "github.com" {
        // Flat owner/repo; ignore any trailing /tree/main etc.
        format!("{}/{}", segs[0], segs[1])
    } else if host_lc == "gitlab.com" || host_lc.contains("gitlab") {
        // Full project path incl. subgroups.
        segs.join("/")
    } else if host_lc.contains("gitea") || host_lc.contains("forgejo") {
        // Same-host registry, flat owner/repo.
        format!("{}/{}", segs[0], segs[1])
    } else {
        return None;
    };

    let image_path = image_path.to_ascii_lowercase();
    // Guard: every segment must be an OCI-legal lowercase atom.
    // GitHub/GitLab names already qualify after lowercasing;
    // this rejects pathological inputs rather than emitting an
    // invalid ref.
    if !image_path.split('/').all(is_oci_safe_segment) {
        return None;
    }

    let registry = if host_lc == "github.com" {
        "ghcr.io".to_string()
    } else if host_lc == "gitlab.com" {
        "registry.gitlab.com".to_string()
    } else if host_lc.contains("gitlab") {
        // Self-managed GitLab — GitLab-documented subdomain
        // default. Operator edits if their registry is on
        // `<host>:5050` instead (scaffold comment flags this).
        format!("registry.{host_lc}")
    } else {
        // Gitea / Forgejo — registry on the same host.
        host_lc.clone()
    };

    Some(format!("{registry}/{image_path}:latest"))
}

/// True iff `s` is a valid lowercase OCI repository-name path
/// component: non-empty, only `[a-z0-9._-]`, not starting or
/// ending with a separator.
fn is_oci_safe_segment(s: &str) -> bool {
    if s.is_empty() {
        return false;
    }
    if !s
        .chars()
        .all(|c| c.is_ascii_lowercase() || c.is_ascii_digit() || matches!(c, '.' | '_' | '-'))
    {
        return false;
    }
    let first = s.chars().next().unwrap();
    let last = s.chars().next_back().unwrap();
    !matches!(first, '.' | '_' | '-') && !matches!(last, '.' | '_' | '-')
}

/// Build the multi-line image comment for the scaffold. The
/// `Derived` variant warns the operator to verify (host + name
/// may differ from what their CI publishes); the `Placeholder`
/// variant is the "fill in REPLACE-ME" TODO. Lines are joined
/// with `\n\t\t` so they align under `spec: base:` (two tabs);
/// the template supplies the leading `\t\t` for the first line.
fn image_comment(derived: bool) -> String {
    let lines: &[&str] = if derived {
        &[
            "// Derived from your git origin — VERIFY before relying on it.",
            "// The registry host AND image name may differ from what your CI",
            "// actually publishes (monorepo subpath, -web / -api suffix, a",
            "// self-managed registry on a different host or :5050 port). The",
            "// CMP plugin doesn't pull the image — kubelet does; the tag must",
            "// exist in the registry by sync time, or pods ImagePullBackOff.",
        ]
    } else {
        &[
            "// TODO: replace `REPLACE-ME` with your registry owner / org and",
            "// pin a concrete tag. The CMP plugin doesn't pull the image —",
            "// that's kubelet's job; the tag must already exist in the",
            "// registry by the time Argo CD syncs, or pods land in",
            "// `ImagePullBackOff`.",
        ]
    };
    lines.join("\n\t\t")
}

/// Pure helper — render a complete Application.cue body for
/// the given `runtime`/`app_name`/`namespace`/`git_origin`.
/// `git_origin` is the detected `remote.origin.url` (or `None`
/// when undetectable) used to derive the image reference; the
/// detection itself lives in the IO-bearing `scaffold` caller
/// so this fn stays pure and string-testable.
pub fn render_application(
    runtime: Runtime,
    app_name: &str,
    namespace: &str,
    git_origin: Option<&str>,
) -> Result<String> {
    let defaults = defaults_for(runtime);
    let camel = kebab_to_camel(app_name);
    let image = derive_image_ref(git_origin, app_name);
    let port = defaults.primary_port.to_string();

    let mut vars: BTreeMap<&str, String> = BTreeMap::new();
    vars.insert("app_name", app_name.to_string());
    vars.insert("app_name_camel", camel);
    vars.insert("namespace", namespace.to_string());
    vars.insert("primary_port", port);
    vars.insert("runtime_display", defaults.display.to_string());
    vars.insert("runtime_slug", defaults.slug.to_string());
    vars.insert("image_placeholder", image.value().to_string());
    vars.insert("image_comment", image_comment(image.is_derived()));

    let template = if runtime == Runtime::Blank {
        BLANK_TEMPLATE
    } else {
        DEFAULT_TEMPLATE
    };
    render_template(template, &vars)
}

/// Probe `git -C <path> remote get-url <remote>` non-fatally —
/// returns the normalised HTTPS origin URL, or `None` outside a
/// git repo / with git missing / when the remote isn't
/// configured. Path-aware sibling of `app_wizard::
/// detect_git_origin` so scaffold can resolve the origin of an
/// arbitrary `--path`, not just cwd.
fn detect_git_origin_in(path: &Path, remote: &str) -> Option<String> {
    let out = std::process::Command::new("git")
        .arg("-C")
        .arg(path)
        .args(["remote", "get-url", remote])
        .output()
        .ok()?;
    if !out.status.success() {
        return None;
    }
    let raw = String::from_utf8_lossy(&out.stdout).trim().to_string();
    if raw.is_empty() {
        return None;
    }
    Some(crate::commands::app::normalise_git_url(&raw))
}

/// Options surface for `apprafter app scaffold`. Mirrors the
/// clap arg shape in `cli::AppCommand::Scaffold`.
#[derive(Debug, Clone)]
pub struct ScaffoldOpts {
    /// Force-pick a runtime instead of detecting from cwd
    /// markers. `Runtime::slug` round-trip — `--runtime bun`
    /// resolves to `Runtime::Bun`.
    pub runtime: Option<Runtime>,

    /// Application name. Default = cwd basename (validated
    /// DNS-1123).
    pub name: Option<String>,

    /// Destination namespace for `metadata.namespace`.
    /// Default = `DEFAULT_NAMESPACE`.
    pub namespace: Option<String>,

    /// Working directory the scaffold writes into. Resolves
    /// the `apprafter/Application.cue` path under it.
    pub path: PathBuf,

    /// Overwrite an existing `apprafter/Application.cue`
    /// (without — refuse and exit error).
    pub force: bool,
}

/// Resolve runtime from explicit override OR detection.
/// Three-way fork:
///
///   1. `--runtime <slug>` passed → use it verbatim.
///   2. Detection finds exactly one High match → use it.
///   3. Otherwise (zero Highs, multiple Highs, only Medium /
///      Low / Fallback): drop into the interactive picker
///      via `scaffold_wizard::pick_runtime_interactive`
///      when both stdio ends are TTYs. Non-TTY surfaces the
///      original error with a pointer to `--runtime <slug>`.
///
/// Walk-fix Part 3b — pre-Part-3b every inconclusive case
/// errored. Standalone `app scaffold` now feels natural on
/// a TTY (no need to memorise slugs) while staying
/// scriptable in CI.
fn resolve_runtime(opts: &ScaffoldOpts) -> Result<Runtime> {
    if let Some(r) = opts.runtime {
        return Ok(r);
    }
    let detections = detect_runtimes(&opts.path);
    let highs: Vec<Runtime> = detections
        .iter()
        .filter(|d| d.confidence == crate::commands::runtime_detect::Confidence::High)
        .map(|d| d.runtime)
        .collect();

    if let [single] = highs.as_slice() {
        return Ok(*single);
    }

    if io::stdin().is_terminal() && io::stdout().is_terminal() {
        return crate::commands::scaffold_wizard::pick_runtime_interactive(&detections);
    }

    if highs.is_empty() {
        let detected = detections
            .iter()
            .map(|d| format!("{} ({:?})", d.runtime.slug(), d.confidence))
            .collect::<Vec<_>>()
            .join(", ");
        Err(CliError::Other(format!(
            "Runtime auto-detection was inconclusive (matches: {detected}). \
             Pass `--runtime <slug>` to pick one explicitly. Available slugs: \
             bun, node-pnpm, node-yarn, node-npm, python-poetry, python-uv, \
             python-pipenv, python-pip, rust, go, docker, blank."
        )))
    } else {
        let slugs: Vec<&'static str> = highs.iter().map(|r| r.slug()).collect();
        Err(CliError::Other(format!(
            "Multiple runtimes detected at high confidence ({}). Pass \
             `--runtime <slug>` to pick one explicitly.",
            slugs.join(", ")
        )))
    }
}

/// Resolve app name from explicit override OR cwd basename.
/// DNS-1123 validation applies to both paths.
fn resolve_app_name(opts: &ScaffoldOpts) -> Result<String> {
    let name = if let Some(n) = &opts.name {
        n.clone()
    } else {
        opts.path
            .canonicalize()
            .ok()
            .and_then(|p| p.file_name().map(|s| s.to_string_lossy().into_owned()))
            .unwrap_or_else(|| "app".to_string())
    };
    validate_dns_1123(&name)?;
    Ok(name)
}

fn validate_dns_1123(name: &str) -> Result<()> {
    if name.is_empty() {
        return Err(CliError::Other("app name must not be empty".into()));
    }
    if name.len() > 63 {
        return Err(CliError::Other(
            "app name must be 1-63 characters (DNS-1123)".into(),
        ));
    }
    let ok = name
        .chars()
        .all(|c| c.is_ascii_lowercase() || c.is_ascii_digit() || c == '-')
        && !name.starts_with('-')
        && !name.ends_with('-');
    if !ok {
        return Err(CliError::Other(format!(
            "app name '{name}' is not DNS-1123 (lower-case [a-z0-9-], no \
             leading/trailing dash). Pass `--name <name>` to override the \
             cwd-derived default."
        )));
    }
    Ok(())
}

/// Match `--runtime <slug>` to `Runtime`. Returns `None` for
/// unknown slugs; caller turns that into a clap-side error
/// before reaching `scaffold`.
pub fn parse_runtime_slug(slug: &str) -> Option<Runtime> {
    match slug {
        "bun" => Some(Runtime::Bun),
        "node-pnpm" => Some(Runtime::NodePnpm),
        "node-yarn" => Some(Runtime::NodeYarn),
        "node-npm" => Some(Runtime::NodeNpm),
        "python-poetry" => Some(Runtime::PythonPoetry),
        "python-uv" => Some(Runtime::PythonUv),
        "python-pipenv" => Some(Runtime::PythonPipenv),
        "python-pip" => Some(Runtime::PythonPip),
        "rust" => Some(Runtime::Rust),
        "go" => Some(Runtime::Go),
        "docker" => Some(Runtime::Docker),
        "blank" => Some(Runtime::Blank),
        _ => None,
    }
}

/// Entry point for `apprafter app scaffold`. Resolves the
/// runtime and app name, renders the template, writes to the
/// target `apprafter/Application.cue` file, and appends a
/// `.apprafter/local/` ignore line to the repo's `.gitignore`
/// when it isn't already listed (best-effort).
pub fn scaffold(opts: ScaffoldOpts) -> Result<()> {
    let runtime = resolve_runtime(&opts)?;
    let name = resolve_app_name(&opts)?;
    let namespace = opts
        .namespace
        .clone()
        .unwrap_or_else(|| DEFAULT_NAMESPACE.to_string());

    let apprafter_dir = opts.path.join("apprafter");
    let target_file = apprafter_dir.join("Application.cue");

    if target_file.exists() && !opts.force {
        return Err(CliError::Other(format!(
            "{} already exists. Pass `--force` to overwrite, or edit the \
             existing manifest in place.",
            target_file.display()
        )));
    }

    std::fs::create_dir_all(&apprafter_dir)
        .map_err(|e| CliError::Other(format!("create {}: {e}", apprafter_dir.display())))?;

    let git_origin = detect_git_origin_in(&opts.path, "origin");
    let image_derived = derive_image_ref(git_origin.as_deref(), &name).is_derived();
    let rendered = render_application(runtime, &name, &namespace, git_origin.as_deref())?;
    std::fs::write(&target_file, &rendered)
        .map_err(|e| CliError::Other(format!("write {}: {e}", target_file.display())))?;

    write_vendored_cue_module(&apprafter_dir)?;

    let gitignore_updated = append_to_gitignore(&opts.path, ".apprafter/local/").unwrap_or(false);

    println!("✓ Scaffolded {}", target_file.display());
    println!(
        "  Runtime:   {} ({})",
        defaults_for(runtime).display,
        runtime.slug()
    );
    println!("  Name:      {name}");
    println!("  Namespace: {namespace}");
    println!(
        "  Vendored:  {}/cue.mod/pkg/apprafter.io/schemas/v1alpha1/ ({} file{})",
        apprafter_dir.display(),
        VENDORED_SCHEMAS.len(),
        if VENDORED_SCHEMAS.len() == 1 { "" } else { "s" }
    );
    if gitignore_updated {
        println!("  .gitignore: appended `.apprafter/local/`");
    }
    println!();
    println!("Next steps:");
    if image_derived {
        println!(
            "  1. Verify the derived image ref in {} matches what your",
            target_file.display()
        );
        println!("     CI publishes (host + name); tune ports.");
    } else {
        println!(
            "  1. Edit {} — replace `REPLACE-ME` in the image ref, tune ports.",
            target_file.display()
        );
    }
    println!("  2. Optional: typed-validate locally —");
    println!("       cd {} && cue vet ./...", apprafter_dir.display());
    println!("     The vendored schemas resolve the `apprafter.io/schemas/");
    println!("     v1alpha1` import without any `cue mod tidy` step.");
    println!("  3. Commit + push to your git remote.");
    println!("  4. `apprafter app add` to register with Argo CD (from the same directory).");

    Ok(())
}

/// Write the cue.mod tree alongside Application.cue:
///
/// ```
/// apprafter/
/// ├── Application.cue
/// └── cue.mod/
///     ├── module.cue                                (local module manifest)
///     └── pkg/
///         └── apprafter.io/
///             └── schemas/
///                 └── v1alpha1/
///                     ├── types.cue                 (vendored)
///                     └── application.cue           (vendored)
/// ```
///
/// CUE's resolver walks up from Application.cue, finds
/// `cue.mod/`, resolves `import "apprafter.io/schemas/v1alpha1"`
/// to the vendored package directory. Works locally for `cue
/// vet` AND inside CMP without any external setup OR network
/// dependency.
///
/// Vendored copies overwritten unconditionally (operators
/// don't edit them; re-scaffold refreshes when AppRafter
/// publishes a new CRD revision).
fn write_vendored_cue_module(apprafter_dir: &Path) -> Result<()> {
    let cue_mod_dir = apprafter_dir.join("cue.mod");
    let pkg_dir = cue_mod_dir
        .join("pkg")
        .join("apprafter.io")
        .join("schemas")
        .join("v1alpha1");
    std::fs::create_dir_all(&pkg_dir)
        .map_err(|e| CliError::Other(format!("create {}: {e}", pkg_dir.display())))?;

    let module_path = cue_mod_dir.join("module.cue");
    std::fs::write(&module_path, CUE_MOD_MODULE_CUE)
        .map_err(|e| CliError::Other(format!("write {}: {e}", module_path.display())))?;

    for (filename, content) in VENDORED_SCHEMAS {
        let target = pkg_dir.join(filename);
        std::fs::write(&target, content)
            .map_err(|e| CliError::Other(format!("write {}: {e}", target.display())))?;
    }
    Ok(())
}

/// Append `line` to `<dir>/.gitignore` if the file exists AND
/// doesn't already contain that line. Returns Ok(true) when
/// the file was modified, Ok(false) when the entry was
/// already present OR no .gitignore exists. Errors return
/// `false` to the caller (non-fatal — scaffold should still
/// succeed even if .gitignore is read-only).
fn append_to_gitignore(dir: &Path, line: &str) -> std::io::Result<bool> {
    let path = dir.join(".gitignore");
    if !path.exists() {
        return Ok(false);
    }
    let content = std::fs::read_to_string(&path)?;
    if content.lines().any(|l| l.trim() == line) {
        return Ok(false);
    }
    let suffix = if content.ends_with('\n') { "" } else { "\n" };
    let new = format!("{content}{suffix}{line}\n");
    std::fs::write(&path, new)?;
    Ok(true)
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::fs;
    use tempfile::tempdir;

    #[test]
    fn render_template_substitutes_known_keys() {
        let tpl = "name: {{name}}, port: {{port}}";
        let mut vars = BTreeMap::new();
        vars.insert("name", "myapp".to_string());
        vars.insert("port", "3000".to_string());
        let out = render_template(tpl, &vars).unwrap();
        assert_eq!(out, "name: myapp, port: 3000");
    }

    #[test]
    fn render_template_handles_repeated_placeholder() {
        let tpl = "{{name}}-{{name}}";
        let mut vars = BTreeMap::new();
        vars.insert("name", "x".to_string());
        assert_eq!(render_template(tpl, &vars).unwrap(), "x-x");
    }

    #[test]
    fn render_template_errors_on_unsubstituted_placeholder() {
        // Catches typo-in-template bugs at render time
        // instead of leaking literal `{{foo}}` into the
        // operator's filesystem.
        let tpl = "name: {{name}}, missing: {{forgot_to_add}}";
        let mut vars = BTreeMap::new();
        vars.insert("name", "ok".to_string());
        let err = render_template(tpl, &vars).unwrap_err();
        assert!(
            err.to_string().contains("unsubstituted placeholder"),
            "error must explicitly call out the unsubstituted placeholder; got: {err}"
        );
    }

    #[test]
    fn kebab_to_camel_basic() {
        assert_eq!(kebab_to_camel("my-app"), "myApp");
        assert_eq!(kebab_to_camel("landing-web"), "landingWeb");
        assert_eq!(kebab_to_camel("a-b-c-d"), "aBCD");
    }

    #[test]
    fn kebab_to_camel_single_segment() {
        assert_eq!(kebab_to_camel("app"), "app");
        assert_eq!(kebab_to_camel("payments"), "payments");
    }

    #[test]
    fn kebab_to_camel_treats_underscore_same_as_dash() {
        // Defensive: operators occasionally type snake_case
        // for app names. DNS-1123 rejects underscores at
        // validation time, but if the helper is called with
        // pre-validation input it shouldn't panic.
        assert_eq!(kebab_to_camel("my_app"), "myApp");
    }

    #[test]
    fn kebab_to_camel_empty_input_returns_app() {
        assert_eq!(kebab_to_camel(""), "app");
    }

    #[test]
    fn defaults_for_every_runtime_has_unique_slug() {
        let runtimes = [
            Runtime::Bun,
            Runtime::NodePnpm,
            Runtime::NodeYarn,
            Runtime::NodeNpm,
            Runtime::PythonPoetry,
            Runtime::PythonUv,
            Runtime::PythonPipenv,
            Runtime::PythonPip,
            Runtime::Rust,
            Runtime::Go,
            Runtime::Docker,
            Runtime::Blank,
        ];
        let mut slugs: Vec<&'static str> = runtimes.iter().map(|r| defaults_for(*r).slug).collect();
        slugs.sort_unstable();
        let pre_dedup_len = slugs.len();
        slugs.dedup();
        assert_eq!(
            pre_dedup_len,
            slugs.len(),
            "defaults_for slugs must be unique; got duplicates"
        );

        // AND each defaults.slug must round-trip via
        // parse_runtime_slug — load-bearing for `--runtime
        // <slug>` flag.
        for r in runtimes {
            let slug = defaults_for(r).slug;
            assert_eq!(
                parse_runtime_slug(slug),
                Some(r),
                "slug `{slug}` must round-trip to its Runtime variant"
            );
        }
    }

    #[test]
    fn render_application_renders_every_runtime_cleanly() {
        // Every runtime must produce non-empty output, must
        // contain the app name + namespace + primary port,
        // and must NOT leak unsubstituted placeholders.
        let runtimes = [
            Runtime::Bun,
            Runtime::NodePnpm,
            Runtime::NodeYarn,
            Runtime::NodeNpm,
            Runtime::PythonPoetry,
            Runtime::PythonUv,
            Runtime::PythonPipenv,
            Runtime::PythonPip,
            Runtime::Rust,
            Runtime::Go,
            Runtime::Docker,
            Runtime::Blank,
        ];
        for r in runtimes {
            let out = render_application(r, "my-app", "apprafter", None)
                .unwrap_or_else(|e| panic!("render failed for {r:?}: {e}"));
            assert!(out.contains("\"my-app\""), "{r:?}: missing app name");
            assert!(
                out.contains("namespace: \"apprafter\""),
                "{r:?}: missing namespace"
            );
            assert!(out.contains("myApp"), "{r:?}: missing CUE binding ident");
            assert!(
                !out.contains("{{"),
                "{r:?}: unsubstituted placeholder leaked"
            );

            let port = defaults_for(r).primary_port.to_string();
            assert!(
                out.contains(&format!("port: {port}")),
                "{r:?}: rendered output missing port {port}"
            );
        }
    }

    #[test]
    fn render_application_blank_uses_blank_template() {
        let out = render_application(Runtime::Blank, "x", "apprafter", None).unwrap();
        assert!(
            out.contains("blank template"),
            "Blank runtime should pick BLANK_TEMPLATE which mentions 'blank template'"
        );
    }

    #[test]
    fn render_application_default_template_has_runtime_display() {
        let out = render_application(Runtime::Bun, "x", "apprafter", None).unwrap();
        assert!(
            out.contains("Bun"),
            "default template should carry runtime display name; got:\n{out}"
        );
    }

    #[test]
    fn render_application_without_origin_emits_placeholder_image_and_todo() {
        // No git origin → REPLACE-ME placeholder + the "replace
        // REPLACE-ME" TODO comment, not the "verify derived" one.
        let out = render_application(Runtime::Rust, "my-app", "apprafter", None).unwrap();
        assert!(out.contains("ghcr.io/REPLACE-ME/my-app:latest"));
        assert!(
            out.contains("replace `REPLACE-ME`"),
            "placeholder image must carry the REPLACE-ME TODO; got:\n{out}"
        );
        assert!(
            !out.contains("Derived from your git origin"),
            "placeholder path must NOT claim the image was derived"
        );
    }

    #[test]
    fn render_application_with_github_origin_derives_image_and_verify_comment() {
        // GitHub origin → ghcr.io/<owner-lower>/<repo-lower> +
        // the "verify derived" comment (host/name may differ).
        let out = render_application(
            Runtime::Docker,
            "landing",
            "procvue",
            Some("https://github.com/ProcVue/landing"),
        )
        .unwrap();
        assert!(
            out.contains("ghcr.io/procvue/landing:latest"),
            "github origin must derive lowercased ghcr ref; got:\n{out}"
        );
        assert!(
            out.contains("Derived from your git origin"),
            "derived image must carry the verify comment"
        );
        assert!(
            !out.contains("REPLACE-ME"),
            "derived path must not leave the REPLACE-ME placeholder"
        );
    }

    // ── derive_image_from_url — pure derivation rules ──────────

    #[test]
    fn derive_github_lowercases_owner_and_repo() {
        assert_eq!(
            derive_image_from_url("https://github.com/ProcVue/landing").as_deref(),
            Some("ghcr.io/procvue/landing:latest")
        );
    }

    #[test]
    fn derive_github_strips_dotgit_and_extra_segments() {
        // `.git` suffix dropped; `/tree/main` ignored — flat
        // owner/repo only.
        assert_eq!(
            derive_image_from_url("https://github.com/acme/web.git").as_deref(),
            Some("ghcr.io/acme/web:latest")
        );
        assert_eq!(
            derive_image_from_url("https://github.com/acme/web/tree/main").as_deref(),
            Some("ghcr.io/acme/web:latest")
        );
    }

    #[test]
    fn derive_gitlab_saas_flat_and_subgroups() {
        assert_eq!(
            derive_image_from_url("https://gitlab.com/acme/app").as_deref(),
            Some("registry.gitlab.com/acme/app:latest")
        );
        // Full project path incl. subgroups — NOT just org/repo.
        assert_eq!(
            derive_image_from_url("https://gitlab.com/acme/team/app").as_deref(),
            Some("registry.gitlab.com/acme/team/app:latest")
        );
        assert_eq!(
            derive_image_from_url("https://gitlab.com/a/b/c/d").as_deref(),
            Some("registry.gitlab.com/a/b/c/d:latest")
        );
    }

    #[test]
    fn derive_self_managed_gitlab_guesses_registry_subdomain() {
        // host contains "gitlab" but ≠ gitlab.com → guess the
        // GitLab-documented registry.<host> subdomain, full path.
        assert_eq!(
            derive_image_from_url("https://gitlab.example.com/mygroup/myproject").as_deref(),
            Some("registry.gitlab.example.com/mygroup/myproject:latest")
        );
        assert_eq!(
            derive_image_from_url("https://gitlab.example.com/acme/team/app").as_deref(),
            Some("registry.gitlab.example.com/acme/team/app:latest")
        );
    }

    #[test]
    fn derive_gitea_forgejo_same_host_flat() {
        assert_eq!(
            derive_image_from_url("https://gitea.example.com/testuser/myrepo").as_deref(),
            Some("gitea.example.com/testuser/myrepo:latest")
        );
        assert_eq!(
            derive_image_from_url("https://forgejo.example.org/team/svc").as_deref(),
            Some("forgejo.example.org/team/svc:latest")
        );
    }

    #[test]
    fn derive_returns_none_for_unmappable_hosts() {
        // Bitbucket (non-derivable image name), GitHub Enterprise
        // (own GHES registry conventions), totally unknown host.
        assert_eq!(
            derive_image_from_url("https://bitbucket.org/workspace/repo"),
            None
        );
        assert_eq!(
            derive_image_from_url("https://github.company.com/org/repo"),
            None
        );
        assert_eq!(
            derive_image_from_url("https://code.example.com/org/repo"),
            None
        );
    }

    #[test]
    fn derive_returns_none_for_non_https_and_ssh() {
        // HTTPS-only in v1. SSH shorthand, ssh://, git://, http://
        // all fall back to the placeholder.
        assert_eq!(
            derive_image_from_url("git@github.com:ProcVue/landing.git"),
            None
        );
        assert_eq!(
            derive_image_from_url("ssh://git@github.com/ProcVue/landing"),
            None
        );
        assert_eq!(derive_image_from_url("http://github.com/acme/web"), None);
    }

    #[test]
    fn derive_returns_none_for_host_suffix_spoof() {
        // SECURITY: github.com must match EXACTLY — a spoof host
        // like github.com.attacker.net must NOT map to ghcr.io.
        // It contains neither "gitlab" nor "gitea"/"forgejo", so
        // it falls through to None.
        assert_eq!(
            derive_image_from_url("https://github.com.attacker.net/a/b"),
            None
        );
    }

    #[test]
    fn derive_returns_none_for_too_few_path_segments() {
        assert_eq!(derive_image_from_url("https://github.com/onlyowner"), None);
        assert_eq!(derive_image_from_url("https://gitlab.com/solo"), None);
        assert_eq!(derive_image_from_url("https://github.com/"), None);
        assert_eq!(derive_image_from_url("https://github.com"), None);
    }

    #[test]
    fn derive_image_ref_wraps_placeholder_and_derived() {
        // None origin → Placeholder; recognised origin → Derived.
        assert_eq!(
            derive_image_ref(None, "my-app"),
            ImageRef::Placeholder("ghcr.io/REPLACE-ME/my-app:latest".to_string())
        );
        assert_eq!(
            derive_image_ref(Some("https://github.com/Acme/Web"), "web"),
            ImageRef::Derived("ghcr.io/acme/web:latest".to_string())
        );
        // Unmappable origin → Placeholder (falls back, doesn't error).
        assert_eq!(
            derive_image_ref(Some("https://bitbucket.org/ws/repo"), "repo"),
            ImageRef::Placeholder("ghcr.io/REPLACE-ME/repo:latest".to_string())
        );
    }

    #[test]
    fn is_oci_safe_segment_accepts_legal_rejects_illegal() {
        assert!(is_oci_safe_segment("landing"));
        assert!(is_oci_safe_segment("my-app"));
        assert!(is_oci_safe_segment("app.v2"));
        assert!(is_oci_safe_segment("a1_b2"));
        assert!(!is_oci_safe_segment("")); // empty
        assert!(!is_oci_safe_segment("Upper")); // uppercase
        assert!(!is_oci_safe_segment("-lead")); // leading sep
        assert!(!is_oci_safe_segment("trail-")); // trailing sep
        assert!(!is_oci_safe_segment("has space")); // space
    }

    #[test]
    fn validate_dns_1123_accepts_well_formed() {
        assert!(validate_dns_1123("my-app").is_ok());
        assert!(validate_dns_1123("payments").is_ok());
        assert!(validate_dns_1123("a").is_ok());
        assert!(validate_dns_1123("app1").is_ok());
    }

    #[test]
    fn validate_dns_1123_rejects_uppercase_underscore_dashes() {
        assert!(validate_dns_1123("MyApp").is_err());
        assert!(validate_dns_1123("my_app").is_err());
        assert!(validate_dns_1123("-leading").is_err());
        assert!(validate_dns_1123("trailing-").is_err());
        assert!(validate_dns_1123("").is_err());
    }

    #[test]
    fn parse_runtime_slug_round_trip() {
        assert_eq!(parse_runtime_slug("bun"), Some(Runtime::Bun));
        assert_eq!(
            parse_runtime_slug("python-poetry"),
            Some(Runtime::PythonPoetry)
        );
        assert_eq!(parse_runtime_slug("rust"), Some(Runtime::Rust));
        assert_eq!(parse_runtime_slug("blank"), Some(Runtime::Blank));
        assert_eq!(parse_runtime_slug("BUN"), None);
        assert_eq!(parse_runtime_slug("unknown"), None);
    }

    #[test]
    fn scaffold_writes_application_cue_and_creates_apprafter_dir() {
        let dir = tempdir().unwrap();
        fs::write(dir.path().join("Cargo.toml"), "[package]\n").unwrap();

        let opts = ScaffoldOpts {
            runtime: None, // detect should pick Rust
            name: Some("my-rust-app".to_string()),
            namespace: None,
            path: dir.path().to_path_buf(),
            force: false,
        };
        scaffold(opts).unwrap();

        let target = dir.path().join("apprafter").join("Application.cue");
        assert!(target.is_file(), "scaffold should create the target file");
        let content = fs::read_to_string(&target).unwrap();
        assert!(content.contains("my-rust-app"));
        assert!(content.contains("port: 8080")); // rust default
        assert!(content.contains("Rust"));
        // Walk-fix #5: typed import constraint replaces inline schema.
        assert!(content.contains("import v1alpha1 \"apprafter.io/schemas/v1alpha1\""));
        assert!(content.contains("v1alpha1.#Application & {"));
    }

    #[test]
    fn scaffold_writes_cue_mod_module_and_vendored_schemas() {
        // Walk-fix #5 regression guard. Scaffold layout:
        //   apprafter/Application.cue
        //   apprafter/cue.mod/module.cue
        //   apprafter/cue.mod/pkg/apprafter.io/schemas/v1alpha1/types.cue
        //   apprafter/cue.mod/pkg/apprafter.io/schemas/v1alpha1/application.cue
        //
        // CUE walks up from Application.cue, finds cue.mod/,
        // resolves the typed import to the vendored pkg.
        let dir = tempdir().unwrap();
        fs::write(dir.path().join("Cargo.toml"), "[package]\n").unwrap();

        scaffold(ScaffoldOpts {
            runtime: Some(Runtime::Rust),
            name: Some("vendored".to_string()),
            namespace: None,
            path: dir.path().to_path_buf(),
            force: false,
        })
        .unwrap();

        let cue_mod = dir.path().join("apprafter").join("cue.mod");
        let pkg = cue_mod
            .join("pkg")
            .join("apprafter.io")
            .join("schemas")
            .join("v1alpha1");

        assert!(cue_mod.join("module.cue").is_file(), "module.cue missing");
        assert!(
            pkg.join("types.cue").is_file(),
            "vendored types.cue missing"
        );
        assert!(
            pkg.join("application.cue").is_file(),
            "vendored application.cue missing"
        );

        // module.cue mentions the AppRafter package path so CUE
        // resolution lands on the vendored schemas.
        let module_content = fs::read_to_string(cue_mod.join("module.cue")).unwrap();
        assert!(
            module_content.contains("language: {")
                && module_content.contains("version: \"v0.10.0\""),
            "module.cue must declare the CUE language version pin; got:\n{module_content}"
        );
    }

    #[test]
    fn scaffold_vendored_schemas_match_embedded_source_byte_for_byte() {
        // Load-bearing — the vendored copy must equal the
        // schema source AppRafter ships, otherwise typed vet
        // diverges from the in-cluster CRD's contract. Catches
        // accidental edits to the include_str! sources OR drift
        // in the schemas/ directory layout.
        let dir = tempdir().unwrap();
        fs::write(dir.path().join("Cargo.toml"), "[package]\n").unwrap();

        scaffold(ScaffoldOpts {
            runtime: Some(Runtime::Rust),
            name: Some("identity".to_string()),
            namespace: None,
            path: dir.path().to_path_buf(),
            force: false,
        })
        .unwrap();

        let pkg = dir
            .path()
            .join("apprafter")
            .join("cue.mod")
            .join("pkg")
            .join("apprafter.io")
            .join("schemas")
            .join("v1alpha1");

        for (filename, source) in VENDORED_SCHEMAS {
            let vendored = fs::read_to_string(pkg.join(filename))
                .unwrap_or_else(|e| panic!("read vendored {filename}: {e}"));
            assert_eq!(
                vendored, *source,
                "vendored {filename} must match embedded source byte-for-byte"
            );
        }
    }

    #[test]
    fn scaffold_refuses_overwrite_without_force() {
        let dir = tempdir().unwrap();
        fs::write(dir.path().join("Cargo.toml"), "[package]\n").unwrap();
        fs::create_dir(dir.path().join("apprafter")).unwrap();
        fs::write(
            dir.path().join("apprafter").join("Application.cue"),
            "existing\n",
        )
        .unwrap();

        let opts = ScaffoldOpts {
            runtime: Some(Runtime::Rust),
            name: Some("x".to_string()),
            namespace: None,
            path: dir.path().to_path_buf(),
            force: false,
        };
        let err = scaffold(opts).unwrap_err();
        assert!(err.to_string().contains("already exists"));
        // Existing file untouched.
        let content =
            fs::read_to_string(dir.path().join("apprafter").join("Application.cue")).unwrap();
        assert_eq!(content, "existing\n");
    }

    #[test]
    fn scaffold_force_overwrites_existing() {
        let dir = tempdir().unwrap();
        fs::write(dir.path().join("Cargo.toml"), "[package]\n").unwrap();
        fs::create_dir(dir.path().join("apprafter")).unwrap();
        fs::write(
            dir.path().join("apprafter").join("Application.cue"),
            "existing\n",
        )
        .unwrap();

        let opts = ScaffoldOpts {
            runtime: Some(Runtime::Rust),
            name: Some("x".to_string()),
            namespace: None,
            path: dir.path().to_path_buf(),
            force: true,
        };
        scaffold(opts).unwrap();
        let content =
            fs::read_to_string(dir.path().join("apprafter").join("Application.cue")).unwrap();
        assert!(!content.starts_with("existing"));
        assert!(content.contains("\"x\""));
    }

    #[test]
    fn scaffold_appends_gitignore_entry_when_absent() {
        let dir = tempdir().unwrap();
        fs::write(dir.path().join("Cargo.toml"), "[package]\n").unwrap();
        fs::write(dir.path().join(".gitignore"), "target/\nnode_modules/\n").unwrap();

        let opts = ScaffoldOpts {
            runtime: Some(Runtime::Rust),
            name: Some("x".to_string()),
            namespace: None,
            path: dir.path().to_path_buf(),
            force: false,
        };
        scaffold(opts).unwrap();
        let content = fs::read_to_string(dir.path().join(".gitignore")).unwrap();
        assert!(
            content.contains(".apprafter/local/"),
            "scaffold should append the local-state ignore; got:\n{content}"
        );
        // Original entries still there.
        assert!(content.contains("target/"));
        assert!(content.contains("node_modules/"));
    }

    #[test]
    fn scaffold_does_not_double_append_existing_gitignore_entry() {
        let dir = tempdir().unwrap();
        fs::write(dir.path().join("Cargo.toml"), "[package]\n").unwrap();
        fs::write(
            dir.path().join(".gitignore"),
            "target/\n.apprafter/local/\n",
        )
        .unwrap();

        let opts = ScaffoldOpts {
            runtime: Some(Runtime::Rust),
            name: Some("x".to_string()),
            namespace: None,
            path: dir.path().to_path_buf(),
            force: false,
        };
        scaffold(opts).unwrap();
        let content = fs::read_to_string(dir.path().join(".gitignore")).unwrap();
        let count = content.matches(".apprafter/local/").count();
        assert_eq!(count, 1, "scaffold should not duplicate gitignore entries");
    }

    #[test]
    fn scaffold_errors_on_inconclusive_runtime_detection_without_override() {
        // Empty dir → only Blank/Fallback. No High match;
        // requires explicit --runtime for standalone scaffold
        // (Part 3b's wizard will prompt).
        let dir = tempdir().unwrap();
        let opts = ScaffoldOpts {
            runtime: None,
            name: Some("x".to_string()),
            namespace: None,
            path: dir.path().to_path_buf(),
            force: false,
        };
        let err = scaffold(opts).unwrap_err();
        let msg = err.to_string();
        assert!(
            msg.contains("--runtime <slug>"),
            "error must point to the override flag; got: {msg}"
        );
    }

    #[test]
    fn scaffold_errors_on_multi_high_runtime_detection_without_override() {
        // bun + Cargo.toml → two Highs. Refuses to pick for
        // the operator; requires explicit --runtime.
        let dir = tempdir().unwrap();
        fs::write(dir.path().join("bun.lock"), "").unwrap();
        fs::write(dir.path().join("Cargo.toml"), "[package]\n").unwrap();

        let opts = ScaffoldOpts {
            runtime: None,
            name: Some("x".to_string()),
            namespace: None,
            path: dir.path().to_path_buf(),
            force: false,
        };
        let err = scaffold(opts).unwrap_err();
        let msg = err.to_string();
        assert!(msg.contains("Multiple runtimes"), "error: {msg}");
        assert!(msg.contains("bun"));
        assert!(msg.contains("rust"));
    }
}
