// SPDX-License-Identifier: FSL-1.1-Apache-2.0
//! The marker is the only way an author can silence the gate, so its
//! grammar is strict: unknown keys, untyped reasons and missing versions
//! are errors, and an exemption expires.

use docsgen::marker::{parse_marker, Check, Marker, Reason};

#[test]
fn a_bare_check_parses() {
    let m: Marker = parse_marker("<!-- docs: check=cli -->").unwrap().unwrap();
    assert_eq!(m.check, Check::Cli);
    assert!(m.run.is_none());
}

#[test]
fn a_run_mode_parses() {
    let m = parse_marker("<!-- docs: check=cli run=local -->")
        .unwrap()
        .unwrap();
    assert_eq!(m.run.as_deref(), Some("local"));
}

#[test]
fn a_kind_parses() {
    let m = parse_marker("<!-- docs: check=cue kind=SourceCredential -->")
        .unwrap()
        .unwrap();
    assert_eq!(m.check, Check::Cue);
    assert_eq!(m.kind.as_deref(), Some("SourceCredential"));
}

#[test]
fn an_exemption_requires_a_typed_reason_and_a_version() {
    let ok = parse_marker(
        "<!-- docs: check=none since=v0.2.45 reason=third-party-output — kubectl output -->",
    )
    .unwrap()
    .unwrap();
    assert_eq!(ok.check, Check::None);
    assert_eq!(ok.reason, Some(Reason::ThirdPartyOutput));
    assert_eq!(ok.since.as_deref(), Some("v0.2.45"));

    assert!(
        parse_marker("<!-- docs: check=none reason=third-party-output -->").is_err(),
        "since= is required"
    );
    assert!(
        parse_marker("<!-- docs: check=none since=v0.2.45 -->").is_err(),
        "reason= is required"
    );
    assert!(
        parse_marker("<!-- docs: check=none since=v0.2.45 reason=because-i-said-so -->").is_err(),
        "the reason vocabulary is closed"
    );
}

#[test]
fn an_unknown_key_is_an_error_not_a_silent_ignore() {
    assert!(parse_marker("<!-- docs: check=cli verify=yes -->").is_err());
}

#[test]
fn a_non_marker_comment_is_not_a_marker() {
    assert!(parse_marker("<!-- generated by docsgen; do not edit -->")
        .unwrap()
        .is_none());
}
