// SPDX-License-Identifier: FSL-1.1-Apache-2.0
//! The rendered artefacts are byte-compared in CI, so determinism and
//! completeness are the properties under test.

use clap::CommandFactory;
use docsgen::render::render_all;

fn artefacts() -> Vec<docsgen::render::Artefact> {
    render_all(
        &apprafter::docs_api::Cli::command(),
        std::path::Path::new("/repo"),
    )
}

fn text_of(name: &str) -> String {
    artefacts()
        .into_iter()
        .find(|a| a.path.ends_with(name))
        .unwrap_or_else(|| panic!("no artefact {name}"))
        .text
}

#[test]
fn rendering_is_byte_deterministic() {
    let a: Vec<_> = artefacts().into_iter().map(|x| (x.path, x.text)).collect();
    let b: Vec<_> = artefacts().into_iter().map(|x| (x.path, x.text)).collect();
    assert_eq!(a, b);
}

#[test]
fn every_visible_top_level_command_gets_a_page() {
    let cmd = apprafter::docs_api::Cli::command();
    for sub in cmd.get_subcommands() {
        let name = sub.get_name();
        if name == "help" {
            continue;
        }
        let page = format!("{name}.md");
        let has = artefacts().iter().any(|a| a.path.ends_with(&page));
        assert_eq!(
            has,
            !sub.is_hide_set(),
            "page presence for {name} must match visibility"
        );
    }
}

#[test]
fn pages_carry_frontmatter_and_the_generated_banner() {
    let page = text_of("secret.md");
    assert!(
        page.starts_with("---\n"),
        "the docs frontmatter validator requires it"
    );
    assert!(page.contains("audience: reference"));
    assert!(page.contains("<!-- generated by docsgen; do not edit -->"));
}

#[test]
fn a_flag_default_reaches_the_rendered_table() {
    let page = text_of("secret.md");
    assert!(
        page.contains("`--namespace`"),
        "flag missing from the table"
    );
    assert!(
        page.contains("apprafter-system"),
        "default missing from the table"
    );
}

#[test]
fn summary_lists_the_index_and_every_page() {
    let summary = text_of("SUMMARY.md");
    assert!(summary.contains("[Overview](index.md)"));
    for a in artefacts() {
        let file = a.path.file_name().unwrap().to_string_lossy().to_string();
        if file.ends_with(".md") && file != "SUMMARY.md" && file != "index.md" {
            assert!(summary.contains(&file), "SUMMARY.md is missing {file}");
        }
    }
}

#[test]
fn commands_json_is_pretty_and_ends_with_a_newline() {
    let json = text_of("commands.json");
    assert!(
        json.ends_with('\n'),
        "a trailing newline keeps git diffs clean"
    );
    let parsed: serde_json::Value = serde_json::from_str(&json).expect("valid json");
    assert!(parsed["commands"].as_array().unwrap().len() > 50);
}
