/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    'waitlist-signups': WaitlistSignup;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    'waitlist-signups': WaitlistSignupsSelect<false> | WaitlistSignupsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: ('false' | 'none' | 'null') | false | null | 'en' | 'en'[];
  globals: {
    'site-settings': SiteSetting;
    'landing-hero': LandingHero;
    'value-props': ValueProp;
    'scaling-journey': ScalingJourney;
    'tier-ladder': TierLadder;
    comparison: Comparison;
    'landing-transparency': LandingTransparency;
    'boring-tech': BoringTech;
    advantages: Advantage;
    roadmap: Roadmap;
    'bootstrap-strip': BootstrapStrip;
    'footer-content': FooterContent;
    'waitlist-form-copy': WaitlistFormCopy;
    booking: Booking;
    publishing: Publishing;
  };
  globalsSelect: {
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
    'landing-hero': LandingHeroSelect<false> | LandingHeroSelect<true>;
    'value-props': ValuePropsSelect<false> | ValuePropsSelect<true>;
    'scaling-journey': ScalingJourneySelect<false> | ScalingJourneySelect<true>;
    'tier-ladder': TierLadderSelect<false> | TierLadderSelect<true>;
    comparison: ComparisonSelect<false> | ComparisonSelect<true>;
    'landing-transparency': LandingTransparencySelect<false> | LandingTransparencySelect<true>;
    'boring-tech': BoringTechSelect<false> | BoringTechSelect<true>;
    advantages: AdvantagesSelect<false> | AdvantagesSelect<true>;
    roadmap: RoadmapSelect<false> | RoadmapSelect<true>;
    'bootstrap-strip': BootstrapStripSelect<false> | BootstrapStripSelect<true>;
    'footer-content': FooterContentSelect<false> | FooterContentSelect<true>;
    'waitlist-form-copy': WaitlistFormCopySelect<false> | WaitlistFormCopySelect<true>;
    booking: BookingSelect<false> | BookingSelect<true>;
    publishing: PublishingSelect<false> | PublishingSelect<true>;
  };
  locale: 'en';
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name?: string | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * Launch waitlist. Email is the unique key; interests record which upcoming releases the signup wants; wantsCall toggles a follow-up Calendly invitation.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "waitlist-signups".
 */
export interface WaitlistSignup {
  id: number;
  email: string;
  /**
   * Optional one-liner — Mary, 3 services, on Render
   */
  useCase?: string | null;
  /**
   * Which upcoming releases this signup wants to hear about.
   */
  interests?: ('tier2' | 'observability' | 'managed' | 'tier3' | 'tier4')[] | null;
  /**
   * Triggers a Calendly link email via afterChange hook.
   */
  wantsCall?: boolean | null;
  /**
   * document.referrer at submit time — empty means direct visit.
   */
  source?: string | null;
  /**
   * Stamped by the hook after the Calendly email is sent.
   */
  callEmailSentAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'waitlist-signups';
        value: number | WaitlistSignup;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "waitlist-signups_select".
 */
export interface WaitlistSignupsSelect<T extends boolean = true> {
  email?: T;
  useCase?: T;
  interests?: T;
  wantsCall?: T;
  source?: T;
  callEmailSentAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * Cross-page site config: external links exposed in nav/footer + (later) analytics domain.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  githubUrl: string;
  specUrl: string;
  /**
   * Empty renders the nav Docs link with a "Soon" badge pointing to GitHub README.
   */
  docsUrl?: string | null;
  /**
   * Reserved for Phase I+ analytics. Leave empty for v1.
   */
  plausibleDomain?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "landing-hero".
 */
export interface LandingHero {
  id: number;
  /**
   * Raw HTML — wrap accented words in <span class="accented">…</span>.
   */
  headlineHtml: string;
  subhead: string;
  statusBadge: string;
  cueFilename: string;
  cueSnippet: string;
  primaryCTA: {
    label: string;
    href: string;
  };
  /**
   * Opens the inline waitlist form — no href needed, just a label.
   */
  secondaryCTA: {
    label: string;
  };
  tertiaryCTA: {
    label: string;
    href: string;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "value-props".
 */
export interface ValueProp {
  id: number;
  blocks?:
    | {
        title: string;
        /**
         * Raw HTML — inline <code class="mono"> spans for code identifiers are supported.
         */
        bodyHtml: string;
        iconName: 'grid' | 'bars' | 'lock';
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "scaling-journey".
 */
export interface ScalingJourney {
  id: number;
  eyebrow: string;
  title: string;
  /**
   * HTML — <code class="mono"> supported.
   */
  ledeHtml: string;
  leftStage: {
    eyebrow: string;
    fileName: string;
    fileMeta: string;
    caption: string;
  };
  rightStage: {
    eyebrow: string;
    fileName: string;
    fileMeta: string;
    caption: string;
  };
  arrowLabel: string;
  footerKickers?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  /**
   * HTML — wrap the leading "Today:" in <strong>.
   */
  caveatHtml: string;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tier-ladder".
 */
export interface TierLadder {
  id: number;
  eyebrow: string;
  title: string;
  cards?:
    | {
        num: string;
        title: string;
        price: string;
        desc: string;
        status: 'live' | 'roadmap';
        statusText: string;
        id?: string | null;
      }[]
    | null;
  /**
   * HTML — wrap "Confidential containers" in <strong>.
   */
  orthogonalNoteHtml: string;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "comparison".
 */
export interface Comparison {
  id: number;
  eyebrow: string;
  title: string;
  /**
   * Three-column header labels + status pills.
   */
  columns: {
    self: {
      label: string;
      statusKind: 'live' | 'waitlist' | 'roadmap';
      statusLabel: string;
    };
    managed: {
      label: string;
      badgeSuffix?: string | null;
      statusKind: 'live' | 'waitlist' | 'roadmap';
      statusLabel: string;
    };
    turnkey: {
      label: string;
      badgeSuffix?: string | null;
      statusKind: 'live' | 'waitlist' | 'roadmap';
      statusLabel: string;
    };
  };
  rows?:
    | {
        label: string;
        selfHtml: string;
        managedHtml: string;
        turnkeyHtml: string;
        id?: string | null;
      }[]
    | null;
  /**
   * HTML — uses <sup>†</sup> for the dagger marker.
   */
  footnoteHtml: string;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Three cards below the Comparison table: 4.5.1 Pricing / 4.5.2 Anti-lock / 4.5.3 Alignment.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "landing-transparency".
 */
export interface LandingTransparency {
  id: number;
  blocks?:
    | {
        kicker: string;
        title: string;
        /**
         * HTML — wrap paragraphs in <p>…</p>, use <strong> for emphasis, <code> for inline tokens.
         */
        bodyHtml: string;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "boring-tech".
 */
export interface BoringTech {
  id: number;
  eyebrow: string;
  title: string;
  lede: string;
  underHood?:
    | {
        name: string;
        desc: string;
        id?: string | null;
      }[]
    | null;
  ourCode?:
    | {
        name: string;
        desc: string;
        id?: string | null;
      }[]
    | null;
  /**
   * HTML — emphasis via <strong>.
   */
  closingHtml: string;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "advantages".
 */
export interface Advantage {
  id: number;
  eyebrow: string;
  title: string;
  lede: string;
  blocks?:
    | {
        title: string;
        /**
         * HTML — open with a <strong> claim, may contain inline <code class="mono">.
         */
        leadHtml: string;
        detail: string;
        phaseTag: string;
        /**
         * Spans the full row as a closer card. Use sparingly — one per section.
         */
        featured?: boolean | null;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "roadmap".
 */
export interface Roadmap {
  id: number;
  eyebrow: string;
  title: string;
  lede: string;
  phases?:
    | {
        /**
         * e.g. "Phase 4", "Phase 8+" — the slug used for the section anchor id is derived from this string.
         */
        num: string;
        title: string;
        items?:
          | {
              text: string;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  closing: string;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * One italic line above the footer — bootstrap-funded / no-VC angle.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "bootstrap-strip".
 */
export interface BootstrapStrip {
  id: number;
  body: string;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer-content".
 */
export interface FooterContent {
  id: number;
  brandDesc: string;
  columns?:
    | {
        heading: string;
        links?:
          | {
              label: string;
              href: string;
              /**
               * Renders with target="_blank" rel="noreferrer".
               */
              external?: boolean | null;
              /**
               * Appends a small "SOON" badge.
               */
              soon?: boolean | null;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  /**
   * {{year}} is replaced with the current year at render time.
   */
  copyright: string;
  licenseNote: string;
  founderNote: string;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Visible copy for the inline waitlist form (Svelte island in Hero).
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "waitlist-form-copy".
 */
export interface WaitlistFormCopy {
  id: number;
  formIntro: string;
  emailLabel: string;
  useCaseLabel: string;
  interestsLabel: string;
  /**
   * Phase-keyed checkboxes. `key` must match WaitlistSignups.interests values.
   */
  interests?:
    | {
        key: string;
        label: string;
        id?: string | null;
      }[]
    | null;
  callLabel: string;
  submitLabel: string;
  successMessage: string;
  successWithCall: string;
  storageNote: string;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Discovery-call booking URL + email template for waitlist signups that ticked "I’d like a short call".
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "booking".
 */
export interface Booking {
  id: number;
  /**
   * Calendly (or compatible) link sent to wantsCall=true signups.
   */
  discoveryCallUrl: string;
  discoveryCallEmailSubject: string;
  /**
   * Plaintext email body. {{url}} is replaced with discoveryCallUrl at send time.
   */
  discoveryCallEmailBody: string;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Preview ↔ prod promotion control. Tick `promoteToProd` and save to retag :preview → :prod. The checkbox auto-resets after each save.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "publishing".
 */
export interface Publishing {
  id: number;
  /**
   * Latest content-global save (stamped by notifyRebuild).
   */
  lastEditAt?: string | null;
  /**
   * Slug of the global that was edited last.
   */
  lastEditedGlobal?: string | null;
  /**
   * Most recent successful Promote-to-prod. Preview is ahead of prod when lastEditAt is later than this.
   */
  lastPromotedAt?: string | null;
  /**
   * Tick + Save to retag ghcr.io/<owner>/landing-web:preview → :prod (+ :latest). Auto-resets to false after save.
   */
  promoteToProd?: boolean | null;
  /**
   * Last 20 content edits since the most recent promote. Cleared on Promote-to-prod.
   */
  editLog?:
    | {
        at: string;
        global: string;
        editor?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  githubUrl?: T;
  specUrl?: T;
  docsUrl?: T;
  plausibleDomain?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "landing-hero_select".
 */
export interface LandingHeroSelect<T extends boolean = true> {
  headlineHtml?: T;
  subhead?: T;
  statusBadge?: T;
  cueFilename?: T;
  cueSnippet?: T;
  primaryCTA?:
    | T
    | {
        label?: T;
        href?: T;
      };
  secondaryCTA?:
    | T
    | {
        label?: T;
      };
  tertiaryCTA?:
    | T
    | {
        label?: T;
        href?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "value-props_select".
 */
export interface ValuePropsSelect<T extends boolean = true> {
  blocks?:
    | T
    | {
        title?: T;
        bodyHtml?: T;
        iconName?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "scaling-journey_select".
 */
export interface ScalingJourneySelect<T extends boolean = true> {
  eyebrow?: T;
  title?: T;
  ledeHtml?: T;
  leftStage?:
    | T
    | {
        eyebrow?: T;
        fileName?: T;
        fileMeta?: T;
        caption?: T;
      };
  rightStage?:
    | T
    | {
        eyebrow?: T;
        fileName?: T;
        fileMeta?: T;
        caption?: T;
      };
  arrowLabel?: T;
  footerKickers?:
    | T
    | {
        text?: T;
        id?: T;
      };
  caveatHtml?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tier-ladder_select".
 */
export interface TierLadderSelect<T extends boolean = true> {
  eyebrow?: T;
  title?: T;
  cards?:
    | T
    | {
        num?: T;
        title?: T;
        price?: T;
        desc?: T;
        status?: T;
        statusText?: T;
        id?: T;
      };
  orthogonalNoteHtml?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "comparison_select".
 */
export interface ComparisonSelect<T extends boolean = true> {
  eyebrow?: T;
  title?: T;
  columns?:
    | T
    | {
        self?:
          | T
          | {
              label?: T;
              statusKind?: T;
              statusLabel?: T;
            };
        managed?:
          | T
          | {
              label?: T;
              badgeSuffix?: T;
              statusKind?: T;
              statusLabel?: T;
            };
        turnkey?:
          | T
          | {
              label?: T;
              badgeSuffix?: T;
              statusKind?: T;
              statusLabel?: T;
            };
      };
  rows?:
    | T
    | {
        label?: T;
        selfHtml?: T;
        managedHtml?: T;
        turnkeyHtml?: T;
        id?: T;
      };
  footnoteHtml?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "landing-transparency_select".
 */
export interface LandingTransparencySelect<T extends boolean = true> {
  blocks?:
    | T
    | {
        kicker?: T;
        title?: T;
        bodyHtml?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "boring-tech_select".
 */
export interface BoringTechSelect<T extends boolean = true> {
  eyebrow?: T;
  title?: T;
  lede?: T;
  underHood?:
    | T
    | {
        name?: T;
        desc?: T;
        id?: T;
      };
  ourCode?:
    | T
    | {
        name?: T;
        desc?: T;
        id?: T;
      };
  closingHtml?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "advantages_select".
 */
export interface AdvantagesSelect<T extends boolean = true> {
  eyebrow?: T;
  title?: T;
  lede?: T;
  blocks?:
    | T
    | {
        title?: T;
        leadHtml?: T;
        detail?: T;
        phaseTag?: T;
        featured?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "roadmap_select".
 */
export interface RoadmapSelect<T extends boolean = true> {
  eyebrow?: T;
  title?: T;
  lede?: T;
  phases?:
    | T
    | {
        num?: T;
        title?: T;
        items?:
          | T
          | {
              text?: T;
              id?: T;
            };
        id?: T;
      };
  closing?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "bootstrap-strip_select".
 */
export interface BootstrapStripSelect<T extends boolean = true> {
  body?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer-content_select".
 */
export interface FooterContentSelect<T extends boolean = true> {
  brandDesc?: T;
  columns?:
    | T
    | {
        heading?: T;
        links?:
          | T
          | {
              label?: T;
              href?: T;
              external?: T;
              soon?: T;
              id?: T;
            };
        id?: T;
      };
  copyright?: T;
  licenseNote?: T;
  founderNote?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "waitlist-form-copy_select".
 */
export interface WaitlistFormCopySelect<T extends boolean = true> {
  formIntro?: T;
  emailLabel?: T;
  useCaseLabel?: T;
  interestsLabel?: T;
  interests?:
    | T
    | {
        key?: T;
        label?: T;
        id?: T;
      };
  callLabel?: T;
  submitLabel?: T;
  successMessage?: T;
  successWithCall?: T;
  storageNote?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "booking_select".
 */
export interface BookingSelect<T extends boolean = true> {
  discoveryCallUrl?: T;
  discoveryCallEmailSubject?: T;
  discoveryCallEmailBody?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "publishing_select".
 */
export interface PublishingSelect<T extends boolean = true> {
  lastEditAt?: T;
  lastEditedGlobal?: T;
  lastPromotedAt?: T;
  promoteToProd?: T;
  editLog?:
    | T
    | {
        at?: T;
        global?: T;
        editor?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}