// SPDX-License-Identifier: FSL-1.1-Apache-2.0

package v1alpha1

// MigrationPlan is auto-generated by a reconciler when it detects a
// destructive change. Execution is paused until explicit human
// approval. See ADR 0012 and spec.md §3.8.
#MigrationPlan: {
	#TypeMeta
	kind:     "MigrationPlan"
	metadata: #ObjectMeta
	spec: {
		application: string
		environment: string

		trigger: {
			type:  string
			field: string
			from?: _
			to?:   _
		}

		risks?: {
			estimatedDowntime?:  string
			dataVolume?:         string
			reversible?:         bool
			requiresFullBackup?: bool
		}

		plan?: [...{
			step:   int & >0
			action: string
		}]

		approvers?: [...string]
	}

	status?: {
		phase?: "pending-approval" | "approved" | "rejected" | "running" | "completed" | "failed"
	}
}
