// SPDX-License-Identifier: FSL-1.1-Apache-2.0

package v1alpha1

// ResourceClaim is generated by the Application operator when an
// Application declares a `need`. It is routed to a matching
// ServiceProvider via labels.
//
// Operator-only resource: admission rejects user-created claims
// (the operator generates them in 2.4). `status` (provider,
// connectionSecretRef, ready, conditions) is the controller's report
// surface — schema only here; the reconciler that writes it lands
// in 2.3.
#ResourceClaim: {
	#TypeMeta
	kind:     "ResourceClaim"
	metadata: #ObjectMeta
	spec: {
		type: #PlatformServiceType
		// `(type, name)` claim identity (2.6b / ADR 0043). Set by the
		// Application controller from a named `needs.<type>[].name`
		// entry so the provisioner derives distinct DBs/users/
		// connection-Secrets for sibling claims of one app. Absent for
		// the unnamed default claim.
		name?: string
		selector: [string]: string
		// `size` is per-type — the admission webhook is the gate: a t-shirt
		// `#Size` for service claims (pg/redis/…), a Kubernetes quantity
		// (e.g. 10Gi) for the `disk` claim (2.6b / ADR 0043). CUE/CRD stay
		// a plain string because they cannot express the per-type split;
		// `#Size` itself (types.cue) is unchanged for its other uses.
		size?: string
		// Persist the provisioned resource across the claim's deletion
		// (default false). Copied from the originating
		// `needs.<type>.persistent` by the Application controller (2.4d);
		// the dragonfly provisioner reads it to pick a persistent vs
		// ephemeral pool instance (ADR 0042).
		persistent?: bool
		// 2.5d prerequisite (ADR 0061 §6 amendment): present only for
		// `type: "jetstream"` claims. See `#ResourceClaimJetStream`'s own
		// doc for what this is and why jetstream is the one claim type
		// that cannot follow `needs.disk`'s `mountPath`-stays-on-the-
		// Application precedent.
		jetstream?: #ResourceClaimJetStream
	}

	status?: {
		provider?:            string
		connectionSecretRef?: string
		ready?:               bool
		// Controller-reported conditions. Read-only schema in 2.2;
		// the reconciler that writes them lands in 2.3. Mirrors the
		// condition shape used by the other CRDs.
		conditions?: [...#ResourceClaimCondition]
		// Dragonfly allocation (ADR 0042): the shared pool instance this
		// claim's DB lives on, and the numbered logical DB ($N). Absent
		// for non-pooled backends (e.g. CNPG).
		instance?: string
		dbnum?:    int & >=0 & <1024
		// Disk allocation (2.6b): the standalone RWO PVC name created by
		// the `Backend::Disk` provisioner. The renderer mounts this PVC
		// into the workload. Absent for non-disk backends (parallel to
		// connectionSecretRef).
		volumeClaimRef?: string
	}
}

// #ResourceClaimJetStream — the jetstream permission model's INPUT,
// carried on the claim itself (2.5d prerequisite / ADR 0061 §6
// amendment). This is NOT a copy of the manifest kept for convenience,
// and it is NOT app-side wiring the way `#DiskClaim.mountPath` is
// (which stays on the Application; the renderer reads it there,
// unchanged by this precedent) — `dynamicStreams`, `streams` and
// `consume` are what the resourceclaim-provisioner's allow list and
// deny vector are COMPUTED FROM (`nats_accounts::allow_list` /
// `deny_vector`). Without them on the claim there is no allow list and
// no deny vector: `JetStreamNeed::as_service_need()` (operator-core)
// already discards all three when projecting onto the generic
// `#ServiceNeed`/`ResourceClaimSpec` shape, and nothing else carried
// them across — a gap 2.5d's `nats.rs` Task 7 investigation found
// before writing any code against it: as scoped, that task could only
// ever have produced empty declarations for every claim.
//
// Reaches the claim, not a second read of the Application, because the
// resourceclaim-provisioner already WATCHES `ResourceClaim` — a
// declaration edit updates the claim and reconciles through the path
// that already exists. Reading `needs.jetstream` from the Application
// instead would need new RBAC, new event plumbing, and a
// claim→application resolution whose failure mode is a permission
// vector computed from a STALE declaration (the claim says one thing,
// the Application has already moved on).
//
// Reuses `#JetStreamStream` / `#JetStreamConsume` from
// `application.cue` verbatim rather than duplicating them:
// `resourceclaim.cue` and `application.cue` are both `package
// v1alpha1` in this same directory, so both definitions are already
// visible here with no import. A second, independent pair would have
// been exactly the drift `#ClaimFieldsFor` (schemas/v1alpha1/
// application.cue, the hand-synced Rust JETSTREAM_FIELDS mirror) is
// the one existing instance of in this repo — not a precedent to add
// to.
#ResourceClaimJetStream: {
	dynamicStreams?: bool | *false
	streams?: [...#JetStreamStream]
	consume?: [...#JetStreamConsume]
}

#ResourceClaimCondition: {
	type:               string
	status:             "True" | "False" | "Unknown"
	reason?:            string
	message?:           string
	lastTransitionTime: string
}
