// SPDX-License-Identifier: FSL-1.1-MIT

package v1alpha1

// ResourceClaim is generated by the Application operator when an
// Application declares a `need`. It is routed to a matching
// ServiceProvider via labels.
//
// Operator-only resource: admission rejects user-created claims.
// Full status (provider, connectionSecretRef, conditions) lands in
// phase 2.2.
#ResourceClaim: {
	#TypeMeta
	kind:     "ResourceClaim"
	metadata: #ObjectMeta
	spec: {
		type: #PlatformServiceType
		selector: [string]: string
		size?: #Size
	}

	status?: {
		provider?:            string
		connectionSecretRef?: string
		ready?:               bool
	}
}
