// SPDX-License-Identifier: FSL-1.1-Apache-2.0

package v1alpha1

// ResourceClaim is generated by the Application operator when an
// Application declares a `need`. It is routed to a matching
// ServiceProvider via labels.
//
// Operator-only resource: admission rejects user-created claims.
// Full status (provider, connectionSecretRef, conditions) lands in
// phase 2.2.
#ResourceClaim: {
	#TypeMeta
	kind:     "ResourceClaim"
	metadata: #ObjectMeta
	spec: {
		type: #PlatformServiceType
		selector: [string]: string
		size?: #Size
	}

	status?: {
		provider?:            string
		connectionSecretRef?: string
		ready?:               bool
		// Controller-reported conditions. Read-only schema in 2.2;
		// the reconciler that writes them lands in 2.3. Mirrors the
		// condition shape used by the other CRDs.
		conditions?: [...#ResourceClaimCondition]
	}
}

#ResourceClaimCondition: {
	type:               string
	status:             "True" | "False" | "Unknown"
	reason?:            string
	message?:           string
	lastTransitionTime: string
}
