// SPDX-License-Identifier: FSL-1.1-Apache-2.0
//! Tier-1 admission-webhook deployment.
//!
//! Emits a 5-document YAML — Namespace, cert-manager Certificate,
//! Service, Deployment, ValidatingWebhookConfiguration — that
//! plugs the v0.1.23 admission webhook into the kube-apiserver via
//! cert-manager's `inject-ca-from` annotation.
//!
//! The certificate is issued by the v0.1.15 self-signed
//! `apprafter-selfsigned` ClusterIssuer. The webhook only validates
//! `apprafter.io/v1alpha1` `Application` resources on CREATE +
//! UPDATE; `failurePolicy: Fail` + `timeoutSeconds: 10` keep the
//! gate strict but bounded.

use crate::k8s::issuer::APPRAFTER_SELFSIGNED_ISSUER;

/// Cluster-side namespace where the admission webhook (and future
/// operator components) run.
pub const APPRAFTER_SYSTEM_NAMESPACE: &str = "apprafter-system";

const ADMISSION_WEBHOOK_NAME: &str = "admission-webhook";
const ADMISSION_WEBHOOK_TLS_SECRET: &str = "admission-webhook-tls";

/// Cluster-side YAML for the admission-webhook stack with the
/// supplied container image. All resources carry `apprafter=true`
/// so destroy / import flows can find them.
pub fn admission_webhook_yaml(image: &str) -> String {
    format!(
        r#"# SPDX-License-Identifier: MIT
# Generated by AppRafter — see cli-providers::k8s::admission_webhook.
apiVersion: v1
kind: Namespace
metadata:
  name: {APPRAFTER_SYSTEM_NAMESPACE}
  labels:
    apprafter: "true"
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {ADMISSION_WEBHOOK_TLS_SECRET}
  namespace: {APPRAFTER_SYSTEM_NAMESPACE}
  labels:
    apprafter: "true"
spec:
  secretName: {ADMISSION_WEBHOOK_TLS_SECRET}
  dnsNames:
    - {ADMISSION_WEBHOOK_NAME}.{APPRAFTER_SYSTEM_NAMESPACE}
    - {ADMISSION_WEBHOOK_NAME}.{APPRAFTER_SYSTEM_NAMESPACE}.svc
    - {ADMISSION_WEBHOOK_NAME}.{APPRAFTER_SYSTEM_NAMESPACE}.svc.cluster.local
  issuerRef:
    name: {APPRAFTER_SELFSIGNED_ISSUER}
    kind: ClusterIssuer
---
apiVersion: v1
kind: Service
metadata:
  name: {ADMISSION_WEBHOOK_NAME}
  namespace: {APPRAFTER_SYSTEM_NAMESPACE}
  labels:
    apprafter: "true"
spec:
  type: ClusterIP
  selector:
    app: {ADMISSION_WEBHOOK_NAME}
  ports:
    - name: https
      port: 443
      targetPort: 8443
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {ADMISSION_WEBHOOK_NAME}
  namespace: {APPRAFTER_SYSTEM_NAMESPACE}
  labels:
    apprafter: "true"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {ADMISSION_WEBHOOK_NAME}
  template:
    metadata:
      labels:
        app: {ADMISSION_WEBHOOK_NAME}
        apprafter: "true"
    spec:
      containers:
        - name: {ADMISSION_WEBHOOK_NAME}
          image: {image}
          ports:
            - name: https
              containerPort: 8443
          env:
            - name: PORT
              value: "8443"
            - name: TLS_CERT_PATH
              value: /tls/tls.crt
            - name: TLS_KEY_PATH
              value: /tls/tls.key
          readinessProbe:
            httpGet:
              path: /readyz
              port: 8443
              scheme: HTTPS
            initialDelaySeconds: 5
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8443
              scheme: HTTPS
            initialDelaySeconds: 10
            periodSeconds: 10
          volumeMounts:
            - name: tls
              mountPath: /tls
              readOnly: true
      volumes:
        - name: tls
          secret:
            secretName: {ADMISSION_WEBHOOK_TLS_SECRET}
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: admission-webhook.apprafter.io
  labels:
    apprafter: "true"
  annotations:
    cert-manager.io/inject-ca-from: {APPRAFTER_SYSTEM_NAMESPACE}/{ADMISSION_WEBHOOK_TLS_SECRET}
webhooks:
  - name: applications.apprafter.io
    sideEffects: None
    failurePolicy: Fail
    admissionReviewVersions:
      - v1
    timeoutSeconds: 10
    clientConfig:
      service:
        name: {ADMISSION_WEBHOOK_NAME}
        namespace: {APPRAFTER_SYSTEM_NAMESPACE}
        path: /validate
        port: 443
    rules:
      - apiGroups:
          - apprafter.io
        apiVersions:
          - v1alpha1
        operations:
          - CREATE
          - UPDATE
        resources:
          - applications
        scope: Namespaced
"#
    )
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn namespace_pins_apprafter_system_and_label() {
        let y = admission_webhook_yaml("ghcr.io/acme/webhook:1.0");
        assert!(y.contains("kind: Namespace"), "{y}");
        assert!(
            y.contains(&format!("name: {APPRAFTER_SYSTEM_NAMESPACE}")),
            "{y}"
        );
        assert!(y.contains("apprafter: \"true\""), "{y}");
    }

    #[test]
    fn certificate_uses_apprafter_selfsigned_clusterissuer() {
        let y = admission_webhook_yaml("ghcr.io/acme/webhook:1.0");
        assert!(y.contains("kind: Certificate"), "{y}");
        assert!(
            y.contains(&format!("name: {APPRAFTER_SELFSIGNED_ISSUER}")),
            "{y}"
        );
        assert!(y.contains("kind: ClusterIssuer"), "{y}");
    }

    #[test]
    fn certificate_dns_names_match_service_fqdns() {
        let y = admission_webhook_yaml("ghcr.io/acme/webhook:1.0");
        assert!(
            y.contains(&format!(
                "- {ADMISSION_WEBHOOK_NAME}.{APPRAFTER_SYSTEM_NAMESPACE}.svc.cluster.local"
            )),
            "{y}"
        );
        assert!(
            y.contains(&format!(
                "- {ADMISSION_WEBHOOK_NAME}.{APPRAFTER_SYSTEM_NAMESPACE}.svc"
            )),
            "{y}"
        );
    }

    #[test]
    fn service_routes_443_to_pod_8443() {
        let y = admission_webhook_yaml("ghcr.io/acme/webhook:1.0");
        assert!(y.contains("kind: Service"), "{y}");
        assert!(y.contains("port: 443"), "{y}");
        assert!(y.contains("targetPort: 8443"), "{y}");
    }

    #[test]
    fn deployment_uses_provided_image() {
        let y = admission_webhook_yaml("ghcr.io/acme/webhook:1.0");
        assert!(y.contains("image: ghcr.io/acme/webhook:1.0"), "{y}");
    }

    #[test]
    fn deployment_mounts_tls_secret_at_slash_tls() {
        let y = admission_webhook_yaml("ghcr.io/acme/webhook:1.0");
        assert!(y.contains("mountPath: /tls"), "{y}");
        assert!(y.contains("readOnly: true"), "{y}");
        assert!(
            y.contains(&format!("secretName: {ADMISSION_WEBHOOK_TLS_SECRET}")),
            "{y}"
        );
    }

    #[test]
    fn deployment_probes_use_https_scheme_on_8443() {
        let y = admission_webhook_yaml("ghcr.io/acme/webhook:1.0");
        // Both probes must hit HTTPS on the container port.
        assert_eq!(
            y.matches("scheme: HTTPS").count(),
            2,
            "expected scheme: HTTPS on both readiness and liveness: {y}"
        );
        assert!(y.contains("path: /readyz"), "{y}");
        assert!(y.contains("path: /healthz"), "{y}");
    }

    #[test]
    fn validating_webhook_config_pins_rules_and_inject_ca_annotation() {
        let y = admission_webhook_yaml("ghcr.io/acme/webhook:1.0");
        assert!(y.contains("kind: ValidatingWebhookConfiguration"), "{y}");
        assert!(
            y.contains(&format!(
                "cert-manager.io/inject-ca-from: {APPRAFTER_SYSTEM_NAMESPACE}/{ADMISSION_WEBHOOK_TLS_SECRET}"
            )),
            "{y}"
        );
        assert!(y.contains("- apprafter.io"), "{y}");
        assert!(y.contains("- v1alpha1"), "{y}");
        assert!(y.contains("- applications"), "{y}");
        assert!(y.contains("- CREATE"), "{y}");
        assert!(y.contains("- UPDATE"), "{y}");
        assert!(y.contains("failurePolicy: Fail"), "{y}");
        assert!(y.contains("sideEffects: None"), "{y}");
    }
}
