// SPDX-License-Identifier: FSL-1.1-MIT
//! Generator for the v1alpha1 `Application` CustomResourceDefinition.
//!
//! Hand-rolled OpenAPI v3 mirroring `schemas/v1alpha1/application.cue`.
//! The `#ApplicationSpec` shape is inlined twice — once under `base`,
//! once under `environments.additionalProperties` — because the
//! kube-apiserver's structural-schema rules forbid `$ref` /
//! `definitions` inside CRD validation schemas.
//!
//! `subresources.status: {}` enables the /status subresource —
//! AND the schema's top-level `properties.status` block declares
//! the field set the operator writes (`phase` / `observedGeneration`
//! / `conditions` / `endpointURL`). Without both, the apiserver
//! accepts the CR but rejects status-subresource PATCH with
//! `.status: field not declared in schema` (v0.1.62 fix —
//! previously the subresources block was present but the status
//! schema was absent, so the operator's first reconcile against a
//! real cluster failed on every status-write attempt).

/// CRD group — `apprafter.io`. The Rust manifest mirror reads
/// `apiVersion: apprafter.io/v1alpha1`.
pub const APPLICATION_CRD_GROUP: &str = "apprafter.io";

/// Stored / served version for v1alpha1.
pub const APPLICATION_CRD_VERSION: &str = "v1alpha1";

/// Plural name, used as the CRD's `metadata.name` prefix
/// (`<plural>.<group>`).
pub const APPLICATION_CRD_PLURAL: &str = "applications";

/// Cluster-side YAML for the Application CRD. Single document
/// (`apiextensions.k8s.io/v1`). Mirrors the field set of
/// `schemas/v1alpha1/application.cue`: `image` (any string in CUE,
/// pinned non-empty here via `pattern: "^.+$"`), `replicas` (≥0),
/// `expose` (port required, public bool, network enum — CUE adds a
/// `*"internal"` default; the kube-apiserver does not, so an absent
/// field stays absent in the stored object), `env` (string→string),
/// and `environments` map of overrides. The `apprafter=true` label
/// lets destroy / import flows find it.
pub fn application_crd_yaml() -> String {
    format!(
        r#"# SPDX-License-Identifier: MIT
# Generated by AppRafter — see cli-providers::k8s::application_crd.
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: {APPLICATION_CRD_PLURAL}.{APPLICATION_CRD_GROUP}
  labels:
    apprafter: "true"
spec:
  group: {APPLICATION_CRD_GROUP}
  scope: Namespaced
  names:
    kind: Application
    listKind: ApplicationList
    plural: {APPLICATION_CRD_PLURAL}
    singular: application
    shortNames:
      - apr
  versions:
    - name: {APPLICATION_CRD_VERSION}
      served: true
      storage: true
      subresources:
        status: {{}}
      schema:
        openAPIV3Schema:
          type: object
          properties:
            apiVersion:
              type: string
            kind:
              type: string
            metadata:
              type: object
            spec:
              type: object
              properties:
                base:
                  type: object
                  properties:
                    image:
                      type: string
                      pattern: "^.+$"
                    replicas:
                      type: integer
                      minimum: 0
                    expose:
                      type: object
                      required:
                        - port
                      properties:
                        port:
                          type: integer
                          minimum: 1
                          maximum: 65535
                        public:
                          type: boolean
                        network:
                          type: string
                          enum:
                            - public
                            - internal
                            - vpn
                    env:
                      type: object
                      additionalProperties:
                        type: string
                environments:
                  type: object
                  additionalProperties:
                    type: object
                    properties:
                      image:
                        type: string
                        pattern: "^.+$"
                      replicas:
                        type: integer
                        minimum: 0
                      expose:
                        type: object
                        required:
                          - port
                        properties:
                          port:
                            type: integer
                            minimum: 1
                            maximum: 65535
                          public:
                            type: boolean
                          network:
                            type: string
                            enum:
                              - public
                              - internal
                              - vpn
                      env:
                        type: object
                        additionalProperties:
                          type: string
            status:
              type: object
              properties:
                phase:
                  type: string
                observedGeneration:
                  type: integer
                  format: int64
                endpointURL:
                  type: string
                conditions:
                  type: array
                  items:
                    type: object
                    required:
                      - type
                      - status
                      - lastTransitionTime
                      - reason
                      - message
                    properties:
                      type:
                        type: string
                      status:
                        type: string
                      lastTransitionTime:
                        type: string
                      reason:
                        type: string
                      message:
                        type: string
                      observedGeneration:
                        type: integer
                        format: int64
"#
    )
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn header_pins_apiversion_and_kind() {
        let y = application_crd_yaml();
        assert!(y.contains("apiVersion: apiextensions.k8s.io/v1"), "{y}");
        assert!(y.contains("kind: CustomResourceDefinition"), "{y}");
    }

    #[test]
    fn metadata_pins_name_and_apprafter_label() {
        let y = application_crd_yaml();
        assert!(y.contains("name: applications.apprafter.io"), "{y}");
        assert!(y.contains("apprafter: \"true\""), "{y}");
    }

    #[test]
    fn spec_pins_group_and_namespaced_scope() {
        let y = application_crd_yaml();
        assert!(
            y.contains(&format!("group: {APPLICATION_CRD_GROUP}")),
            "{y}"
        );
        assert!(y.contains("scope: Namespaced"), "{y}");
    }

    #[test]
    fn names_block_pins_kind_plural_singular_and_shortname() {
        let y = application_crd_yaml();
        assert!(y.contains("kind: Application"), "{y}");
        assert!(y.contains("listKind: ApplicationList"), "{y}");
        assert!(
            y.contains(&format!("plural: {APPLICATION_CRD_PLURAL}")),
            "{y}"
        );
        assert!(y.contains("singular: application"), "{y}");
        assert!(y.contains("- apr"), "{y}");
    }

    #[test]
    fn version_marked_served_and_storage_with_subresource_status() {
        let y = application_crd_yaml();
        assert!(
            y.contains(&format!("name: {APPLICATION_CRD_VERSION}")),
            "{y}"
        );
        assert!(y.contains("served: true"), "{y}");
        assert!(y.contains("storage: true"), "{y}");
        assert!(y.contains("subresources:"), "{y}");
        assert!(y.contains("status: {}"), "{y}");
    }

    #[test]
    fn application_spec_schema_appears_twice_for_base_and_environment_overrides() {
        let y = application_crd_yaml();
        // The image-pattern, replicas-minimum, port-range, and
        // network-enum lines must appear under both `base` and
        // `environments.additionalProperties`.
        assert_eq!(
            y.matches("pattern: \"^.+$\"").count(),
            2,
            "image pattern must appear twice (base + envs override): {y}"
        );
        assert_eq!(
            y.matches("minimum: 0").count(),
            2,
            "replicas minimum must appear twice: {y}"
        );
        assert_eq!(
            y.matches("maximum: 65535").count(),
            2,
            "expose.port maximum must appear twice: {y}"
        );
    }

    #[test]
    fn expose_section_pins_port_range_and_network_enum() {
        let y = application_crd_yaml();
        assert!(y.contains("minimum: 1"), "{y}");
        assert!(y.contains("maximum: 65535"), "{y}");
        // The enum order is fixed; assert the literal block.
        assert!(y.contains("- public\n"), "{y}");
        assert!(y.contains("- internal\n"), "{y}");
        assert!(y.contains("- vpn\n"), "{y}");
    }

    #[test]
    fn status_subschema_declares_every_field_the_operator_writes() {
        // Regression guard for v0.1.62: previously the CRD enabled
        // `subresources.status: {}` (the /status endpoint) but
        // declared no `properties.status` block in the OpenAPIv3
        // schema. Result: the apiserver accepted the CR on apply,
        // and the operator's first reconcile failed with
        // `.status: field not declared in schema` on every
        // status-subresource PATCH. The four sub-fields must stay
        // in lockstep with `operator-core::ApplicationStatus`.
        let y = application_crd_yaml();
        // The top-level status property must exist...
        assert!(
            y.contains("\n            status:\n              type: object"),
            "status property must be declared at the same indent level as spec: {y}"
        );
        // ...and every field operator_core::ApplicationStatus
        // writes must be in the schema.
        for field in &[
            "phase:",
            "observedGeneration:",
            "endpointURL:",
            "conditions:",
        ] {
            assert!(
                y.contains(field),
                "ApplicationStatus.{field} must be declared in CRD properties.status; \
                 without it `.status: field not declared in schema` from apiserver: {y}"
            );
        }
        // ApplicationCondition's required fields.
        for field in &["lastTransitionTime:", "reason:", "message:"] {
            assert!(
                y.contains(field),
                "ApplicationCondition.{field} must be declared: {y}"
            );
        }
    }

    #[test]
    fn env_is_string_to_string_map() {
        let y = application_crd_yaml();
        // The env block must be a string→string map (object with
        // additionalProperties: type: string). It appears twice —
        // once under `spec.base.env`, once under `spec.environments.*.env`.
        // Assert the literal shape at both indentation levels.
        assert!(
            y.contains(
                "env:\n                      type: object\n                      additionalProperties:\n                        type: string"
            ),
            "spec.base.env shape missing: {y}"
        );
        assert!(
            y.contains(
                "env:\n                        type: object\n                        additionalProperties:\n                          type: string"
            ),
            "spec.environments.*.env shape missing: {y}"
        );
    }
}
