// SPDX-License-Identifier: FSL-1.1-MIT
//! Tier-1 Helm values for the upstream `argo-cd` chart.
//!
//! Pure string composition. The CLI writes the result to a
//! tempfile and passes that path to `helm upgrade --install`.

/// Pinned Argo CD chart version. Bumped intentionally — bump in
/// lockstep with the cert-manager / HTTPRoute work in v0.1.15 so
/// the UI exposure path stays in sync with the install.
pub const ARGOCD_CHART_VERSION: &str = "7.7.7";

/// Helm values YAML for a single-node k3s cluster. Tier-1 keeps
/// every sub-chart at one replica, disables Dex (admin-only auth),
/// turns off Redis-HA (one Redis pod is plenty), and silences
/// notifications. The Server runs as a ClusterIP — exposure via
/// Gateway API HTTPRoute lands in v0.1.15.
pub fn argocd_values_yaml() -> String {
    r#"# Generated by AppRafter — see cli-providers::k8s::argocd_values.
dex:
  enabled: false
redis-ha:
  enabled: false
controller:
  replicas: 1
server:
  replicas: 1
  service:
    type: ClusterIP
repoServer:
  replicas: 1
applicationSet:
  enabled: true
  replicas: 1
notifications:
  enabled: false
"#
    .to_string()
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn dex_is_disabled_for_admin_only_auth() {
        let y = argocd_values_yaml();
        assert!(y.contains("dex:"), "{y}");
        assert!(y.contains("enabled: false"), "{y}");
    }

    #[test]
    fn redis_ha_is_disabled_on_tier_1() {
        let y = argocd_values_yaml();
        assert!(y.contains("redis-ha:"), "{y}");
    }

    #[test]
    fn server_runs_as_cluster_ip_until_httproute_lands() {
        let y = argocd_values_yaml();
        assert!(y.contains("server:"), "{y}");
        assert!(y.contains("type: ClusterIP"), "{y}");
    }

    #[test]
    fn every_subchart_pinned_to_one_replica() {
        let y = argocd_values_yaml();
        let count = y.matches("replicas: 1").count();
        assert!(
            count >= 4,
            "expected at least 4 occurrences of `replicas: 1`, got {count}: {y}"
        );
    }

    #[test]
    fn applicationset_is_enabled() {
        let y = argocd_values_yaml();
        assert!(y.contains("applicationSet:"), "{y}");
        assert!(y.contains("enabled: true"), "{y}");
    }

    #[test]
    fn notifications_off_to_keep_tier_1_lean() {
        let y = argocd_values_yaml();
        assert!(y.contains("notifications:"), "{y}");
    }
}
