// SPDX-License-Identifier: FSL-1.1-MIT
//! Generator for the Argo CD repository-credentials `Secret`.
//!
//! Pure string composition. `cluster-bootstrap` writes the result
//! to a tempfile and applies it via `kubectl apply -f` after the
//! Argo CD helm release is up but before the bootstrap `Application`
//! references the private repo URL. Argo CD discovers the Secret by
//! its `argocd.argoproj.io/secret-type: repository` label and uses
//! the `username` + `password` fields for HTTPS basic auth scoped
//! to `url`.

/// Name of the Secret created in the `argocd` namespace. Stable
/// across cluster-bootstrap re-runs — `kubectl apply` overwrites
/// the existing payload when the env-var supplies a new token.
pub const APPRAFTER_BOOTSTRAP_REPO_CREDS_SECRET: &str = "apprafter-bootstrap-repo-creds";

/// Default username used in the Secret when `APPRAFTER_ARGOCD_REPO_USERNAME`
/// is unset. Both GitHub and GitLab accept any non-empty username
/// when authenticating with a PAT in the password slot.
pub const ARGOCD_REPO_USERNAME_DEFAULT: &str = "apprafter";

/// Cluster-side YAML for the Argo CD repository-credentials Secret.
/// `stringData` lets the apiserver base64-encode the values on
/// apply — keeps the rendered manifest readable.
pub fn argocd_repo_secret_yaml(repo_url: &str, username: &str, token: &str) -> String {
    format!(
        r#"# Generated by AppRafter — see cli-providers::k8s::argocd_repo_secret.
apiVersion: v1
kind: Secret
metadata:
  name: {APPRAFTER_BOOTSTRAP_REPO_CREDS_SECRET}
  namespace: argocd
  labels:
    apprafter: "true"
    argocd.argoproj.io/secret-type: repository
type: Opaque
stringData:
  url: {repo_url}
  username: {username}
  password: {token}
"#
    )
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn metadata_pins_name_namespace_and_apprafter_label() {
        let y = argocd_repo_secret_yaml("https://github.com/org/state.git", "apprafter", "ghp_xxx");
        assert!(
            y.contains(&format!("name: {APPRAFTER_BOOTSTRAP_REPO_CREDS_SECRET}")),
            "{y}"
        );
        assert!(y.contains("namespace: argocd"), "{y}");
        assert!(y.contains("apprafter: \"true\""), "{y}");
    }

    #[test]
    fn metadata_carries_argocd_secret_type_repository_label() {
        let y = argocd_repo_secret_yaml("https://github.com/org/state.git", "apprafter", "ghp_xxx");
        assert!(
            y.contains("argocd.argoproj.io/secret-type: repository"),
            "{y}"
        );
    }

    #[test]
    fn string_data_propagates_url_username_token() {
        let y = argocd_repo_secret_yaml(
            "https://gitlab.com/group/repo.git",
            "x-access-token",
            "glpat-secret",
        );
        assert!(y.contains("url: https://gitlab.com/group/repo.git"), "{y}");
        assert!(y.contains("username: x-access-token"), "{y}");
        assert!(y.contains("password: glpat-secret"), "{y}");
    }

    #[test]
    fn secret_type_is_opaque() {
        let y = argocd_repo_secret_yaml("https://github.com/org/state.git", "apprafter", "ghp_xxx");
        assert!(y.contains("type: Opaque"), "{y}");
    }
}
