// SPDX-License-Identifier: FSL-1.1-MIT
//! Generators for the Argo CD UI exposure manifests:
//! - Gateway (HTTPS listener with hostname + TLS terminate).
//! - HTTPRoute (routes / to argocd-server).
//! - Certificate (cert-manager-issued from APPRAFTER_SELFSIGNED_ISSUER).
//!
//! Pure string composition. Caller writes the result to a tempfile
//! and applies it via `kubectl apply -f`.

use crate::k8s::issuer::APPRAFTER_SELFSIGNED_ISSUER;

/// Cluster-side YAML for Argo CD UI exposure on the given domain.
/// Emits a 3-document manifest (Gateway + HTTPRoute + Certificate)
/// in the `argocd` namespace, all labelled `apprafter=true`. The
/// Gateway uses the Cilium gatewayClass and references a Secret
/// (`argocd-tls`) that cert-manager populates from the
/// self-signed ClusterIssuer.
pub fn argocd_gateway_yaml(domain: &str) -> String {
    format!(
        r#"# Generated by AppRafter — see cli-providers::k8s::argocd_gateway.
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: argocd-gateway
  namespace: argocd
  labels:
    apprafter: "true"
spec:
  gatewayClassName: cilium
  listeners:
    - name: https
      protocol: HTTPS
      port: 443
      hostname: {domain}
      tls:
        mode: Terminate
        certificateRefs:
          - name: argocd-tls
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: argocd
  namespace: argocd
  labels:
    apprafter: "true"
spec:
  parentRefs:
    - name: argocd-gateway
  hostnames:
    - {domain}
  rules:
    - backendRefs:
        - name: argocd-server
          port: 80
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: argocd-tls
  namespace: argocd
  labels:
    apprafter: "true"
spec:
  secretName: argocd-tls
  issuerRef:
    name: {APPRAFTER_SELFSIGNED_ISSUER}
    kind: ClusterIssuer
  dnsNames:
    - {domain}
"#
    )
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn gateway_uses_cilium_gateway_class() {
        let y = argocd_gateway_yaml("argo.example.com");
        assert!(y.contains("kind: Gateway"), "{y}");
        assert!(y.contains("gatewayClassName: cilium"), "{y}");
    }

    #[test]
    fn gateway_listener_terminates_tls_on_443() {
        let y = argocd_gateway_yaml("argo.example.com");
        assert!(y.contains("protocol: HTTPS"), "{y}");
        assert!(y.contains("port: 443"), "{y}");
        assert!(y.contains("mode: Terminate"), "{y}");
    }

    #[test]
    fn gateway_listener_pins_hostname_from_argument() {
        let y = argocd_gateway_yaml("argo.example.com");
        assert!(y.contains("hostname: argo.example.com"), "{y}");
    }

    #[test]
    fn httproute_routes_to_argocd_server_on_80() {
        let y = argocd_gateway_yaml("argo.example.com");
        assert!(y.contains("kind: HTTPRoute"), "{y}");
        assert!(y.contains("name: argocd-server"), "{y}");
        assert!(y.contains("port: 80"), "{y}");
    }

    #[test]
    fn certificate_references_apprafter_selfsigned_issuer() {
        let y = argocd_gateway_yaml("argo.example.com");
        assert!(y.contains("kind: Certificate"), "{y}");
        assert!(
            y.contains(&format!("name: {APPRAFTER_SELFSIGNED_ISSUER}")),
            "{y}"
        );
        assert!(y.contains("kind: ClusterIssuer"), "{y}");
    }

    #[test]
    fn every_resource_carries_apprafter_label() {
        let y = argocd_gateway_yaml("argo.example.com");
        assert!(
            y.matches("apprafter: \"true\"").count() >= 3,
            "expected ≥3 apprafter labels: {y}"
        );
    }
}
