// SPDX-License-Identifier: FSL-1.1-MIT
//! Tier-1 `app-config.yaml` for the Backstage host app.
//!
//! Pure string composition. The result is embedded as the
//! `app-config.yaml` key in a Kubernetes `ConfigMap` (see
//! `backstage_manifests_yaml`) and mounted into the Deployment
//! at `/app/app-config.yaml`, overriding the file baked into the
//! container image at build time.

/// Tier-1 Backstage `app-config.yaml`.
///
/// Bakes in the URL fan-out (`app.baseUrl`, `backend.baseUrl`,
/// `backend.cors.origin`) from the same `domain`, listens on
/// `0.0.0.0:7007` (so the Service can route traffic), uses an
/// in-memory SQLite database (data resets on pod restart — fine
/// for tier-1), enables the `guest` auth provider with
/// `dangerouslyAllowOutsideDevelopment: true` (Backstage's
/// canonical basic-admin stub), and lists the standard catalog
/// entity kinds.
pub fn backstage_app_config_yaml(domain: &str) -> String {
    format!(
        r#"# Generated by AppRafter — see cli-providers::k8s::backstage_app_config.
app:
  title: AppRafter Backstage
  baseUrl: https://{domain}
backend:
  baseUrl: https://{domain}
  listen:
    host: 0.0.0.0
    port: 7007
  cors:
    origin: https://{domain}
    methods: [GET, HEAD, PATCH, POST, PUT, DELETE]
    credentials: true
  database:
    client: better-sqlite3
    connection: ":memory:"
auth:
  environment: production
  providers:
    guest:
      dangerouslyAllowOutsideDevelopment: true
catalog:
  rules:
    - allow: [Component, System, API, Resource, Location]
"#
    )
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn app_block_pins_title_and_baseurl() {
        let y = backstage_app_config_yaml("backstage.example.com");
        assert!(y.contains("title: AppRafter Backstage"), "{y}");
        assert!(y.contains("baseUrl: https://backstage.example.com"), "{y}");
    }

    #[test]
    fn backend_listens_on_0_0_0_0_port_7007() {
        let y = backstage_app_config_yaml("backstage.example.com");
        assert!(y.contains("host: 0.0.0.0"), "{y}");
        assert!(y.contains("port: 7007"), "{y}");
    }

    #[test]
    fn cors_origin_propagates_from_domain() {
        let y = backstage_app_config_yaml("backstage.example.com");
        assert!(y.contains("origin: https://backstage.example.com"), "{y}");
        assert!(y.contains("credentials: true"), "{y}");
    }

    #[test]
    fn database_uses_in_memory_sqlite_on_tier_1() {
        let y = backstage_app_config_yaml("backstage.example.com");
        assert!(y.contains("client: better-sqlite3"), "{y}");
        assert!(y.contains("\":memory:\""), "{y}");
    }

    #[test]
    fn auth_enables_guest_provider_with_dangerous_flag() {
        let y = backstage_app_config_yaml("backstage.example.com");
        assert!(y.contains("auth:"), "{y}");
        assert!(y.contains("environment: production"), "{y}");
        assert!(y.contains("providers:"), "{y}");
        assert!(y.contains("guest:"), "{y}");
        assert!(
            y.contains("dangerouslyAllowOutsideDevelopment: true"),
            "{y}"
        );
    }
}
