// SPDX-License-Identifier: FSL-1.1-MIT
//! Tier-1 Backstage manifest set: Namespace + Deployment + Service
//! + HTTPRoute + Gateway + cert-manager Certificate. Pure string
//! composition.
//!
//! The Deployment runs a single replica on Backstage's default
//! port 7007 with a small probe surface; the operator is expected
//! to swap in their own image (and an `app-config.yaml` ConfigMap
//! mount once v0.1.20 wires OAuth) when shipping for real.

use crate::k8s::issuer::APPRAFTER_SELFSIGNED_ISSUER;

/// Placeholder Backstage image used when the operator's manifest
/// doesn't pin one. Lets `cluster-bootstrap` produce a runnable
/// (if catalog-empty) Backstage even before they build their own
/// image.
pub const BACKSTAGE_DEFAULT_IMAGE: &str = "ghcr.io/apprafter/backstage:placeholder";

const BACKSTAGE_NAMESPACE: &str = "backstage";

/// Cluster-side YAML for the tier-1 Backstage stack on the given
/// domain. Emits a 6-document manifest in the `backstage`
/// namespace:
/// - Namespace,
/// - Deployment (1 replica, the supplied or placeholder image),
/// - Service (ClusterIP, port 80 → backend port 7007),
/// - HTTPRoute (Gateway API, hostname → Service),
/// - Gateway (Cilium, HTTPS+TLS terminate),
/// - cert-manager Certificate (issued by `apprafter-selfsigned`).
///
/// All resources carry `apprafter=true` so destroy / import flows
/// can find them.
pub fn backstage_manifests_yaml(domain: &str, image: &str) -> String {
    let effective_image = if image.is_empty() {
        BACKSTAGE_DEFAULT_IMAGE
    } else {
        image
    };
    format!(
        r#"# Generated by AppRafter — see cli-providers::k8s::backstage_manifests.
apiVersion: v1
kind: Namespace
metadata:
  name: {BACKSTAGE_NAMESPACE}
  labels:
    apprafter: "true"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backstage
  namespace: {BACKSTAGE_NAMESPACE}
  labels:
    apprafter: "true"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backstage
  template:
    metadata:
      labels:
        app: backstage
        apprafter: "true"
    spec:
      containers:
        - name: backstage
          image: {effective_image}
          ports:
            - containerPort: 7007
          readinessProbe:
            httpGet:
              path: /healthcheck
              port: 7007
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /healthcheck
              port: 7007
            initialDelaySeconds: 30
            periodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  name: backstage
  namespace: {BACKSTAGE_NAMESPACE}
  labels:
    apprafter: "true"
spec:
  type: ClusterIP
  selector:
    app: backstage
  ports:
    - name: http
      port: 80
      targetPort: 7007
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: backstage
  namespace: {BACKSTAGE_NAMESPACE}
  labels:
    apprafter: "true"
spec:
  parentRefs:
    - name: backstage-gateway
  hostnames:
    - {domain}
  rules:
    - backendRefs:
        - name: backstage
          port: 80
---
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: backstage-gateway
  namespace: {BACKSTAGE_NAMESPACE}
  labels:
    apprafter: "true"
spec:
  gatewayClassName: cilium
  listeners:
    - name: https
      protocol: HTTPS
      port: 443
      hostname: {domain}
      tls:
        mode: Terminate
        certificateRefs:
          - name: backstage-tls
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: backstage-tls
  namespace: {BACKSTAGE_NAMESPACE}
  labels:
    apprafter: "true"
spec:
  secretName: backstage-tls
  issuerRef:
    name: {APPRAFTER_SELFSIGNED_ISSUER}
    kind: ClusterIssuer
  dnsNames:
    - {domain}
"#
    )
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn namespace_pins_apprafter_label_and_name() {
        let y = backstage_manifests_yaml("backstage.example.com", "");
        assert!(y.contains("kind: Namespace"), "{y}");
        assert!(y.contains(&format!("name: {BACKSTAGE_NAMESPACE}")), "{y}");
        assert!(y.contains("apprafter: \"true\""), "{y}");
    }

    #[test]
    fn deployment_uses_provided_image() {
        let y = backstage_manifests_yaml("backstage.example.com", "ghcr.io/acme/bs:1.0");
        assert!(y.contains("image: ghcr.io/acme/bs:1.0"), "{y}");
    }

    #[test]
    fn empty_image_falls_back_to_placeholder() {
        let y = backstage_manifests_yaml("backstage.example.com", "");
        assert!(
            y.contains(&format!("image: {BACKSTAGE_DEFAULT_IMAGE}")),
            "{y}"
        );
    }

    #[test]
    fn service_targets_port_7007() {
        let y = backstage_manifests_yaml("backstage.example.com", "");
        assert!(y.contains("kind: Service"), "{y}");
        assert!(y.contains("port: 80"), "{y}");
        assert!(y.contains("targetPort: 7007"), "{y}");
    }

    #[test]
    fn httproute_pins_hostname_and_routes_to_backstage() {
        let y = backstage_manifests_yaml("backstage.example.com", "");
        assert!(y.contains("kind: HTTPRoute"), "{y}");
        assert!(y.contains("hostname: backstage.example.com"), "{y}");
        assert!(y.contains("name: backstage"), "{y}");
    }

    #[test]
    fn certificate_references_apprafter_selfsigned_issuer() {
        let y = backstage_manifests_yaml("backstage.example.com", "");
        assert!(y.contains("kind: Certificate"), "{y}");
        assert!(
            y.contains(&format!("name: {APPRAFTER_SELFSIGNED_ISSUER}")),
            "{y}"
        );
        assert!(y.contains("kind: ClusterIssuer"), "{y}");
    }
}
