// SPDX-License-Identifier: FSL-1.1-MIT
//! Generator for the Argo CD bootstrap `Application` manifest.
//!
//! Pure string composition. The CLI writes the result to a tempfile
//! and applies it via `kubectl apply -f` after Argo CD itself is up.

/// Default sub-path within the bootstrap Git repo when the manifest
/// doesn't pin one. Argo CD treats `.` as repo root.
pub const BOOTSTRAP_APP_DEFAULT_PATH: &str = ".";

/// Cluster-side YAML for the Argo CD `Application` named
/// `bootstrap`. Targets the `argocd` namespace and the in-cluster
/// API server, syncs `path` from `repo_url` HEAD, and turns on
/// auto-prune + self-heal so a `git push` to the repo propagates
/// into the cluster without operator intervention. Carries the
/// apprafter=true label.
pub fn bootstrap_application_yaml(repo_url: &str, path: &str) -> String {
    let effective_path = if path.is_empty() {
        BOOTSTRAP_APP_DEFAULT_PATH
    } else {
        path
    };
    format!(
        r#"# Generated by AppRafter — see cli-providers::k8s::bootstrap_app.
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: bootstrap
  namespace: argocd
  labels:
    apprafter: "true"
spec:
  project: default
  source:
    repoURL: {repo_url}
    targetRevision: HEAD
    path: {effective_path}
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
"#
    )
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn header_pins_argoproj_apiversion_and_application_kind() {
        let y = bootstrap_application_yaml("https://example.com/repo.git", "clusters/prod");
        assert!(y.contains("apiVersion: argoproj.io/v1alpha1"), "{y}");
        assert!(y.contains("kind: Application"), "{y}");
    }

    #[test]
    fn metadata_pins_name_namespace_and_apprafter_label() {
        let y = bootstrap_application_yaml("https://example.com/repo.git", "clusters/prod");
        assert!(y.contains("name: bootstrap"), "{y}");
        assert!(y.contains("namespace: argocd"), "{y}");
        assert!(y.contains("apprafter: \"true\""), "{y}");
    }

    #[test]
    fn source_block_propagates_repo_url_and_path() {
        let y = bootstrap_application_yaml("https://example.com/repo.git", "clusters/prod");
        assert!(y.contains("repoURL: https://example.com/repo.git"), "{y}");
        assert!(y.contains("targetRevision: HEAD"), "{y}");
        assert!(y.contains("path: clusters/prod"), "{y}");
    }

    #[test]
    fn empty_path_falls_back_to_default_dot() {
        let y = bootstrap_application_yaml("https://example.com/repo.git", "");
        assert!(
            y.contains(&format!("path: {BOOTSTRAP_APP_DEFAULT_PATH}")),
            "{y}"
        );
    }

    #[test]
    fn sync_policy_enables_auto_prune_and_self_heal() {
        let y = bootstrap_application_yaml("https://example.com/repo.git", ".");
        assert!(y.contains("syncPolicy:"), "{y}");
        assert!(y.contains("prune: true"), "{y}");
        assert!(y.contains("selfHeal: true"), "{y}");
    }
}
