// SPDX-License-Identifier: FSL-1.1-Apache-2.0
//! Tier-1 Helm values for the upstream `jetstack/cert-manager`
//! chart. Pure string composition.

/// Pinned cert-manager chart version. Bumped intentionally — bump
/// in lockstep with the Gateway/HTTPRoute work in v0.1.16.
pub const CERT_MANAGER_CHART_VERSION: &str = "v1.16.2";

/// Helm values YAML for a single-node k3s cluster. cert-manager
/// installs its own CRDs (`crds.enabled: true`) so we don't need
/// a separate `kubectl apply` for the CRDs. Webhook + cainjector +
/// controller all pinned to a single replica; Prometheus metrics
/// disabled (tier-1 stays lean).
///
/// The chart's old top-level `installCRDs: true` was deprecated
/// in v1.15+ and emitted a noisy
/// `WARNING: \`installCRDs\` is deprecated, use \`crds.enabled\`
/// instead.` on every `cluster-bootstrap`. Switched to the new
/// nested form in v0.1.48.
pub fn cert_manager_values_yaml() -> String {
    r#"# Generated by AppRafter — see cli-providers::k8s::cert_manager_values.
crds:
  enabled: true
replicaCount: 1
webhook:
  replicaCount: 1
cainjector:
  replicaCount: 1
prometheus:
  enabled: false
"#
    .to_string()
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn crds_enabled_is_true_so_we_can_skip_a_separate_apply() {
        let y = cert_manager_values_yaml();
        assert!(y.contains("crds:") && y.contains("enabled: true"), "{y}");
    }

    #[test]
    fn does_not_use_deprecated_top_level_install_crds() {
        let y = cert_manager_values_yaml();
        assert!(
            !y.contains("installCRDs"),
            "deprecated since cert-manager v1.15 — emits a WARNING on every cluster-bootstrap; use the nested `crds.enabled` form instead.\n{y}"
        );
    }

    #[test]
    fn controller_pinned_to_one_replica() {
        let y = cert_manager_values_yaml();
        assert!(y.contains("replicaCount: 1"), "{y}");
    }

    #[test]
    fn webhook_pinned_to_one_replica() {
        let y = cert_manager_values_yaml();
        assert!(y.contains("webhook:"), "{y}");
    }

    #[test]
    fn cainjector_pinned_to_one_replica() {
        let y = cert_manager_values_yaml();
        assert!(y.contains("cainjector:"), "{y}");
    }

    #[test]
    fn prometheus_off_to_keep_tier_1_lean() {
        let y = cert_manager_values_yaml();
        assert!(y.contains("prometheus:"), "{y}");
        assert!(y.contains("enabled: false"), "{y}");
    }
}
