// SPDX-License-Identifier: FSL-1.1-MIT
//! Tier-1 Helm values for the upstream `jetstack/cert-manager`
//! chart. Pure string composition.

/// Pinned cert-manager chart version. Bumped intentionally — bump
/// in lockstep with the Gateway/HTTPRoute work in v0.1.16.
pub const CERT_MANAGER_CHART_VERSION: &str = "v1.16.2";

/// Helm values YAML for a single-node k3s cluster. cert-manager
/// installs its own CRDs (installCRDs: true) so we don't need a
/// separate `kubectl apply` for the CRDs. Webhook + cainjector +
/// controller all pinned to a single replica; Prometheus metrics
/// disabled (tier-1 stays lean).
pub fn cert_manager_values_yaml() -> String {
    r#"# Generated by AppRafter — see cli-providers::k8s::cert_manager_values.
installCRDs: true
replicaCount: 1
webhook:
  replicaCount: 1
cainjector:
  replicaCount: 1
prometheus:
  enabled: false
"#
    .to_string()
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn install_crds_is_true_so_we_can_skip_a_separate_apply() {
        let y = cert_manager_values_yaml();
        assert!(y.contains("installCRDs: true"), "{y}");
    }

    #[test]
    fn controller_pinned_to_one_replica() {
        let y = cert_manager_values_yaml();
        assert!(y.contains("replicaCount: 1"), "{y}");
    }

    #[test]
    fn webhook_pinned_to_one_replica() {
        let y = cert_manager_values_yaml();
        assert!(y.contains("webhook:"), "{y}");
    }

    #[test]
    fn cainjector_pinned_to_one_replica() {
        let y = cert_manager_values_yaml();
        assert!(y.contains("cainjector:"), "{y}");
    }

    #[test]
    fn prometheus_off_to_keep_tier_1_lean() {
        let y = cert_manager_values_yaml();
        assert!(y.contains("prometheus:"), "{y}");
        assert!(y.contains("enabled: false"), "{y}");
    }
}
