// SPDX-License-Identifier: FSL-1.1-MIT
//! Tier-1 Helm values for the Cilium chart.
//!
//! Pure string composition. The CLI writes the result to a
//! tempfile and passes that path to `helm upgrade --install`.

/// Helm values YAML for a single-node k3s cluster. Picks
/// kube-proxy replacement (so k3s doesn't need kube-proxy), the
/// Kubernetes IPAM mode (k3s exposes pod CIDR via the Node API),
/// disables Hubble (extra observability is over-budget for tier-1),
/// and pins one operator replica because there is exactly one node.
pub fn cilium_values_yaml() -> String {
    r#"# Generated by AppRafter — see cli-providers::k8s::cilium_values.
kubeProxyReplacement: true
k8sServiceHost: "127.0.0.1"
k8sServicePort: 6443
ipam:
  mode: kubernetes
hubble:
  enabled: false
operator:
  replicas: 1
"#
    .to_string()
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn declares_kube_proxy_replacement_true() {
        let y = cilium_values_yaml();
        assert!(y.contains("kubeProxyReplacement: true"), "{y}");
    }

    #[test]
    fn points_k8s_service_at_loopback_6443_for_k3s() {
        let y = cilium_values_yaml();
        assert!(y.contains("k8sServiceHost: \"127.0.0.1\""), "{y}");
        assert!(y.contains("k8sServicePort: 6443"), "{y}");
    }

    #[test]
    fn ipam_mode_is_kubernetes() {
        let y = cilium_values_yaml();
        assert!(y.contains("ipam:"), "{y}");
        assert!(y.contains("mode: kubernetes"), "{y}");
    }

    #[test]
    fn hubble_is_disabled_on_tier_1() {
        let y = cilium_values_yaml();
        assert!(y.contains("hubble:"), "{y}");
        assert!(y.contains("enabled: false"), "{y}");
    }

    #[test]
    fn operator_pinned_to_one_replica() {
        let y = cilium_values_yaml();
        assert!(y.contains("operator:"), "{y}");
        assert!(y.contains("replicas: 1"), "{y}");
    }
}
