// SPDX-License-Identifier: FSL-1.1-MIT
//! Generators for cert-manager `ClusterIssuer` manifests.
//!
//! Tier-1 baseline: a single self-signed `ClusterIssuer` named
//! `apprafter-selfsigned`. Future cycles add LetsEncrypt
//! (HTTP-01 / DNS-01) issuers when we have real domains to
//! validate against.

/// Cluster-scoped name of the self-signed ClusterIssuer that
/// AppRafter pins. HTTPRoute / Certificate manifests reference
/// this name, so it lives as a `pub const` rather than a magic
/// string.
pub const APPRAFTER_SELFSIGNED_ISSUER: &str = "apprafter-selfsigned";

/// Cluster-side YAML for a self-signed cert-manager
/// `ClusterIssuer`. Carries the apprafter=true label so it lines
/// up with the rest of the resources we manage.
pub fn selfsigned_cluster_issuer_yaml() -> String {
    format!(
        r#"# Generated by AppRafter — see cli-providers::k8s::issuer.
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: {APPRAFTER_SELFSIGNED_ISSUER}
  labels:
    apprafter: "true"
spec:
  selfSigned: {{}}
"#
    )
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn header_pins_kind_and_apiversion() {
        let y = selfsigned_cluster_issuer_yaml();
        assert!(y.contains("apiVersion: cert-manager.io/v1"), "{y}");
        assert!(y.contains("kind: ClusterIssuer"), "{y}");
    }

    #[test]
    fn metadata_includes_apprafter_label_and_pinned_name() {
        let y = selfsigned_cluster_issuer_yaml();
        assert!(
            y.contains(&format!("name: {APPRAFTER_SELFSIGNED_ISSUER}")),
            "{y}"
        );
        assert!(y.contains("apprafter: \"true\""), "{y}");
    }

    #[test]
    fn spec_uses_selfsigned_provider() {
        let y = selfsigned_cluster_issuer_yaml();
        assert!(y.contains("selfSigned: {}"), "{y}");
    }
}
