// SPDX-License-Identifier: FSL-1.1-MIT
//! Generators for cluster-side `NetworkPolicy` manifests.
//!
//! Tier-1 baseline: a deny-all policy on the `default` namespace
//! (kube-system is exempt — those are Cilium / Gateway API system
//! pods that need free egress). Future cycles will hook into the
//! Application operator to mint per-namespace policies as workloads
//! are created.

/// Cluster-side YAML for a NetworkPolicy that denies all ingress
/// AND egress on every pod in `namespace`. AppRafter applications
/// land in `default` in tier-1 and add explicit allow-rules per
/// app via the operator (phase 1.8).
pub fn default_deny_network_policy_yaml(namespace: &str) -> String {
    format!(
        r#"# Generated by AppRafter — see cli-providers::k8s::network_policy.
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: default-deny
  namespace: {namespace}
  labels:
    apprafter: "true"
spec:
  podSelector: {{}}
  policyTypes:
    - Ingress
    - Egress
"#
    )
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn header_pins_kind_and_apiversion() {
        let y = default_deny_network_policy_yaml("default");
        assert!(y.contains("apiVersion: networking.k8s.io/v1"), "{y}");
        assert!(y.contains("kind: NetworkPolicy"), "{y}");
    }

    #[test]
    fn metadata_includes_namespace_and_apprafter_label() {
        let y = default_deny_network_policy_yaml("apps");
        assert!(y.contains("namespace: apps"), "{y}");
        assert!(y.contains("apprafter: \"true\""), "{y}");
        assert!(y.contains("name: default-deny"), "{y}");
    }

    #[test]
    fn pod_selector_targets_every_pod_in_the_namespace() {
        let y = default_deny_network_policy_yaml("default");
        assert!(y.contains("podSelector: {}"), "{y}");
    }

    #[test]
    fn policy_types_cover_both_ingress_and_egress() {
        let y = default_deny_network_policy_yaml("default");
        assert!(y.contains("- Ingress"), "{y}");
        assert!(y.contains("- Egress"), "{y}");
    }
}
