// SPDX-License-Identifier: FSL-1.1-MIT
//! Generators for cluster-side `NetworkPolicy` manifests.
//!
//! Tier-1 baseline: deny ingress from **other** namespaces while
//! allowing same-namespace pod-to-pod (Service routing) and
//! kube-system traffic (Cilium gateway, HTTPRoute backends,
//! monitoring; kubelet reaches via host-network and is unaffected
//! by NP at all). Egress is unrestricted — phase 2.10 (`needs` →
//! NetworkPolicy auto-derivation) will mint per-app egress allows
//! based on declared service dependencies once `ServiceProvider`
//! / `ResourceClaim` ship.
//!
//! The previous (v0.1.0-mvp through v0.1.50) shape was
//! `policyTypes: [Ingress, Egress]` with **no** allow rules,
//! which silently broke every workload in the namespace: pods
//! looked Running because `readinessProbe` traffic comes from
//! kubelet (host-network, exempt from NP), but Service routing
//! and DNS resolution were both blocked. Fixed in v0.1.51.

/// Cluster-side YAML for a tier-1 baseline NetworkPolicy.
///
/// Selects every pod in `namespace` and allows ingress from:
/// - any pod in the SAME namespace (intra-app Service routing,
///   curl pod → backend pod, etc.);
/// - any pod in the `kube-system` namespace (Cilium gateway pods
///   forwarding HTTPRoute traffic, future-tier-2 monitoring
///   scrapes, controllers reaching workloads).
///
/// All other ingress (e.g. from a future tier-2 multi-tenant
/// `apps-*` namespace, or an attacker who tunnels into another
/// namespace) is denied. Egress is **not** restricted: tier-1 is
/// single-tenant and the operator doesn't yet auto-derive
/// per-app egress allows; restricting egress without those
/// allows would re-introduce the v0.1.50 silent-breakage bug.
pub fn default_deny_network_policy_yaml(namespace: &str) -> String {
    format!(
        r#"# Generated by AppRafter — see cli-providers::k8s::network_policy.
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: default-deny
  namespace: {namespace}
  labels:
    apprafter: "true"
spec:
  podSelector: {{}}
  policyTypes:
    - Ingress
  ingress:
    # Same-namespace pod-to-pod (Service routing).
    - from:
        - podSelector: {{}}
    # kube-system (Cilium gateway, HTTPRoute backends, monitoring).
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: kube-system
"#
    )
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn header_pins_kind_and_apiversion() {
        let y = default_deny_network_policy_yaml("default");
        assert!(y.contains("apiVersion: networking.k8s.io/v1"), "{y}");
        assert!(y.contains("kind: NetworkPolicy"), "{y}");
    }

    #[test]
    fn metadata_includes_namespace_and_apprafter_label() {
        let y = default_deny_network_policy_yaml("apps");
        assert!(y.contains("namespace: apps"), "{y}");
        assert!(y.contains("apprafter: \"true\""), "{y}");
        assert!(y.contains("name: default-deny"), "{y}");
    }

    #[test]
    fn pod_selector_targets_every_pod_in_the_namespace() {
        let y = default_deny_network_policy_yaml("default");
        assert!(y.contains("podSelector: {}"), "{y}");
    }

    #[test]
    fn enforces_ingress_only_egress_unrestricted() {
        let y = default_deny_network_policy_yaml("default");
        assert!(
            y.contains("- Ingress"),
            "policyTypes must include Ingress (deny external ingress is the entire point of this NP):\n{y}"
        );
        assert!(
            !y.contains("- Egress"),
            "policyTypes must NOT include Egress — egress restriction without per-app egress allows (phase 2.10) silently breaks every workload's DNS + Service routing (the v0.1.50 → v0.1.51 fix):\n{y}"
        );
    }

    #[test]
    fn allows_same_namespace_pod_to_pod() {
        let y = default_deny_network_policy_yaml("default");
        // Allow rule is a podSelector with empty matchLabels →
        // any pod in this namespace.
        assert!(
            y.contains("- podSelector: {}"),
            "must allow same-namespace ingress so Service routing works:\n{y}"
        );
    }

    #[test]
    fn allows_ingress_from_kube_system_namespace() {
        let y = default_deny_network_policy_yaml("default");
        assert!(
            y.contains("kubernetes.io/metadata.name: kube-system"),
            "must allow ingress from kube-system so Cilium gateway / HTTPRoute / monitoring can reach default-ns pods:\n{y}"
        );
    }
}
