// SPDX-License-Identifier: FSL-1.1-Apache-2.0
//! Tier-1 Helm values for `operator/charts/apprafter-operator/`.
//!
//! Pure string composition. `cluster-bootstrap` writes the result
//! to a tempfile and passes it as `--values <file>` to
//! `helm upgrade --install apprafter-operator`. Only the image
//! repository + tag are overridden; everything else (replicaCount,
//! resources, security context) stays at chart defaults.

/// Helm values YAML overriding the operator chart's
/// `image.repository` and `image.tag`. The image arguments come
/// from [`crate::k8s::resolve_image_ref`] so the operator and
/// admission-webhook references are composed identically.
pub fn operator_values_yaml(image_repo: &str, image_tag: &str) -> String {
    format!(
        r#"# SPDX-License-Identifier: MIT
# Generated by AppRafter — see cli-providers::k8s::operator_values.
image:
  repository: {image_repo}
  tag: {image_tag}
"#
    )
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn yaml_overrides_repository_and_tag() {
        let y = operator_values_yaml("ghcr.io/apprafter/apprafter-operator", "v0.1.64");
        assert!(
            y.contains("repository: ghcr.io/apprafter/apprafter-operator"),
            "{y}"
        );
        assert!(y.contains("tag: v0.1.64"), "{y}");
    }

    #[test]
    fn yaml_carries_spdx_comment() {
        let y = operator_values_yaml("ghcr.io/x/y", "v1");
        assert!(y.starts_with("# SPDX-License-Identifier: MIT"), "{y}");
    }

    #[test]
    fn yaml_does_not_override_replicacount_or_resources() {
        // Anything we do NOT override stays at chart defaults so
        // operators can `helm upgrade` later without surprises.
        let y = operator_values_yaml("ghcr.io/x/y", "v1");
        assert!(!y.contains("replicaCount"), "{y}");
        assert!(!y.contains("resources:"), "{y}");
        assert!(!y.contains("logLevel"), "{y}");
    }
}
