// SPDX-License-Identifier: FSL-1.1-Apache-2.0
//! Pure restic argv builders and passphrase resolution.
//!
//! The passphrase is NEVER passed on argv — it is always injected via the
//! `RESTIC_PASSWORD` environment variable at call time by the invoking layer.

/// `restic init` argv (RESTIC_PASSWORD passed via env, never argv).
pub fn restic_init_argv(repo: &str) -> Vec<String> {
    vec!["init".into(), "--repo".into(), repo.into()]
}

/// `restic backup` argv: snapshot the staging dir into the repo, tagged.
/// `--json` is included so the caller can parse the structured summary line.
///
/// `host`: when `Some(h)`, passes `--host h` so `restic forget` groups
/// snapshots by a fixed, stable host rather than the pod/machine name — a
/// requirement for retention policies (spec §Retention M-r3-1a). Pass `None`
/// for local-pull / CLI paths where the machine's own hostname is correct.
pub fn restic_backup_argv(
    repo: &str,
    staging_dir: &str,
    tag: &str,
    host: Option<&str>,
) -> Vec<String> {
    let mut argv = vec![
        "backup".into(),
        "--repo".into(),
        repo.into(),
        "--tag".into(),
        tag.into(),
        "--json".into(),
    ];
    if let Some(h) = host {
        argv.push("--host".into());
        argv.push(h.into());
    }
    argv.push(staging_dir.into());
    argv
}

/// `restic snapshots --json` argv.
pub fn restic_snapshots_argv(repo: &str) -> Vec<String> {
    vec![
        "snapshots".into(),
        "--repo".into(),
        repo.into(),
        "--json".into(),
    ]
}

/// `restic forget <ids...> --prune` argv (retention prune, spec §M-r3-1b).
///
/// Forgets an explicit set of snapshot ids (the run-aware planner in
/// [`crate::prune`] decides the set) and runs `--prune` to reclaim the space.
/// RESTIC_PASSWORD is passed via env, never argv.
pub fn restic_forget_argv(repo: &str, ids: &[String]) -> Vec<String> {
    let mut argv = vec!["forget".into(), "--repo".into(), repo.into()];
    argv.extend(ids.iter().cloned());
    argv.push("--prune".into());
    argv
}

/// `restic restore <snapshot> --target <out>` argv.
pub fn restic_restore_argv(repo: &str, snapshot: &str, out: &str) -> Vec<String> {
    vec![
        "restore".into(),
        "--repo".into(),
        repo.into(),
        snapshot.into(),
        "--target".into(),
        out.into(),
    ]
}

/// `restic unlock` argv: removes only stale locks (restic's default behaviour —
/// no `--remove-all` flag, which would also kill live locks held by concurrent
/// backup runs).
pub fn restic_unlock_argv(repo: &str) -> Vec<String> {
    vec!["unlock".into(), "--repo".into(), repo.into()]
}

/// Passphrase precedence: explicit arg → env. Returns None when neither is set
/// (the caller then prompts on a TTY, or errors on non-TTY — the repo holds
/// decrypted secrets so an empty passphrase is NEVER allowed). The resolved
/// passphrase is passed to restic via the RESTIC_PASSWORD env at call time,
/// never on argv.
pub fn resolve_passphrase(arg: Option<&str>, env: Option<&str>) -> Option<String> {
    arg.or(env).map(str::to_string)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn backup_argv_targets_repo_and_tag() {
        // tag is opaque to argv here — generated by backup_tag() (T9) as
        // cluster-id + timestamp, NOT namespace-based.
        let a = restic_backup_argv("/repo", "/stage", "k3d-demo-2026-06-20T00:00:00Z", None);
        assert_eq!(a[0], "backup");
        assert!(a.contains(&"--repo".to_string()));
        assert!(a.contains(&"/repo".to_string()));
        assert!(a.contains(&"--tag".to_string()));
        assert!(a.contains(&"k3d-demo-2026-06-20T00:00:00Z".to_string()));
        assert!(a.contains(&"/stage".to_string()));
        assert!(a.contains(&"--json".to_string()));
    }

    #[test]
    fn backup_argv_sets_fixed_host_when_given_one() {
        let a = restic_backup_argv("s3:repo", "/stage", "tag", Some("apprafter-backup"));
        let i = a
            .iter()
            .position(|x| x == "--host")
            .expect("--host present");
        assert_eq!(a[i + 1], "apprafter-backup");
    }

    #[test]
    fn backup_argv_omits_host_when_none_for_local_pull() {
        let a = restic_backup_argv("/local/repo", "/stage", "tag", None);
        assert!(
            !a.iter().any(|x| x == "--host"),
            "local-pull must NOT set --host (uses machine hostname): {a:?}"
        );
    }

    #[test]
    fn init_argv_and_restore_argv() {
        assert_eq!(restic_init_argv("/repo")[0], "init");
        let r = restic_restore_argv("/repo", "latest", "/out");
        assert_eq!(r[0], "restore");
        assert!(r.contains(&"latest".to_string()));
        assert!(r.windows(2).any(|w| w == ["--target", "/out"]));
    }

    #[test]
    fn forget_argv_lists_ids_and_prunes() {
        let ids = vec!["aaaa".to_string(), "bbbb".to_string()];
        let a = restic_forget_argv("s3:repo", &ids);
        assert_eq!(a[0], "forget");
        assert!(a.windows(2).any(|w| w == ["--repo", "s3:repo"]));
        assert!(a.contains(&"aaaa".to_string()));
        assert!(a.contains(&"bbbb".to_string()));
        assert_eq!(a.last(), Some(&"--prune".to_string()));
        // ids come before --prune (restic parses positional ids, then the flag).
        let prune_i = a.iter().position(|x| x == "--prune").unwrap();
        assert!(a.iter().position(|x| x == "aaaa").unwrap() < prune_i);
    }

    #[test]
    fn forget_argv_with_no_ids_is_still_well_formed() {
        let a = restic_forget_argv("/repo", &[]);
        assert_eq!(a, vec!["forget", "--repo", "/repo", "--prune"]);
    }

    #[test]
    fn unlock_argv_targets_repo_and_removes_only_stale() {
        let a = restic_unlock_argv("s3:repo");
        assert_eq!(a[0], "unlock");
        assert!(a.iter().any(|x| x == "--repo") && a.iter().any(|x| x == "s3:repo"));
        assert!(
            !a.iter().any(|x| x == "--remove-all"),
            "must NOT remove live locks"
        );
    }

    #[test]
    fn passphrase_precedence_arg_then_env_then_none() {
        assert_eq!(
            resolve_passphrase(Some("p1"), Some("p2")),
            Some("p1".to_string())
        );
        assert_eq!(resolve_passphrase(None, Some("p2")), Some("p2".to_string()));
        assert_eq!(resolve_passphrase(None, None), None);
    }
}
