// SPDX-License-Identifier: FSL-1.1-Apache-2.0
//! Pure restic argv builders and passphrase resolution.
//!
//! The passphrase is NEVER passed on argv — it is always injected via the
//! `RESTIC_PASSWORD` environment variable at call time by the invoking layer.

/// `restic init` argv (RESTIC_PASSWORD passed via env, never argv).
pub fn restic_init_argv(repo: &str) -> Vec<String> {
    vec!["init".into(), "--repo".into(), repo.into()]
}

/// `restic backup` argv: snapshot the staging dir into the repo, tagged.
/// `--json` is included so the caller can parse the structured summary line.
pub fn restic_backup_argv(repo: &str, staging_dir: &str, tag: &str) -> Vec<String> {
    vec![
        "backup".into(),
        "--repo".into(),
        repo.into(),
        "--tag".into(),
        tag.into(),
        "--json".into(),
        staging_dir.into(),
    ]
}

/// `restic snapshots --json` argv.
pub fn restic_snapshots_argv(repo: &str) -> Vec<String> {
    vec![
        "snapshots".into(),
        "--repo".into(),
        repo.into(),
        "--json".into(),
    ]
}

/// `restic restore <snapshot> --target <out>` argv.
pub fn restic_restore_argv(repo: &str, snapshot: &str, out: &str) -> Vec<String> {
    vec![
        "restore".into(),
        "--repo".into(),
        repo.into(),
        snapshot.into(),
        "--target".into(),
        out.into(),
    ]
}

/// Passphrase precedence: explicit arg → env. Returns None when neither is set
/// (the caller then prompts on a TTY, or errors on non-TTY — the repo holds
/// decrypted secrets so an empty passphrase is NEVER allowed). The resolved
/// passphrase is passed to restic via the RESTIC_PASSWORD env at call time,
/// never on argv.
pub fn resolve_passphrase(arg: Option<&str>, env: Option<&str>) -> Option<String> {
    arg.or(env).map(str::to_string)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn backup_argv_targets_repo_and_tag() {
        // tag is opaque to argv here — generated by backup_tag() (T9) as
        // cluster-id + timestamp, NOT namespace-based.
        let a = restic_backup_argv("/repo", "/stage", "k3d-demo-2026-06-20T00:00:00Z");
        assert_eq!(a[0], "backup");
        assert!(a.contains(&"--repo".to_string()));
        assert!(a.contains(&"/repo".to_string()));
        assert!(a.contains(&"--tag".to_string()));
        assert!(a.contains(&"k3d-demo-2026-06-20T00:00:00Z".to_string()));
        assert!(a.contains(&"/stage".to_string()));
        assert!(a.contains(&"--json".to_string()));
    }

    #[test]
    fn init_argv_and_restore_argv() {
        assert_eq!(restic_init_argv("/repo")[0], "init");
        let r = restic_restore_argv("/repo", "latest", "/out");
        assert_eq!(r[0], "restore");
        assert!(r.contains(&"latest".to_string()));
        assert!(r.windows(2).any(|w| w == ["--target", "/out"]));
    }

    #[test]
    fn passphrase_precedence_arg_then_env_then_none() {
        assert_eq!(
            resolve_passphrase(Some("p1"), Some("p2")),
            Some("p1".to_string())
        );
        assert_eq!(resolve_passphrase(None, Some("p2")), Some("p2".to_string()));
        assert_eq!(resolve_passphrase(None, None), None);
    }
}
