// SPDX-License-Identifier: FSL-1.1-Apache-2.0
//! Compile-time extraction of CLI loader values from the
//! platform-stack chart's CUE source. Emits a Rust file at
//! `OUT_DIR/loader_values.rs` containing one `pub const &str`
//! per `_loaderValues.<component>` field. The crate's
//! `src/k8s/loader_values.rs` `include!`s that file and
//! re-exports the constants.
//!
//! Why a build script: the chart's CUE is the single source
//! of truth for what Cilium + Argo CD get installed with.
//! Hardcoding the same YAML in Rust would re-introduce the
//! walk-fix #6 drift class (chart's `k8sServiceHost: "auto"`
//! vs loader's `"127.0.0.1"`). build.rs eliminates the
//! duplication structurally.
//!
//! Requires `cue` (v0.10+) on PATH at build time, or `nix`
//! with `nixpkgs#cue` available. Falls back to `nix run` if
//! the bare binary is missing, matching `scripts/lint-cue.sh`'s
//! behaviour.

use std::env;
use std::path::{Path, PathBuf};
use std::process::{Command, Stdio};

fn main() {
    let manifest_dir = PathBuf::from(env::var("CARGO_MANIFEST_DIR").unwrap());
    let chart_root = manifest_dir.join("../../platform-stack/cue");

    let operator_chart_yaml =
        manifest_dir.join("../../operator/charts/apprafter-operator/Chart.yaml");
    let webhook_chart_yaml =
        manifest_dir.join("../../operator/charts/apprafter-admission-webhook/Chart.yaml");

    println!("cargo:rerun-if-changed={}", chart_root.display());
    println!("cargo:rerun-if-changed=build.rs");
    println!("cargo:rerun-if-changed={}", operator_chart_yaml.display());
    println!("cargo:rerun-if-changed={}", webhook_chart_yaml.display());

    let cilium_yaml = cue_export(&chart_root, "_loaderValues.cilium.values");
    let argocd_yaml = cue_export(&chart_root, "_loaderValues.argocd.values");
    let cilium_chart_version = cue_export_string(&chart_root, "_loaderValues.cilium.chartVersion");
    let argocd_chart_version = cue_export_string(&chart_root, "_loaderValues.argocd.chartVersion");
    let platform_stack_version = cue_export_string(&chart_root, "currentVersion");

    let operator_app_version = read_chart_field(&operator_chart_yaml, "appVersion");
    let webhook_app_version = read_chart_field(&webhook_chart_yaml, "appVersion");

    assert_eq!(
        operator_app_version, webhook_app_version,
        "operator + admission-webhook charts must ship the same appVersion \
         (operator: {operator_app_version}, webhook: {webhook_app_version}) — \
         they're built together by release-operator.yml"
    );

    let released_operator_version = operator_app_version;

    let out_dir = PathBuf::from(env::var("OUT_DIR").unwrap());
    let out_file = out_dir.join("loader_values.rs");

    let contents = format!(
        "// Auto-generated by cli-providers/build.rs from platform-stack/cue/.\n\
         // Do not edit. Modify `platform-stack/cue/` instead.\n\
         pub const CILIUM_VALUES_YAML: &str = {cilium_yaml:?};\n\
         pub const ARGOCD_LOADER_VALUES_YAML: &str = {argocd_yaml:?};\n\
         pub const CILIUM_CHART_VERSION: &str = {cilium_chart_version:?};\n\
         pub const ARGOCD_CHART_VERSION: &str = {argocd_chart_version:?};\n\
         pub const RELEASED_PLATFORM_STACK_VERSION: &str = {platform_stack_version:?};\n\
         pub const RELEASED_OPERATOR_VERSION: &str = {released_operator_version:?};\n",
        cilium_yaml = cilium_yaml,
        argocd_yaml = argocd_yaml,
        cilium_chart_version = cilium_chart_version,
        argocd_chart_version = argocd_chart_version,
        platform_stack_version = platform_stack_version,
        released_operator_version = released_operator_version,
    );

    std::fs::write(&out_file, contents)
        .unwrap_or_else(|e| panic!("write {}: {e}", out_file.display()));
}

/// Run `cue export -e <expr> --out yaml` against `chart_root`.
/// Tries the bare `cue` binary first; on `not found` falls
/// back to `nix run nixpkgs#cue --`. Panics with a clear
/// error if both routes fail.
fn cue_export(chart_root: &PathBuf, expr: &str) -> String {
    let try_bare = Command::new("cue")
        .args(["export", "-e", expr, "--out", "yaml", "./..."])
        .current_dir(chart_root)
        .stdin(Stdio::null())
        .output();

    let out = match try_bare {
        Ok(o) => o,
        Err(_) => Command::new("nix")
            .args([
                "run",
                "nixpkgs#cue",
                "--",
                "export",
                "-e",
                expr,
                "--out",
                "yaml",
                "./...",
            ])
            .current_dir(chart_root)
            .stdin(Stdio::null())
            .output()
            .expect(
                "cli-providers/build.rs: neither `cue` nor `nix run nixpkgs#cue` is on PATH. \
                 Install cue (v0.10+) or run the build under `nix develop`.",
            ),
    };

    if !out.status.success() {
        panic!(
            "cue export -e {expr} failed (exit {:?}):\nstdout: {}\nstderr: {}",
            out.status.code(),
            String::from_utf8_lossy(&out.stdout),
            String::from_utf8_lossy(&out.stderr),
        );
    }

    String::from_utf8(out.stdout).expect("cue export emitted non-utf8")
}

/// Like `cue_export` but expects a scalar string field; trims
/// surrounding YAML quoting + whitespace before returning.
/// `cue export -e <scalar>` emits something like `0.1.12\n` or
/// `"0.1.12"\n` depending on whether the scalar is a string or
/// number-looking string.
fn cue_export_string(chart_root: &PathBuf, expr: &str) -> String {
    let raw = cue_export(chart_root, expr);
    raw.trim().trim_matches('"').trim_matches('\'').to_string()
}

/// Read a top-level scalar string field from a Helm Chart.yaml
/// file via a minimal line-prefix grep. Helm chart manifests
/// keep `version:` and `appVersion:` as top-level keys in
/// flat YAML, so this avoids the cost of a full serde_yaml
/// dependency at build time. Trims surrounding whitespace +
/// optional `"..."` quoting.
fn read_chart_field(chart_yaml: &Path, field: &str) -> String {
    let content = std::fs::read_to_string(chart_yaml).unwrap_or_else(|e| {
        panic!(
            "cli-providers/build.rs: read {chart_yaml:?}: {e}. \
             Track B.1.71b moved the SoT for operator + webhook \
             image tags into these Chart.yaml files."
        );
    });
    let prefix = format!("{field}:");
    for line in content.lines() {
        let trimmed = line.trim_start();
        if let Some(rest) = trimmed.strip_prefix(&prefix) {
            return rest.trim().trim_matches('"').trim_matches('\'').to_string();
        }
    }
    panic!("cli-providers/build.rs: field {field:?} not found in {chart_yaml:?}");
}
