#!/usr/bin/env bash
# SPDX-License-Identifier: FSL-1.1-Apache-2.0
#
# check-payload-types.sh — fail if `landing/cms/payload-types.ts` differs from
# what `payload generate:types` produces, so the committed generated file
# cannot silently lag the collections and globals it is generated from.
#
# ## Why
#
# `landing/cms/payload-types.ts` is generated by Payload from
# `landing/cms/src/collections/**` and `landing/cms/src/globals/**`, and it is
# committed — `landing/web/src/lib/types.ts` imports it directly. Nothing
# regenerated it as part of any check and nothing compared it: before this
# script the repository had no gate, no hook and no CI step that read the file
# at all.
#
# So it lagged. `2abac0f` (2026-09-10) rewrote a field's admin description in
# `landing/cms/src/globals/LandingHero.ts` and left the mirrored JSDoc in
# `payload-types.ts` behind; it was found only because an unrelated change to
# `SiteSettings.ts` happened to regenerate the file and produced a third,
# unexplained hunk. Nobody was looking for it, and nothing would have looked.
#
# The failure mode worth naming is that a stale generated file COMPILES. It has
# every field the code touches and its types are right, so the site builds and
# deploys. What rots is the part no compiler reads — the JSDoc Payload copies
# out of each field's `admin.description`, which is the text an owner reads in
# the CMS admin before deciding what to type into a box. Nor is the type half
# actually guarded elsewhere: `landing/cms`'s `typecheck` (`tsc --noEmit`) does
# not reach this file, and the thing that does type-check it — `landing/web`'s
# `astro check` — is not run by any gate in this repository. Drift here is
# invisible to everything else, and it worsens monotonically, because each
# stale run makes the next diff noisier and easier to wave through.
#
# ## What it does
#
# Deletes the artefact, regenerates, and compares against the committed bytes,
# restoring the committed file on every exit path — a failing check never
# leaves a modified working tree, and never silently "fixes" the drift it
# found. Applying the fix is deliberate: `just payload-types`.
#
# The delete is not tidiness. Without it the comparison is `$OUT` against a
# byte-identical copy of itself whenever `typescript.outputFile` points
# somewhere else, and the gate passes green forever on a file nothing
# regenerates any more. Making the generator prove it wrote THIS path is the
# only thing that catches a moved output.
#
# `payload generate:types` compiles the schema and writes a file. It opens no
# database and needs no configuration values: `payload.config.ts` defaults both
# `PAYLOAD_SECRET` and `DATABASE_URL` to `''`, and running the generator with
# both forced empty produces byte-identical output. (Bun does auto-load
# `landing/cms/.env` on a `bun run` from that directory, and Payload's CLI
# calls Next's `loadEnvConfig` besides — so values may be present. Nothing on
# the generation path reads them.) Safe to run in CI with no secrets.
#
# ## Why there is no pre-commit hook for this
#
# Deliberate, and both alternatives were built and reproduced before being
# rejected. A local hook can only see the WORKING TREE, but a commit is the
# INDEX, and for a generated artefact the difference is not academic:
#
#   - Regenerate-and-stage (the shape the `docsgen` job uses) breaks under
#     `git commit -- <paths>`, `--only` and `--amend -- <paths>`: those run
#     hooks against a throwaway index (`.git/next-index-<pid>.lock`) that git
#     discards afterwards, so the `git add` reaches the commit but never the
#     real index. The artefact stays staged at its pre-hook bytes and the NEXT
#     plain commit silently reverts it — this gate's own hook reintroducing
#     exactly the drift it exists to prevent, between two clean commits.
#   - It also renders from the working tree. lefthook hides unstaged hunks only
#     for PARTIALLY staged files, so a sibling global that is modified but
#     wholly unstaged gets baked into the artefact and staged with it — content
#     in the commit that appears in no source file of that commit.
#   - Running THIS script from a hook inherits the same working-tree problem
#     from the other side: it reports drift for an unstaged sibling edit the
#     commit does not contain, and its advice ("run `just payload-types`")
#     walks the contributor straight into the case above.
#
# CI is where index, working tree and commit are the same thing, so that is
# where this runs — `.github/workflows/lint.yml`, the `payload-types drift`
# step. A correct local hook would have to render from the index (a temporary
# worktree, or `git stash --keep-index`), which is more machinery than the
# 30 seconds it saves.

set -euo pipefail

REPO_ROOT="$(git rev-parse --show-toplevel)"
cd "$REPO_ROOT"

# `git rev-parse` resolves from the CWD, not from where this script lives, so
# it happily lands in a DIFFERENT repository — and the "no landing/cms here"
# skip below would then report the same green as a real run. Two markers,
# because a `Justfile` alone is a weak discriminator.
if [ ! -f Justfile ] || [ ! -f cue.mod/module.cue ]; then
    echo "ERROR: $REPO_ROOT is not the apprafter repo root." >&2
    exit 1
fi

CMS="landing/cms"
OUT="$CMS/payload-types.ts"

# Conditional like every other target here: no workspace, nothing to check.
# This is the ONE skip, and it is structural — the directory is absent, so
# there is no committed artefact that could be stale.
if [ ! -f "$CMS/package.json" ]; then
    echo "==> no $CMS/package.json — skipping payload-types check"
    exit 0
fi

if [ ! -f "$OUT" ]; then
    echo "ERROR: $OUT is missing." >&2
    echo "       It is generated and committed. Run: just payload-types" >&2
    exit 1
fi

# Missing dependencies are a LOUD failure, not a skip. A check that quietly
# passes when it could not run reports the same green as one that ran, which is
# how the drift above survived in the first place.
#
# Both locations are accepted because where bun puts a workspace member's
# binary is bun's business, not ours: today it is the member's own
# `node_modules/.bin`, but a hoist to the workspace root would be an equally
# valid install and must not read as "dependencies missing".
if [ ! -x "$CMS/node_modules/.bin/payload" ] && [ ! -x "landing/node_modules/.bin/payload" ]; then
    echo "ERROR: the payload generator is not installed, so the generated types" >&2
    echo "       cannot be compared against their source." >&2
    echo "       Run: (cd $CMS && bun install)" >&2
    exit 1
fi

committed="$(mktemp)"
regenerated="$(mktemp)"
log="$(mktemp)"
cp "$OUT" "$committed"

# Restore on EVERY exit path, including the failure branches and an interrupt:
# the generator writes in place, and a gate must not mutate the tree it judges.
# All three temps are trap-managed — a cleanup that covers two of three is the
# kind of asymmetry that becomes a leak the first time someone hits Ctrl-C.
# The `cmp` guard keeps the success path from writing the file a SECOND time:
# the generator has already replaced it with identical bytes, and copying the
# copy back over that would be pure churn.
# shellcheck disable=SC2329  # invoked by the EXIT trap below, not by name.
restore() {
    cmp -s "$committed" "$OUT" 2>/dev/null || cp "$committed" "$OUT"
    rm -f "$committed" "$regenerated" "$log"
}
trap restore EXIT

# Make the generator prove it wrote THIS path — see the note above.
rm -f "$OUT"

if ! (cd "$CMS" && bun run generate:types) >"$log" 2>&1; then
    echo "ERROR: \`bun run generate:types\` failed in $CMS:" >&2
    cat "$log" >&2
    exit 1
fi

if [ ! -f "$OUT" ]; then
    echo "ERROR: the generator ran but did not write $OUT." >&2
    echo "       Check \`typescript.outputFile\` in $CMS/src/payload.config.ts;" >&2
    echo "       the freshly generated file is now at whatever path it names." >&2
    echo "       Moving the artefact takes four edits, not one: that config" >&2
    echo "       line, \`OUT=\` in this script, the biome ignore entry in" >&2
    echo "       landing/biome.json, and the import in" >&2
    echo "       landing/web/src/lib/types.ts." >&2
    exit 1
fi

if cmp -s "$committed" "$OUT"; then
    echo "OK: $OUT matches the collections and globals it is generated from."
    exit 0
fi

cp "$OUT" "$regenerated"
echo "ERROR: $OUT is stale — it does not match what Payload generates from" >&2
echo "       $CMS/src/{collections,globals}/**." >&2
echo >&2
diff -u --label "committed/$OUT" --label "generated/$OUT" \
    "$committed" "$regenerated" >&2 || true
echo >&2
echo "       Fix: just payload-types    (then commit the result)" >&2
exit 1
