// SPDX-License-Identifier: FSL-1.1-Apache-2.0
//! kube-rs CRD types for v1alpha1 `ResourceClaim`.
//!
//! Mirrors the OpenAPI v3 CRD shipped in
//! `operator/charts/apprafter-operator/templates/crd-resourceclaim.yaml`
//! and `schemas/v1alpha1/resourceclaim.cue`. Namespaced; generated by
//! the Application operator (2.4) — never hand-authored (the admission
//! webhook rejects user CREATE).

use std::collections::BTreeMap;

use kube::CustomResource;
use schemars::JsonSchema;
use serde::{Deserialize, Serialize};

#[derive(CustomResource, Clone, Debug, Default, Deserialize, Serialize, JsonSchema, PartialEq)]
#[kube(
    group = "apprafter.io",
    version = "v1alpha1",
    kind = "ResourceClaim",
    namespaced,
    status = "ResourceClaimStatus"
)]
pub struct ResourceClaimSpec {
    /// Built-in service type (closed enum; see `schemas/v1alpha1`).
    #[serde(rename = "type")]
    pub type_: String,
    /// Label selector matched against ServiceProvider `metadata.labels`
    /// by the 2.3 scheduler.
    pub selector: BTreeMap<String, String>,
    /// Requested size (closed set; see `#Size`).
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub size: Option<String>,
}

#[derive(Clone, Debug, Default, Deserialize, Serialize, JsonSchema, PartialEq)]
pub struct ResourceClaimStatus {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub provider: Option<String>,
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        rename = "connectionSecretRef"
    )]
    pub connection_secret_ref: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub ready: Option<bool>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub conditions: Option<Vec<ResourceClaimCondition>>,
}

#[derive(Clone, Debug, Deserialize, Serialize, JsonSchema, PartialEq)]
pub struct ResourceClaimCondition {
    #[serde(rename = "type")]
    pub type_: String,
    pub status: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub reason: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub message: Option<String>,
    #[serde(rename = "lastTransitionTime")]
    pub last_transition_time: String,
}

#[cfg(test)]
mod tests {
    use super::*;
    use serde_json::json;

    #[test]
    fn deserializes_spec_with_type_rename_and_selector() {
        let spec: ResourceClaimSpec = serde_json::from_value(json!({
            "type": "pg",
            "selector": { "tier": "integrated" },
            "size": "small"
        }))
        .expect("valid spec");
        assert_eq!(spec.type_, "pg");
        assert_eq!(
            spec.selector.get("tier").map(String::as_str),
            Some("integrated")
        );
        assert_eq!(spec.size.as_deref(), Some("small"));
    }

    #[test]
    fn size_is_optional_and_type_serializes_back() {
        let spec = ResourceClaimSpec {
            type_: "redis".into(),
            selector: BTreeMap::from([("tier".to_string(), "integrated".to_string())]),
            size: None,
        };
        let v = serde_json::to_value(&spec).unwrap();
        assert_eq!(v.get("type"), Some(&json!("redis")));
        assert!(v.get("size").is_none());
    }

    #[test]
    fn status_conditions_and_renames_round_trip() {
        let status: ResourceClaimStatus = serde_json::from_value(json!({
            "provider": "pg-integrated",
            "connectionSecretRef": "demo-web-pg-conn",
            "ready": true,
            "conditions": [{
                "type": "Ready",
                "status": "True",
                "lastTransitionTime": "2026-06-02T00:00:00Z"
            }]
        }))
        .unwrap();
        assert_eq!(
            status.connection_secret_ref.as_deref(),
            Some("demo-web-pg-conn")
        );
        let c = &status.conditions.unwrap()[0];
        assert_eq!(c.type_, "Ready");
        assert_eq!(c.last_transition_time, "2026-06-02T00:00:00Z");
    }
}
