// SPDX-License-Identifier: FSL-1.1-Apache-2.0
//! kube-rs CRD types for v1alpha1 `ResourceClaim`.
//!
//! Mirrors the OpenAPI v3 CRD shipped in
//! `operator/charts/apprafter-operator/templates/crd-resourceclaim.yaml`
//! and `schemas/v1alpha1/resourceclaim.cue`. Namespaced; generated by
//! the Application operator (2.4) — never hand-authored (the admission
//! webhook rejects user CREATE).

use std::collections::BTreeMap;

use kube::CustomResource;
use schemars::JsonSchema;
use serde::{Deserialize, Serialize};

#[derive(CustomResource, Clone, Debug, Default, Deserialize, Serialize, JsonSchema, PartialEq)]
#[kube(
    group = "apprafter.io",
    version = "v1alpha1",
    kind = "ResourceClaim",
    namespaced,
    status = "ResourceClaimStatus"
)]
pub struct ResourceClaimSpec {
    /// Built-in service type (closed enum; see `schemas/v1alpha1`).
    #[serde(rename = "type")]
    pub type_: String,
    /// `(type, name)` claim identity (2.6b / ADR 0043). Set by the
    /// Application controller from a named `needs.<type>[].name` entry so
    /// the provisioner derives distinct DBs/users/connection-Secrets for
    /// sibling claims of one app. Absent for the unnamed default claim.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    /// Label selector matched against ServiceProvider `metadata.labels`
    /// by the 2.3 scheduler.
    pub selector: BTreeMap<String, String>,
    /// Requested size (closed set; see `#Size`).
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub size: Option<String>,
    /// Persist the provisioned resource across the claim's deletion
    /// (default false). Copied from the originating `needs.<type>.persistent`
    /// by the Application controller (2.4d); the dragonfly provisioner reads
    /// it to route to a persistent vs ephemeral pool instance (ADR 0042).
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub persistent: Option<bool>,
}

/// How much data a claim holds (2.22d / D8).
///
/// Two fields because two backends can honestly answer different questions,
/// and forcing one unit would mean inventing a number. Postgres reports
/// BYTES — `cnpg_pg_database_size_bytes` is a default CNPG metric. Dragonfly
/// reports KEYS: per-DB byte accounting exists inside the server but every
/// emission site sums across databases first, and the only ways to bytes are
/// per-key `MEMORY USAGE` or `DEBUG OBJHIST`, which walk the keyspace on
/// shared shard threads and mix tenants respectively.
#[derive(Clone, Debug, Default, Deserialize, Serialize, JsonSchema, PartialEq)]
pub struct ClaimSize {
    /// On-disk bytes. Postgres only.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub bytes: Option<i64>,
    /// Key count. Redis only — NOT bytes, and the CLI must say so.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub keys: Option<i64>,
    /// RFC3339 time of the sample, so a stale figure is visibly stale.
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        rename = "measuredAt"
    )]
    pub measured_at: Option<String>,
}

/// Bytes used and available on the volume backing a `disk` claim
/// (2.22d / D8).
#[derive(Clone, Debug, Default, Deserialize, Serialize, JsonSchema, PartialEq)]
pub struct ClaimCapacity {
    #[serde(rename = "usedBytes")]
    pub used_bytes: i64,
    #[serde(rename = "capacityBytes")]
    pub capacity_bytes: i64,
    /// WHICH THING these bytes measure (D29): `"volume"` when the backend
    /// enforces a real quota and reports it, `"host"` when the figures are the
    /// backing filesystem's — which is what the kubelet returns for a
    /// local-path volume, because a directory on a shared disk has no quota to
    /// report against.
    ///
    /// Optional so a claim last written by an operator that predates the field
    /// still deserialises; readers treat the absence as "unknown" and fall
    /// back to the pre-D29 rendering rather than guessing.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub scope: Option<String>,
}

#[derive(Clone, Debug, Default, Deserialize, Serialize, JsonSchema, PartialEq)]
pub struct ResourceClaimStatus {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub provider: Option<String>,
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        rename = "connectionSecretRef"
    )]
    pub connection_secret_ref: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub ready: Option<bool>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub conditions: Option<Vec<ResourceClaimCondition>>,
    /// Dragonfly allocation: the shared pool instance this claim's DB
    /// lives on (ADR 0042). None for non-pooled backends (e.g. CNPG).
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub instance: Option<String>,
    /// Dragonfly allocation: the numbered logical DB (`$N`) assigned to
    /// this claim on `instance` (0..1023). None for non-pooled backends.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub dbnum: Option<u16>,
    /// Disk allocation (2.6b): the standalone RWO PVC name created by the
    /// `Backend::Disk` provisioner. The renderer mounts this PVC into the
    /// workload. None for non-disk backends (parallel to `connectionSecretRef`).
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        rename = "volumeClaimRef"
    )]
    pub volume_claim_ref: Option<String>,
    /// Used and total bytes of the volume backing this claim (2.22d / D8).
    ///
    /// Set for `disk` claims only, and deliberately so. An owned disk has
    /// its OWN PVC and therefore its own denominator, which makes a
    /// fraction meaningful. A `pg` or `redis` claim lives on a SHARED
    /// backend, where a per-tenant number has no per-tenant limit to be
    /// measured against — the actionable figure there is the backend's own
    /// fullness, not the tenant's slice of it.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub capacity: Option<ClaimCapacity>,
    /// How much data this claim holds (2.22d / D8) — the "how big is my
    /// database" question, which is separate from "how full is the disk"
    /// and useful without a denominator: it sizes a backup, shows growth
    /// and explains cost.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub size: Option<ClaimSize>,
}

#[derive(Clone, Debug, Deserialize, Serialize, JsonSchema, PartialEq)]
pub struct ResourceClaimCondition {
    #[serde(rename = "type")]
    pub type_: String,
    pub status: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub reason: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub message: Option<String>,
    #[serde(rename = "lastTransitionTime")]
    pub last_transition_time: String,
}

#[cfg(test)]
mod tests {
    use super::*;
    use serde_json::json;

    #[test]
    fn deserializes_spec_with_type_rename_and_selector() {
        let spec: ResourceClaimSpec = serde_json::from_value(json!({
            "type": "pg",
            "selector": { "tier": "integrated" },
            "size": "small"
        }))
        .expect("valid spec");
        assert_eq!(spec.type_, "pg");
        assert_eq!(
            spec.selector.get("tier").map(String::as_str),
            Some("integrated")
        );
        assert_eq!(spec.size.as_deref(), Some("small"));
    }

    #[test]
    fn size_is_optional_and_type_serializes_back() {
        let spec = ResourceClaimSpec {
            type_: "redis".into(),
            name: None,
            selector: BTreeMap::from([("tier".to_string(), "integrated".to_string())]),
            size: None,
            persistent: None,
        };
        let v = serde_json::to_value(&spec).unwrap();
        assert_eq!(v.get("type"), Some(&json!("redis")));
        assert!(v.get("size").is_none());
        assert!(v.get("persistent").is_none());
    }

    #[test]
    fn spec_name_round_trips_and_is_optional() {
        // 2.6b: a named array claim carries `spec.name`.
        let spec: ResourceClaimSpec = serde_json::from_value(json!({
            "type": "pg",
            "name": "analytics",
            "selector": { "tier": "integrated" }
        }))
        .expect("valid spec");
        assert_eq!(spec.name.as_deref(), Some("analytics"));
        let v = serde_json::to_value(&spec).unwrap();
        assert_eq!(v.get("name"), Some(&json!("analytics")));
        // Absent → omitted (the unnamed default claim).
        let unnamed: ResourceClaimSpec = serde_json::from_value(json!({
            "type": "pg",
            "selector": { "tier": "integrated" }
        }))
        .expect("valid spec");
        assert!(unnamed.name.is_none());
        let uv = serde_json::to_value(&unnamed).unwrap();
        assert!(uv.get("name").is_none());
    }

    #[test]
    fn spec_persistent_round_trips() {
        let spec: ResourceClaimSpec = serde_json::from_value(json!({
            "type": "redis",
            "selector": { "tier": "integrated" },
            "persistent": true
        }))
        .expect("valid spec");
        assert_eq!(spec.persistent, Some(true));
        let v = serde_json::to_value(&spec).unwrap();
        assert_eq!(v.get("persistent"), Some(&json!(true)));
    }

    #[test]
    fn resource_claim_status_carries_allocation() {
        let st: ResourceClaimStatus = serde_json::from_value(json!({
            "instance": "platform-redis-ephemeral-000",
            "dbnum": 7
        }))
        .unwrap();
        assert_eq!(st.instance.as_deref(), Some("platform-redis-ephemeral-000"));
        assert_eq!(st.dbnum, Some(7));
    }

    #[test]
    fn status_volume_claim_ref_round_trips() {
        let st: ResourceClaimStatus = serde_json::from_value(json!({
            "volumeClaimRef": "claim-demo-app-disk-data",
            "ready": true
        }))
        .unwrap();
        assert_eq!(
            st.volume_claim_ref.as_deref(),
            Some("claim-demo-app-disk-data")
        );
        let v = serde_json::to_value(&st).unwrap();
        assert_eq!(
            v.get("volumeClaimRef"),
            Some(&json!("claim-demo-app-disk-data"))
        );
        // Absent → omitted (skip_serializing_if).
        let empty: ResourceClaimStatus = serde_json::from_value(json!({})).unwrap();
        assert!(empty.volume_claim_ref.is_none());
        let ev = serde_json::to_value(&empty).unwrap();
        assert!(ev.get("volumeClaimRef").is_none());
    }

    #[test]
    fn status_conditions_and_renames_round_trip() {
        let status: ResourceClaimStatus = serde_json::from_value(json!({
            "provider": "pg-integrated",
            "connectionSecretRef": "demo-web-pg-conn",
            "ready": true,
            "conditions": [{
                "type": "Ready",
                "status": "True",
                "lastTransitionTime": "2026-06-02T00:00:00Z"
            }]
        }))
        .unwrap();
        assert_eq!(
            status.connection_secret_ref.as_deref(),
            Some("demo-web-pg-conn")
        );
        let c = &status.conditions.unwrap()[0];
        assert_eq!(c.type_, "Ready");
        assert_eq!(c.last_transition_time, "2026-06-02T00:00:00Z");
    }
}
