// SPDX-License-Identifier: FSL-1.1-Apache-2.0
//! Pure validator for the v1alpha1 ResourceClaim object.
//!
//! Two responsibilities:
//!
//!   1. **Operator-only CREATE.** ResourceClaims are generated by the
//!      AppRafter operator when an Application declares a `need` (the
//!      generation lands in 2.4); users must not hand-author them. On
//!      `CREATE` the requester must be the operator ServiceAccount OR a
//!      `system:masters` member (cluster-admin break-glass). `UPDATE`
//!      is NOT identity-gated — the 2.3/2.4 scheduler/controllers patch
//!      claims, possibly under a different identity.
//!   2. **Field validation** (always, regardless of identity / op):
//!      `type` in the closed built-in set, `selector` a non-empty map,
//!      `size` (if present) per-type — a t-shirt `#Size` for service
//!      claims, a Kubernetes quantity for the `disk` claim (2.6b /
//!      ADR 0043).
//!
//! Unlike the other validators it needs `request.userInfo` +
//! `request.operation`, which `server.rs` threads in only for this kind.
//!
//! Typed against `operator_core::ResourceClaimSpec` (ADR 0047
//! Decision #4): the spec is deserialized into the operator-core struct
//! once and the happy-path rules read TYPED fields (`type_`, `selector`,
//! `size`), so a renamed field fails to compile instead of silently
//! bypassing a rule. The presence ("is required") diagnostics for
//! `type`/`selector` stay on the raw `Value`: those fields are non-`Option`
//! in `ResourceClaimSpec`, so the typed struct cannot represent an absent
//! one. A non-conforming object never reaches admission in production (a
//! validating webhook runs after the apiserver's structural validation,
//! which already enforced `required: [type, selector]`); those branches
//! exist only for defence-in-depth and the unit tests below.

use operator_core::ResourceClaimSpec;
use serde_json::Value;

use crate::validator::{is_operator_or_admin, operator_service_account, ValidationError};

/// Mirrors `#PlatformServiceType` in `schemas/v1alpha1/types.cue`.
const BUILTIN_TYPES: [&str; 8] = [
    "pg",
    "jetstream",
    "clickhouse",
    "redis",
    "s3",
    "notifications",
    // 2.6b (ADR 0043): the `disk` claim type (persistent block storage).
    "disk",
    // 2.6c: the `shared-disk` claim type (shared RWX PVC for SharedVolume).
    "shared-disk",
];
/// Mirrors `#Size` in `schemas/v1alpha1/types.cue`.
const SIZES: [&str; 5] = ["nano", "small", "medium", "large", "xlarge"];

/// Validate a ResourceClaim AdmissionReview. `user_info` is
/// `request.userInfo` (may be an empty object) and `operation` is
/// `request.operation` (`CREATE`/`UPDATE`/...). Empty/missing userInfo
/// on a CREATE fails closed (rejected as non-operator).
pub fn validate_resourceclaim(
    object: &Value,
    user_info: &Value,
    operation: &str,
) -> Vec<ValidationError> {
    let mut errors = Vec::new();

    // 1. Identity gate — CREATE only. 2.16b-sec (F-1): the operator SA is
    // resolved ONCE from `OPERATOR_SERVICEACCOUNT` (env-driven, one source of
    // truth shared with the status guards), not a per-validator hardcoded const.
    if operation == "CREATE" && !is_operator_or_admin(user_info, operator_service_account()) {
        let username = user_info
            .get("username")
            .and_then(Value::as_str)
            .unwrap_or("<unknown>");
        errors.push(ValidationError::new(
            "metadata",
            format!(
                "ResourceClaim objects may only be created by the apprafter-operator; \
                 they are generated automatically when an Application declares a need \
                 (requester {username:?} denied)"
            ),
        ));
    }

    // 2. Field validations — always.
    let Some(obj) = object.as_object() else {
        errors.push(ValidationError::new(
            "object",
            "ResourceClaim object must be a JSON object",
        ));
        return errors;
    };
    let Some(spec_value) = obj.get("spec").filter(|s| s.is_object()) else {
        errors.push(ValidationError::new("spec", "spec is required"));
        return errors;
    };

    // Deserialize the spec into the typed operator-core struct. In
    // production this always succeeds — a validating webhook runs after the
    // apiserver's structural validation, which already enforced
    // `required: [type, selector]` and the field types. When it succeeds the
    // happy-path rules read the TYPED fields, so a renamed field fails to
    // compile instead of silently bypassing a rule (ADR 0047 #4).
    //
    // `type`/`selector` are non-`Option` in `ResourceClaimSpec`, so the typed
    // struct cannot represent an *absent* field; the per-field presence
    // ("is required") branches below therefore stay on the raw `Value`,
    // matching the pre-refactor `as_str()`/`as_object()` semantics exactly (a
    // field that is not a usable string/map is treated as missing). They are
    // only reachable in tests / a misconfigured apiserver.
    let typed = serde_json::from_value::<ResourceClaimSpec>(spec_value.clone()).ok();
    let spec = spec_value.as_object().expect("filtered to an object above");

    match (typed.as_ref(), spec.get("type").and_then(Value::as_str)) {
        // Happy path: read the typed field so the compiler gates `type_`.
        (Some(t), Some(_)) if BUILTIN_TYPES.contains(&t.type_.as_str()) => {}
        (_, Some(t)) if BUILTIN_TYPES.contains(&t) => {}
        (_, Some(t)) => errors.push(ValidationError::new(
            "spec.type",
            format!(
                "type must be one of {} (got {t:?})",
                BUILTIN_TYPES.join("|")
            ),
        )),
        (_, None) => errors.push(ValidationError::new("spec.type", "spec.type is required")),
    }

    match (
        typed.as_ref(),
        spec.get("selector").and_then(Value::as_object),
    ) {
        // Happy path: read the typed field so the compiler gates `selector`.
        (Some(t), Some(_)) if !t.selector.is_empty() => {}
        (_, Some(m)) if !m.is_empty() => {}
        (_, Some(_)) => errors.push(ValidationError::new(
            "spec.selector",
            "spec.selector must not be empty (it routes the claim to a ServiceProvider)",
        )),
        (_, None) => errors.push(ValidationError::new(
            "spec.selector",
            "spec.selector is required",
        )),
    }

    // `spec.size` is a per-type field (2.6b / ADR 0043): a t-shirt hint
    // for service claims (pg/redis/…) but a Kubernetes quantity (the
    // storage capacity) for the `disk` claim. The CRD dropped its t-shirt
    // enum; the webhook is the per-type gate. The "must be a string" guard
    // is shared by both branches. The typed `size`/`type_` drive the happy
    // path (gating the renames); the not-a-string branch stays on the raw
    // `Value` because `Option<String>` cannot represent a non-string input.
    if let Some(size) = spec.get("size") {
        let claim_type = typed
            .as_ref()
            .map(|t| t.type_.as_str())
            .or_else(|| spec.get("type").and_then(Value::as_str));
        let typed_size = typed.as_ref().and_then(|t| t.size.as_deref());
        match typed_size.or_else(|| size.as_str()) {
            Some(s) if claim_type == Some("disk") => {
                if !is_k8s_quantity(s) {
                    errors.push(ValidationError::new(
                        "spec.size",
                        format!("disk size must be a Kubernetes quantity (e.g. 10Gi); got {s:?}"),
                    ));
                }
            }
            Some(s) if SIZES.contains(&s) => {}
            Some(s) => errors.push(ValidationError::new(
                "spec.size",
                format!("size must be one of {} (got {s:?})", SIZES.join("|")),
            )),
            None => errors.push(ValidationError::new(
                "spec.size",
                "size must be a string (a t-shirt size for service claims, a \
                 Kubernetes quantity for disk)",
            )),
        }
    }

    errors
}

/// 2.6b (ADR 0043): a Kubernetes resource quantity for the disk `size`.
/// A decimal magnitude with an optional binary (Ei…Ki) or decimal
/// (E…k, with lower-case `k`) SI suffix.
/// KEEP IN SYNC with `validator.rs::is_k8s_quantity` (the disk-needs
/// guard on the Application object uses the same grammar).
fn is_k8s_quantity(s: &str) -> bool {
    let suffix_ok = |suffix: &str| -> bool {
        matches!(
            suffix,
            "" | "Ei" | "Pi" | "Ti" | "Gi" | "Mi" | "Ki" | "E" | "P" | "T" | "G" | "M" | "k"
        )
    };
    // Split the leading numeric magnitude (digits, optionally one '.'
    // followed by digits) from the trailing suffix.
    let mut chars = s.char_indices().peekable();
    let mut seen_digit = false;
    let mut seen_dot = false;
    let mut split = s.len();
    while let Some(&(i, ch)) = chars.peek() {
        match ch {
            '0'..='9' => {
                seen_digit = true;
                chars.next();
            }
            '.' if !seen_dot => {
                seen_dot = true;
                chars.next();
            }
            _ => {
                split = i;
                break;
            }
        }
    }
    if !seen_digit {
        return false;
    }
    let (magnitude, suffix) = s.split_at(split);
    // A trailing '.' with no fractional digits is malformed.
    if magnitude.ends_with('.') {
        return false;
    }
    suffix_ok(suffix)
}

#[cfg(test)]
mod tests {
    use super::*;
    use serde_json::json;

    /// The default operator SA (`operator_service_account()` resolves to this
    /// when `OPERATOR_SERVICEACCOUNT` is unset — the in-test fallback).
    const OPERATOR_SA: &str = "system:serviceaccount:apprafter-system:apprafter-operator";

    fn claim() -> Value {
        json!({
            "metadata": { "name": "demo-web-pg", "namespace": "demo" },
            "spec": { "type": "pg", "selector": { "tier": "integrated" }, "size": "small" }
        })
    }
    fn operator_user() -> Value {
        json!({ "username": OPERATOR_SA, "groups": ["system:serviceaccounts"] })
    }
    fn admin_user() -> Value {
        json!({ "username": "kubernetes-admin", "groups": ["system:masters", "system:authenticated"] })
    }
    fn normal_user() -> Value {
        json!({ "username": "alice", "groups": ["system:authenticated"] })
    }

    #[test]
    fn allows_operator_create() {
        assert!(validate_resourceclaim(&claim(), &operator_user(), "CREATE").is_empty());
    }

    #[test]
    fn allows_system_masters_create() {
        assert!(validate_resourceclaim(&claim(), &admin_user(), "CREATE").is_empty());
    }

    #[test]
    fn rejects_user_create() {
        let errors = validate_resourceclaim(&claim(), &normal_user(), "CREATE");
        assert!(errors
            .iter()
            .any(|e| e.field == "metadata" && e.message.contains("apprafter-operator")));
        assert!(errors.iter().any(|e| e.message.contains("alice")));
    }

    #[test]
    fn rejects_create_with_empty_userinfo_fails_closed() {
        let errors = validate_resourceclaim(&claim(), &json!({}), "CREATE");
        assert!(errors.iter().any(|e| e.field == "metadata"));
    }

    #[test]
    fn allows_non_operator_update() {
        assert!(validate_resourceclaim(&claim(), &normal_user(), "UPDATE").is_empty());
    }

    #[test]
    fn rejects_bad_type_regardless_of_identity() {
        let mut c = claim();
        c["spec"]["type"] = json!("kafka");
        let errors = validate_resourceclaim(&c, &operator_user(), "CREATE");
        assert!(errors.iter().any(|e| e.field == "spec.type"));
    }

    #[test]
    fn rejects_empty_selector() {
        let mut c = claim();
        c["spec"]["selector"] = json!({});
        let errors = validate_resourceclaim(&c, &operator_user(), "CREATE");
        assert!(errors.iter().any(|e| e.field == "spec.selector"));
    }

    #[test]
    fn rejects_missing_selector() {
        let mut c = claim();
        c["spec"].as_object_mut().unwrap().remove("selector");
        let errors = validate_resourceclaim(&c, &operator_user(), "CREATE");
        assert!(errors.iter().any(|e| e.field == "spec.selector"));
    }

    #[test]
    fn rejects_bad_size() {
        let mut c = claim();
        c["spec"]["size"] = json!("enormous");
        let errors = validate_resourceclaim(&c, &operator_user(), "CREATE");
        assert!(errors.iter().any(|e| e.field == "spec.size"));
    }

    // 2.6b (ADR 0043): `spec.size` is a per-type field — a t-shirt hint
    // for service claims (pg/redis/…) but a Kubernetes quantity for the
    // `disk` claim (the disk's storage capacity). The CRD enum is gone;
    // the webhook is the per-type gate.

    #[test]
    fn accepts_disk_quantity_size() {
        // A disk claim carries a quantity (e.g. "1Gi") as its size.
        let mut c = claim();
        c["spec"]["type"] = json!("disk");
        c["spec"]["size"] = json!("1Gi");
        assert!(
            validate_resourceclaim(&c, &operator_user(), "CREATE").is_empty(),
            "disk claim with a quantity size should be accepted"
        );
    }

    #[test]
    fn rejects_disk_tshirt_size() {
        // A t-shirt size is not a valid quantity for a disk claim.
        let mut c = claim();
        c["spec"]["type"] = json!("disk");
        c["spec"]["size"] = json!("small");
        let errors = validate_resourceclaim(&c, &operator_user(), "CREATE");
        assert!(errors.iter().any(|e| e.field == "spec.size"));
    }

    #[test]
    fn rejects_service_quantity_size() {
        // A quantity is not a valid t-shirt size for a service claim.
        let mut c = claim(); // type pg
        c["spec"]["size"] = json!("1Gi");
        let errors = validate_resourceclaim(&c, &operator_user(), "CREATE");
        assert!(errors.iter().any(|e| e.field == "spec.size"));
    }

    #[test]
    fn accepts_service_tshirt_size() {
        // The historical t-shirt path is unchanged for service claims.
        let mut c = claim(); // type pg
        c["spec"]["size"] = json!("small");
        assert!(
            validate_resourceclaim(&c, &operator_user(), "CREATE").is_empty(),
            "pg claim with a t-shirt size should be accepted"
        );
    }

    #[test]
    fn user_create_with_bad_fields_reports_both_identity_and_field() {
        let mut c = claim();
        c["spec"]["type"] = json!("kafka");
        let errors = validate_resourceclaim(&c, &normal_user(), "CREATE");
        assert!(errors.iter().any(|e| e.field == "metadata"));
        assert!(errors.iter().any(|e| e.field == "spec.type"));
    }

    #[test]
    fn rejects_missing_spec() {
        let obj = json!({ "metadata": { "name": "x", "namespace": "demo" } });
        let errors = validate_resourceclaim(&obj, &operator_user(), "CREATE");
        assert!(errors.iter().any(|e| e.field == "spec"));
    }

    #[test]
    fn accepts_every_builtin_type_for_operator() {
        for t in BUILTIN_TYPES {
            let mut c = claim();
            c["spec"]["type"] = json!(t);
            // `size` is per-type: a quantity for disk, a t-shirt otherwise.
            if t == "disk" {
                c["spec"]["size"] = json!("1Gi");
            }
            assert!(
                validate_resourceclaim(&c, &operator_user(), "CREATE").is_empty(),
                "builtin type {t} should be accepted"
            );
        }
    }

    #[test]
    fn accepts_disk_type_for_operator() {
        // 2.6b (ADR 0043): the `disk` claim type is generated by the
        // Application controller for a `needs.disk` entry and must be
        // accepted (the disk provisioner lands in 2.6b-3). Its `size` is
        // a Kubernetes quantity, not a t-shirt.
        let mut c = claim();
        c["spec"]["type"] = json!("disk");
        c["spec"]["size"] = json!("1Gi");
        assert!(
            validate_resourceclaim(&c, &operator_user(), "CREATE").is_empty(),
            "disk claim type should be accepted"
        );
    }

    #[test]
    fn update_skips_identity_but_still_field_validates() {
        let mut c = claim();
        c["spec"]["type"] = json!("kafka");
        let errors = validate_resourceclaim(&c, &normal_user(), "UPDATE");
        // No identity error on UPDATE...
        assert!(!errors.iter().any(|e| e.field == "metadata"));
        // ...but the bad type is still caught.
        assert!(errors.iter().any(|e| e.field == "spec.type"));
    }
}
