// SPDX-License-Identifier: FSL-1.1-Apache-2.0
//! Pure validator for the v1alpha1 ResourceClaim object.
//!
//! Two responsibilities:
//!
//!   1. **Operator-only CREATE.** ResourceClaims are generated by the
//!      AppRafter operator when an Application declares a `need` (the
//!      generation lands in 2.4); users must not hand-author them. On
//!      `CREATE` the requester must be the operator ServiceAccount OR a
//!      `system:masters` member (cluster-admin break-glass). `UPDATE`
//!      is NOT identity-gated — the 2.3/2.4 scheduler/controllers patch
//!      claims, possibly under a different identity.
//!   2. **Field validation** (always, regardless of identity / op):
//!      `type` in the closed built-in set, `selector` a non-empty map,
//!      `size` (if present) in the closed `#Size` set.
//!
//! Unlike the other validators it needs `request.userInfo` +
//! `request.operation`, which `server.rs` threads in only for this kind.

use serde_json::Value;

use crate::validator::ValidationError;

/// The operator's ServiceAccount username (default Helm release name
/// `apprafter-operator` in namespace `apprafter-system`). Re-verify in
/// 2.4 when the Application controller actually creates claims, and if
/// HA changes the SA naming.
const OPERATOR_SA: &str = "system:serviceaccount:apprafter-system:apprafter-operator";
/// Mirrors `#PlatformServiceType` in `schemas/v1alpha1/types.cue`.
const BUILTIN_TYPES: [&str; 6] = [
    "pg",
    "jetstream",
    "clickhouse",
    "redis",
    "s3",
    "notifications",
];
/// Mirrors `#Size` in `schemas/v1alpha1/types.cue`.
const SIZES: [&str; 5] = ["nano", "small", "medium", "large", "xlarge"];

/// Validate a ResourceClaim AdmissionReview. `user_info` is
/// `request.userInfo` (may be an empty object) and `operation` is
/// `request.operation` (`CREATE`/`UPDATE`/...). Empty/missing userInfo
/// on a CREATE fails closed (rejected as non-operator).
pub fn validate_resourceclaim(
    object: &Value,
    user_info: &Value,
    operation: &str,
) -> Vec<ValidationError> {
    let mut errors = Vec::new();

    // 1. Identity gate — CREATE only.
    if operation == "CREATE" && !is_operator_or_admin(user_info) {
        let username = user_info
            .get("username")
            .and_then(Value::as_str)
            .unwrap_or("<unknown>");
        errors.push(ValidationError::new(
            "metadata",
            format!(
                "ResourceClaim objects may only be created by the apprafter-operator; \
                 they are generated automatically when an Application declares a need \
                 (requester {username:?} denied)"
            ),
        ));
    }

    // 2. Field validations — always.
    let Some(obj) = object.as_object() else {
        errors.push(ValidationError::new(
            "object",
            "ResourceClaim object must be a JSON object",
        ));
        return errors;
    };
    let Some(spec) = obj.get("spec").and_then(Value::as_object) else {
        errors.push(ValidationError::new("spec", "spec is required"));
        return errors;
    };

    match spec.get("type").and_then(Value::as_str) {
        Some(t) if BUILTIN_TYPES.contains(&t) => {}
        Some(t) => errors.push(ValidationError::new(
            "spec.type",
            format!(
                "type must be one of {} (got {t:?})",
                BUILTIN_TYPES.join("|")
            ),
        )),
        None => errors.push(ValidationError::new("spec.type", "spec.type is required")),
    }

    match spec.get("selector").and_then(Value::as_object) {
        Some(m) if !m.is_empty() => {}
        Some(_) => errors.push(ValidationError::new(
            "spec.selector",
            "spec.selector must not be empty (it routes the claim to a ServiceProvider)",
        )),
        None => errors.push(ValidationError::new(
            "spec.selector",
            "spec.selector is required",
        )),
    }

    if let Some(size) = spec.get("size") {
        match size.as_str() {
            Some(s) if SIZES.contains(&s) => {}
            Some(s) => errors.push(ValidationError::new(
                "spec.size",
                format!("size must be one of {} (got {s:?})", SIZES.join("|")),
            )),
            None => errors.push(ValidationError::new(
                "spec.size",
                format!("size must be a string, one of {}", SIZES.join("|")),
            )),
        }
    }

    errors
}

fn is_operator_or_admin(user_info: &Value) -> bool {
    let is_operator = user_info.get("username").and_then(Value::as_str) == Some(OPERATOR_SA);
    // Cluster-admin break-glass — `system:masters` or, on kubeadm >= 1.29
    // (k8s 1.35 / kind), `kubeadm:cluster-admins`; either is omnipotent.
    let is_admin = user_info
        .get("groups")
        .and_then(Value::as_array)
        .is_some_and(|groups| {
            groups.iter().any(|g| {
                matches!(
                    g.as_str(),
                    Some("system:masters" | "kubeadm:cluster-admins")
                )
            })
        });
    is_operator || is_admin
}

#[cfg(test)]
mod tests {
    use super::*;
    use serde_json::json;

    fn claim() -> Value {
        json!({
            "metadata": { "name": "demo-web-pg", "namespace": "demo" },
            "spec": { "type": "pg", "selector": { "tier": "integrated" }, "size": "small" }
        })
    }
    fn operator_user() -> Value {
        json!({ "username": OPERATOR_SA, "groups": ["system:serviceaccounts"] })
    }
    fn admin_user() -> Value {
        json!({ "username": "kubernetes-admin", "groups": ["system:masters", "system:authenticated"] })
    }
    fn normal_user() -> Value {
        json!({ "username": "alice", "groups": ["system:authenticated"] })
    }

    #[test]
    fn allows_operator_create() {
        assert!(validate_resourceclaim(&claim(), &operator_user(), "CREATE").is_empty());
    }

    #[test]
    fn allows_system_masters_create() {
        assert!(validate_resourceclaim(&claim(), &admin_user(), "CREATE").is_empty());
    }

    #[test]
    fn rejects_user_create() {
        let errors = validate_resourceclaim(&claim(), &normal_user(), "CREATE");
        assert!(errors
            .iter()
            .any(|e| e.field == "metadata" && e.message.contains("apprafter-operator")));
        assert!(errors.iter().any(|e| e.message.contains("alice")));
    }

    #[test]
    fn rejects_create_with_empty_userinfo_fails_closed() {
        let errors = validate_resourceclaim(&claim(), &json!({}), "CREATE");
        assert!(errors.iter().any(|e| e.field == "metadata"));
    }

    #[test]
    fn allows_non_operator_update() {
        assert!(validate_resourceclaim(&claim(), &normal_user(), "UPDATE").is_empty());
    }

    #[test]
    fn rejects_bad_type_regardless_of_identity() {
        let mut c = claim();
        c["spec"]["type"] = json!("kafka");
        let errors = validate_resourceclaim(&c, &operator_user(), "CREATE");
        assert!(errors.iter().any(|e| e.field == "spec.type"));
    }

    #[test]
    fn rejects_empty_selector() {
        let mut c = claim();
        c["spec"]["selector"] = json!({});
        let errors = validate_resourceclaim(&c, &operator_user(), "CREATE");
        assert!(errors.iter().any(|e| e.field == "spec.selector"));
    }

    #[test]
    fn rejects_missing_selector() {
        let mut c = claim();
        c["spec"].as_object_mut().unwrap().remove("selector");
        let errors = validate_resourceclaim(&c, &operator_user(), "CREATE");
        assert!(errors.iter().any(|e| e.field == "spec.selector"));
    }

    #[test]
    fn rejects_bad_size() {
        let mut c = claim();
        c["spec"]["size"] = json!("enormous");
        let errors = validate_resourceclaim(&c, &operator_user(), "CREATE");
        assert!(errors.iter().any(|e| e.field == "spec.size"));
    }

    #[test]
    fn user_create_with_bad_fields_reports_both_identity_and_field() {
        let mut c = claim();
        c["spec"]["type"] = json!("kafka");
        let errors = validate_resourceclaim(&c, &normal_user(), "CREATE");
        assert!(errors.iter().any(|e| e.field == "metadata"));
        assert!(errors.iter().any(|e| e.field == "spec.type"));
    }

    #[test]
    fn rejects_missing_spec() {
        let obj = json!({ "metadata": { "name": "x", "namespace": "demo" } });
        let errors = validate_resourceclaim(&obj, &operator_user(), "CREATE");
        assert!(errors.iter().any(|e| e.field == "spec"));
    }

    #[test]
    fn accepts_every_builtin_type_for_operator() {
        for t in BUILTIN_TYPES {
            let mut c = claim();
            c["spec"]["type"] = json!(t);
            assert!(
                validate_resourceclaim(&c, &operator_user(), "CREATE").is_empty(),
                "builtin type {t} should be accepted"
            );
        }
    }

    #[test]
    fn update_skips_identity_but_still_field_validates() {
        let mut c = claim();
        c["spec"]["type"] = json!("kafka");
        let errors = validate_resourceclaim(&c, &normal_user(), "UPDATE");
        // No identity error on UPDATE...
        assert!(!errors.iter().any(|e| e.field == "metadata"));
        // ...but the bad type is still caught.
        assert!(errors.iter().any(|e| e.field == "spec.type"));
    }
}
